import 'reflect-metadata';
import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { calculateWorkTimePlan } from './work-time-plan';
import { correctionTouches, sheetDays, sheetEmployee, sheetSummary, SheetSession } from './timesheet.policy';
import { TimesheetQueryDto } from './timesheet.dto';
const days=sheetDays('2026-09','Europe/Moscow'),period={start:days[0].start,end:days[29].end},now=new Date('2026-10-02T12:00Z');
const session=(start:string,end:string|null):SheetSession=>({id:'s',timezone:'Europe/Moscow',version:1,startedAt:new Date(start),endedAt:end?new Date(end):null,breaks:[]});
const emptyPlan=()=>calculateWorkTimePlan([],[],period);
const plan=()=>calculateWorkTimePlan([{kind:'SHIFT',status:'PUBLISHED',startsAt:new Date('2026-09-01T06:00Z'),endsAt:new Date('2026-09-01T15:00Z'),plannedMinutes:480}],[],period);
describe('Team timesheet calculations',()=>{
  it('creates all dates in report timezone',()=>{expect(days).toHaveLength(30);expect(days[0].start.toISOString()).toBe('2026-08-31T21:00:00.000Z');expect(days[29].end.toISOString()).toBe('2026-09-30T21:00:00.000Z');});
  it('handles leap February and final supported month',()=>{expect(sheetDays('2028-02','UTC')).toHaveLength(29);expect(sheetDays('2099-12','UTC')[30].end.toISOString()).toBe('2100-01-01T00:00:00.000Z');});
  it('uses 25 real hours for DST boundary day',()=>{const day=sheetDays('2026-10','Europe/Berlin')[24];expect(+day.end-+day.start).toBe(25*3600000);});
  it('separates night work and exact breaks between dates',()=>{
    const row={...session('2026-09-01T20:00Z','2026-09-02T02:00Z'),breaks:[{startedAt:new Date('2026-09-01T20:30Z'),endedAt:new Date('2026-09-01T21:30Z')}]};
    const result=sheetEmployee([row],emptyPlan(),[],days,now);
    expect(result.workedMs).toBe(5*3600000);expect(result.days[0].workedMs).toBe(1800000);expect(result.days[1].workedMs).toBe(16200000);expect(result.days[0].breakMs).toBe(1800000);
  });
  it('keeps only the intersecting portion at month boundary',()=>{const result=sheetEmployee([session('2026-08-31T20:00Z','2026-08-31T23:00Z')],emptyPlan(),[],days,now);expect(result.workedMs).toBe(7200000);});
  it('excludes intervals ending at month start',()=>expect(sheetEmployee([session('2026-08-31T20:00Z','2026-08-31T21:00Z')],emptyPlan(),[],days,now).workedMs).toBe(0));
  it('marks planned completed date without records for verification',()=>{const row=sheetEmployee([],plan(),[],days,now);expect(row.issues.missing).toBe(1);expect(row.needsAttention).toBe(true);expect(row.days[0].issues.missing).toBe(true);});
  it('does not mark future/today planned dates as absence',()=>expect(sheetEmployee([],plan(),[],days,new Date('2026-09-01T12:00Z')).issues.missing).toBe(0));
  it('does not count unplanned rest as missing work',()=>expect(sheetEmployee([],emptyPlan(),[],days,now).needsAttention).toBe(false));
  it('shows unknown plan as null, not zero',()=>{const unavailable={...emptyPlan(),available:false,plannedMs:null,shifts:null,warning:'Bad pattern'};const row=sheetEmployee([],unavailable,[],days,now);expect(row.plannedMs).toBeNull();expect(row.days[0].plannedMs).toBeNull();expect(row.issues.planUnavailable).toBe(true);expect(row.workedMs).toBe(0);});
  it('does not report overlapping actual records as a valid double total',()=>{const row=sheetEmployee([session('2026-09-01T06:00Z','2026-09-01T09:00Z'),{...session('2026-09-01T08:00Z','2026-09-01T10:00Z'),id:'b'}],emptyPlan(),[],days,now);expect(row.workedMs).toBeNull();expect(row.days[0].issues.overlap).toBe(true);expect(row.days[1].workedMs).toBe(0);});
  it('allows touching consecutive intervals',()=>expect(sheetEmployee([session('2026-09-01T06:00Z','2026-09-01T09:00Z'),session('2026-09-01T09:00Z','2026-09-01T10:00Z')],emptyPlan(),[],days,now).workedMs).toBe(14400000));
  it('counts one long open interval once in month, not once per day',()=>{const row=sheetEmployee([session('2026-09-01T06:00Z',null)],emptyPlan(),[],days,now);expect(row.issues.unclosed).toBe(1);expect(row.days[0].issues.unclosed).toBe(1);});
  it('does not classify a current overnight shift under 24h as forgotten',()=>{const row=sheetEmployee([session('2026-09-01T20:00Z',null)],emptyPlan(),[],days,new Date('2026-09-02T01:00Z'));expect(row.openSessions).toBe(1);expect(row.needsAttention).toBe(false);expect(row.days.some(d=>d.issues.unclosed)).toBe(false);});
  const correction={id:'r',startedAt:new Date('2026-10-01T06:00Z'),endedAt:new Date('2026-10-01T15:00Z'),original:{startedAt:'2026-09-01T06:00Z',endedAt:'2026-09-01T15:00Z'}};
  it('flags both months if correction moves a recorded day',()=>{expect(correctionTouches(correction,period.start,period.end,now)).toBe(true);const oct=sheetDays('2026-10','Europe/Moscow');expect(correctionTouches(correction,oct[0].start,oct[30].end,now)).toBe(true);});
  it('counts a pending proposal only once in summary and not as actual work',()=>{const row=sheetEmployee([],emptyPlan(),[correction],days,now);expect(row.issues.pending).toBe(1);expect(row.workedMs).toBe(0);expect(row.days[0].pendingIds).toEqual(['r']);});
  it('does not mark future dates from an open original snapshot',()=>expect(correctionTouches({...correction,startedAt:new Date('2026-08-01'),endedAt:new Date('2026-08-02'),original:{startedAt:'2026-09-01T00:00Z',endedAt:null}},new Date('2026-12-01'),new Date('2027-01-01'),now)).toBe(false));
  it('preserves precise totals, never adds proposal time',()=>{const row=sheetEmployee([session('2026-09-01T06:00:32.123Z','2026-09-01T07:00Z')],emptyPlan(),[correction],days,now);expect(row.workedMs).toBe(3567877);});
  it('summarizes all filtered rows, not one page',()=>{const row=sheetEmployee([session('2026-09-01T06:00Z','2026-09-01T07:00Z')],plan(),[],days,now);const total=sheetSummary(Array(30).fill(row));expect(total.employees).toBe(30);expect(total.workedMs).toBe(30*3600000);expect(total.plannedMs).toBe(30*8*3600000);});
  it('does not show partial total if one actual row is invalid',()=>{const row=sheetEmployee([],plan(),[],days,now);expect(sheetSummary([row,{...row,workedMs:null}])).toMatchObject({workedMs:null,unavailableActual:1});});
  it('handles empty filtered result',()=>expect(sheetSummary([])).toMatchObject({employees:0,attention:0,workedMs:0,plannedMs:0}));
  it.each([{month:'2026-13'},{month:'2100-01'},{departmentId:'foreign'},{page:0},{view:'ALL_COMPANY'},{search:'x'.repeat(81)},{employeeId:'forged'}])('rejects malformed/forged query %j',async patch=>expect((await validate(plainToInstance(TimesheetQueryDto,{month:'2026-09',...patch}),{whitelist:true,forbidNonWhitelisted:true})).length).toBeGreaterThan(0));
  it('accepts report filters and converts query page',async()=>{const dto=plainToInstance(TimesheetQueryDto,{month:'2026-09',search:' Иван ',page:'2',view:'ATTENTION'});expect(await validate(dto)).toHaveLength(0);expect(dto.page).toBe(2);expect(dto.search).toBe('Иван');});
});
