CREATE TABLE "CrmLeadFile" (
 "leadId" TEXT NOT NULL, "nodeId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "CrmLeadFile_pkey" PRIMARY KEY ("leadId","nodeId"),
 CONSTRAINT "CrmLeadFile_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT "CrmLeadFile_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "CrmDriveNode"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
