<script setup lang="ts">
import { Check, Copy, MapPin, Package, Phone, X } from '@lucide/vue';
const selected = useState<any | null>('admin-order-selected', () => null); const copied = ref(false);
const statuses: Record<string, string> = { NEW: 'Новый', CONFIRMED: 'Подтверждён', PAID: 'Оплачен', ASSEMBLING: 'Сборка', SHIPPED: 'Отправлен', DELIVERED: 'Доставлен', CANCELLED: 'Отменён', REFUNDED: 'Возврат' };
const address = computed(() => { const value = selected.value?.shippingAddress; if (!value) return 'Адрес доставки не указан'; if (typeof value === 'string') return value; return Object.values(value).filter(Boolean).join(', '); });
async function copyNumber() { if (!selected.value) return; await navigator.clipboard?.writeText(selected.value.orderNumber); copied.value = true; setTimeout(() => copied.value = false, 1600); }
</script>
<template>
  <aside v-if="selected" class="order-backdrop" @click.self="selected=null"><section class="order-drawer"><header class="drawer-header"><div><p class="eyebrow">ЗАКАЗ МАГАЗИНА</p><div class="number-line"><h2>{{ selected.orderNumber }}</h2><button @click="copyNumber" title="Скопировать номер"><Check v-if="copied" :size="15" /><Copy v-else :size="15" /></button></div><span>{{ new Date(selected.createdAt).toLocaleString('ru-RU') }}</span></div><button class="close" @click="selected=null"><X :size="19" /></button></header><div class="drawer-body"><div class="order-summary"><div><span>Статус</span><strong :class="`status-${selected.status.toLowerCase()}`">{{ statuses[selected.status] || selected.status }}</strong></div><div><span>Оплата</span><strong>{{ statuses[selected.paymentStatus] || selected.paymentStatus }}</strong></div><div><span>Итого</span><strong>{{ Number(selected.finalAmount || 0).toLocaleString('ru-RU') }} ₽</strong></div></div><section class="detail-section"><h3><Package :size="16" /> Состав заказа</h3><div v-for="item in selected.items" :key="item.id" class="item"><div><strong>{{ item.productName }}</strong><small>{{ item.variantName }} · {{ item.quantity }} шт.</small></div><span>{{ Number(item.total || 0).toLocaleString('ru-RU') }} ₽</span></div><p v-if="!selected.items?.length" class="muted">Состав не указан</p></section><section class="detail-section"><h3><Phone :size="16" /> Клиент</h3><div class="client"><strong>{{ [selected.user?.firstName, selected.user?.lastName].filter(Boolean).join(' ') || 'Гость' }}</strong><span>{{ selected.user?.email || 'Email не указан' }}</span><span>{{ selected.user?.phone || 'Телефон не указан' }}</span></div></section><section class="detail-section"><h3><MapPin :size="16" /> Доставка</h3><p class="address">{{ address }}</p><p v-if="selected.shippingProvider || selected.trackingNumber" class="delivery-meta">{{ selected.shippingProvider || 'Служба доставки' }} <b v-if="selected.trackingNumber">· {{ selected.trackingNumber }}</b></p></section><section class="detail-section history"><h3>История статусов</h3><div v-for="entry in selected.history" :key="entry.id" class="history-row"><i></i><div><strong>{{ statuses[entry.toStatus] || entry.toStatus }}</strong><small>{{ new Date(entry.createdAt).toLocaleString('ru-RU') }}<template v-if="entry.comment"> · {{ entry.comment }}</template></small></div></div><p v-if="!selected.history?.length" class="muted">История пока пуста</p></section></div></section></aside>
</template>
<style scoped>
.order-backdrop{position:fixed;inset:0;background:#1115;z-index:450}.order-drawer{position:absolute;right:0;top:0;bottom:0;width:min(560px,94vw);background:#fff;display:flex;flex-direction:column;box-shadow:-12px 0 40px #1112}.drawer-header{padding:28px 30px 22px;border-bottom:1px solid #e8e9ec;display:flex;justify-content:space-between}.eyebrow{font-size:10px;letter-spacing:.15em;color:#f15b49;margin:0 0 8px}.drawer-header h2{font-size:24px;margin:0}.drawer-header span{font-size:11px;color:#858991}.number-line{display:flex;gap:9px;align-items:center}.number-line button,.close{border:0;background:none;color:#858991;cursor:pointer}.close{margin-top:-5px}.drawer-body{padding:24px 30px;overflow:auto}.order-summary{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;background:#f6f7f8;padding:15px;margin-bottom:24px}.order-summary div{display:grid;gap:7px}.order-summary span,.detail-section small,.muted{font-size:10px;color:#858991}.order-summary strong{font-size:12px}.status-new,.status-cancelled,.status-refunded{color:#c45c4d!important}.status-delivered,.status-paid{color:#2c9566!important}.detail-section{border-top:1px solid #ececef;padding:20px 0}.detail-section h3{display:flex;align-items:center;gap:7px;font-size:13px;margin:0 0 14px}.item,.client{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-bottom:1px solid #f0f1f2;font-size:12px}.item div,.client{display:grid;gap:5px}.item small,.client span{font-size:10px;color:#858991}.address{font-size:12px;line-height:1.6;margin:0}.delivery-meta{font-size:11px;color:#858991}.history-row{display:flex;gap:11px;position:relative;padding:0 0 16px}.history-row:last-child{padding-bottom:0}.history-row i{width:8px;height:8px;border-radius:50%;background:#f15b49;margin-top:4px;flex:none}.history-row div{display:grid;gap:5px}.history-row strong{font-size:12px}.history-row small{font-size:10px;color:#858991}@media(max-width:600px){.drawer-header,.drawer-body{padding-left:20px;padding-right:20px}}
</style>
