<script setup lang="ts">
import { BarChart3, CalendarDays, ChevronDown, CircleHelp, ClipboardList, LogOut, PackageSearch, Scissors, Settings, ShoppingBag, Users } from '@lucide/vue';
const route = useRoute(); const config = useRuntimeConfig(); const { user, logout } = useB2BSession(); const { openProfile } = useUserProfilePanel(); const open = ref(false);
const items = [
  { id:'dashboard',label:'Обзор бизнеса',icon:BarChart3 }, { id:'calendar',label:'Записи',icon:CalendarDays },
  { id:'clients',label:'Мои клиенты',icon:Users }, { id:'services',label:'Услуги и цены',icon:Scissors },
  { id:'catalog',label:'Закупить товары',icon:PackageSearch }, { id:'orders',label:'Мои заказы',icon:ShoppingBag },
  { id:'team',label:'Команда',icon:ClipboardList }, { id:'support',label:'Поддержка',icon:CircleHelp },
];
const section=computed(()=>String(route.query.section||'dashboard'));
function signOut(){logout();navigateTo('/b2b-login')}
onMounted(()=>{if(user.value?.forcePasswordChange)openProfile()});
watch(()=>user.value?.forcePasswordChange,(required)=>{if(required)openProfile()});
</script>
<template><aside class="b2b-rail"><NuxtLink to="/b2b" class="brand"><img src="/sarkisian-logo.png" alt="SARKISIAN" /></NuxtLink><button class="company" @click="open=!open"><Settings :size="17"/><span><small>КАБИНЕТ ПАРТНЁРА</small><strong>B2B-кабинет</strong></span><ChevronDown :size="14"/></button><div v-if="open" class="company-note">Управление салоном, клиентами, записью и закупками в одном месте.</div><nav><NuxtLink v-for="item in items" :key="item.id" :to="item.id==='dashboard'?'/b2b':`/b2b?section=${item.id}`" :class="{active:section===item.id}"><component :is="item.icon" :size="18"/><span>{{item.label}}</span></NuxtLink></nav><div class="bottom"><NuxtLink to="/"><ShoppingBag :size="17"/><span>Открыть магазин</span></NuxtLink><button @click="signOut"><LogOut :size="17"/><span>Выйти</span></button><button class="person" title="Открыть профиль" @click="openProfile"><i><img v-if="user?.avatarUrl" :src="new URL(user.avatarUrl,config.public.apiBase).toString()" alt=""/><template v-else>{{(user?.firstName||user?.email||'B').slice(0,1).toUpperCase()}}</template></i><span><b>{{[user?.firstName,user?.lastName].filter(Boolean).join(' ')||'Партнёр'}}</b><small>{{user?.email}}</small></span></button></div></aside></template>
<style scoped>
.b2b-rail{position:fixed;z-index:400;inset:0 auto 0 0;width:250px;background:#191919;padding:18px 12px;box-sizing:border-box;color:#fff;display:flex;flex-direction:column;font-family:var(--sb-font)}.brand{display:block;padding:8px 10px 20px;flex-shrink:0}.brand img{width:145px;filter:brightness(0) invert(1)}.company{height:58px;border:1px solid #3a3a3d;background:#252528;color:#fff;border-radius:8px;padding:0 11px;display:flex;align-items:center;gap:10px;text-align:left;flex-shrink:0}.company>svg:first-child{color:var(--sb-coral)}.company>svg:last-child{margin-left:auto;color:#8f9197}.company span{display:grid;gap:3px}.company small{font-size:8px;letter-spacing:.1em;color:#8f9197}.company strong{font-size:12px;font-weight:500}.company-note{position:absolute;left:14px;top:115px;width:260px;background:#fff;color:#62656b;border:1px solid var(--sb-line);box-shadow:0 18px 50px #0003;padding:16px;font-size:10px;line-height:1.6;box-sizing:border-box}.b2b-rail nav{display:grid;gap:4px;margin-top:18px;flex:1;min-height:0;align-content:start;overflow-y:auto;overflow-x:hidden;padding-right:3px;scrollbar-width:thin;scrollbar-color:#444449 transparent}.b2b-rail nav a,.bottom>a,.bottom>button{height:42px;padding:0 12px;box-sizing:border-box;display:flex;align-items:center;gap:12px;border:0;border-radius:7px;color:#aeb0b5;background:transparent;text-decoration:none;font:12px var(--sb-font);cursor:pointer}.b2b-rail nav a:hover,.b2b-rail nav a.active,.bottom>a:hover,.bottom>button:hover{background:#2b2b2f;color:#fff}.b2b-rail nav a.active svg{color:var(--sb-coral)}.bottom{margin-top:auto;display:grid;gap:3px;flex-shrink:0}.bottom>button{width:100%}.person{height:auto!important;margin-top:9px;padding:13px 8px 3px!important;border-top:1px solid #303033!important;border-radius:0!important;display:flex;gap:9px;align-items:center;text-align:left}.person i{width:30px;height:30px;border-radius:50%;background:var(--sb-coral);display:grid;place-items:center;font-style:normal;font-size:11px;overflow:hidden}.person i img{width:100%;height:100%;object-fit:cover}.person span{display:grid;gap:3px;min-width:0}.person b{font-size:10px;font-weight:500}.person small{font-size:8px;color:#898c92;overflow:hidden;text-overflow:ellipsis}@media(max-width:800px){.b2b-rail{width:72px;padding:14px 9px}.brand{height:32px;padding:4px}.brand img,.company span,.company>svg:last-child,.b2b-rail nav a span,.bottom span{display:none}.company{width:52px;justify-content:center}.b2b-rail nav a,.bottom>a,.bottom>button{justify-content:center}.person{justify-content:center;padding:12px 0 0}}
</style>
