<script setup lang="ts">
import { ChevronDown, PackageSearch, Repeat2, Search } from '@lucide/vue';
const props=defineProps<{orders:any[];busy:boolean;canOrder:boolean;canSeeFinance:boolean;formatPrice:(value:any)=>string;statusLabels:Record<string,string>;fulfillment:(item:any)=>string}>();
const emit=defineEmits<{repeat:[item:any];context:[event:MouseEvent,item:any]}>();
const query=ref(''),status=ref(''),sort=ref('newest'),expanded=ref('');
const statuses=computed(()=>[...new Set(props.orders.map(o=>o.status))]);
const filtered=computed(()=>props.orders.filter(o=>(!status.value||o.status===status.value)&&`${o.orderNumber} ${o.items.map((i:any)=>i.productName).join(' ')}`.toLocaleLowerCase('ru').includes(query.value.trim().toLocaleLowerCase('ru'))).sort((a,b)=>(Date.parse(b.createdAt)-Date.parse(a.createdAt))*(sort.value==='newest'?1:-1)));
</script>
<template>
 <section class="salon-services-panel business-orders-panel"><div class="salon-services-filters"><label class="salon-services-search"><Search :size="18"/><input v-model="query" type="search" placeholder="Номер заказа или товар" aria-label="Поиск закупочных заказов"/></label><select v-model="status" aria-label="Статус закупочного заказа"><option value="">Все статусы</option><option v-for="value in statuses" :key="value" :value="value">{{statusLabels[value]||value}}</option></select><select v-model="sort" aria-label="Сортировка закупочных заказов"><option value="newest">Сначала новые</option><option value="oldest">Сначала старые</option></select></div>
  <table v-if="filtered.length" class="salon-services-table business-orders-table"><thead><tr><th>Заказ</th><th>Статус</th><th>Склад и передача</th><th v-if="canSeeFinance">Сумма</th><th><span class="salon-services-sr-only">Действия</span></th></tr></thead><tbody><template v-for="item in filtered" :key="item.id"><tr class="salon-service-row business-order-row" @contextmenu.prevent="emit('context',$event,item)"><th scope="row" class="salon-service-info"><button type="button" class="b2b-edit-link" :aria-expanded="expanded===item.id" :aria-label="`Состав заказа ${item.orderNumber}`" @click="expanded=expanded===item.id?'':item.id">{{item.orderNumber}} <ChevronDown :size="14"/></button><small>{{new Date(item.createdAt).toLocaleDateString('ru-RU')}} · {{item.items.length}} позиций</small></th><td data-label="Статус"><span class="salon-service-status" :class="{'is-active':item.status==='DELIVERED'}">{{statusLabels[item.status]||item.status}}</span></td><td data-label="Склад и передача"><span :class="{'sync-error':item.oneCSyncError}">{{fulfillment(item)}}</span><small v-if="item.trackingNumber">Трек: {{item.trackingNumber}}</small></td><td v-if="canSeeFinance" data-label="Сумма" class="salon-client-spent"><strong>{{formatPrice(item.finalAmount)}}</strong></td><td class="business-order-actions"><button type="button" :disabled="busy||!canOrder" :aria-label="`Повторить заказ ${item.orderNumber}`" @click="emit('repeat',item)"><Repeat2 :size="16"/>Повторить</button></td></tr><tr v-if="expanded===item.id" class="business-order-details"><td :colspan="canSeeFinance?5:4"><div><h3>Состав заказа</h3><div v-for="(line,i) in item.items" :key="line.id||i" class="business-order-line"><span><strong>{{line.productName}}</strong><small>{{line.variantName||line.externalSku}}</small></span><span>{{line.quantity}} шт.</span><strong v-if="canSeeFinance">{{formatPrice(line.total)}}</strong></div><p v-if="item.comments">{{item.comments}}</p><small>Повтор заказа использует актуальные цены и остатки. Передача в 1С зависит от настроенного подключения.</small></div></td></tr></template></tbody></table>
  <div v-else class="salon-services-empty"><PackageSearch :size="24"/><h3>{{orders.length?'Заказы не найдены':'Заказов пока нет'}}</h3><p>{{orders.length?'Измените поиск или статус.':'Начните с подбора товаров в оптовом каталоге.'}}</p><NuxtLink v-if="!orders.length" to="/b2b?section=catalog">Открыть каталог</NuxtLink></div><footer v-if="orders.length" class="salon-services-total"><small>Найдено заказов: {{filtered.length}} из {{orders.length}}</small></footer>
 </section>
</template>
