<script setup lang="ts">
import { Minus, Plus, Search, ShoppingBag, Sparkles, Trash2 } from '@lucide/vue';
import { resolveProductImageUrl } from '~/shared/product-images';
const props=defineProps<{products:any[];cart:Record<string,number>;canOrder:boolean;busy:boolean;formatPrice:(value:any)=>string}>();
const emit=defineEmits<{quantity:[id:string,value:number];checkout:[]}>();
const config=useRuntimeConfig(),query=ref(''),category=ref(''),stock=ref('all'),sort=ref('name'),failed=ref<Record<string,boolean>>({});
const categories=computed(()=>{const values=new Map<string,string>();for(const p of props.products)for(const c of p.categories||[])values.set(c.category.id,c.category.nameRu||c.category.name);return [...values.entries()].sort((a,b)=>a[1].localeCompare(b[1],'ru'));});
const price=(p:any)=>Math.min(...p.variants.map((v:any)=>Number(v.b2bPrice)));
const filtered=computed(()=>props.products.filter(p=>(!query.value.trim()||`${p.nameRu} ${p.sku} ${p.variants.map((v:any)=>v.sku).join(' ')}`.toLocaleLowerCase('ru').includes(query.value.trim().toLocaleLowerCase('ru')))&&(!category.value||p.categories?.some((c:any)=>c.category.id===category.value))&&(stock.value==='all'||p.variants.some((v:any)=>v.available>0))).sort((a,b)=>sort.value==='price'?price(a)-price(b):a.nameRu.localeCompare(b.nameRu,'ru')));
const lines=computed(()=>props.products.flatMap(p=>p.variants.filter((v:any)=>props.cart[v.id]>0).map((v:any)=>({product:p,variant:v,quantity:props.cart[v.id]}))));
const total=computed(()=>lines.value.reduce((sum,l)=>sum+l.quantity*l.variant.b2bPrice,0));
const image=(p:any)=>failed.value[p.id]?'':resolveProductImageUrl(p.images?.[0]?.url,config.public.apiBase,String(config.public.siteUrl||''));
function set(v:any,value:any){const amount=Number(value);emit('quantity',v.id,Math.min(Math.max(0,Math.floor(Number.isFinite(amount)?amount:0)),Math.max(0,v.available)));}
</script>
<template>
 <div class="business-catalog"><section class="business-catalog-products"><div class="salon-services-panel"><div class="salon-services-filters business-catalog-filters"><label class="salon-services-search"><Search :size="18"/><input v-model="query" type="search" placeholder="Название или артикул" aria-label="Поиск оптовых товаров"/></label><select v-model="category" aria-label="Категория оптовых товаров"><option value="">Все категории</option><option v-for="[id,label] in categories" :key="id" :value="id">{{label}}</option></select><select v-model="stock" aria-label="Наличие оптовых товаров"><option value="all">Любой остаток</option><option value="available">В наличии</option></select><select v-model="sort" aria-label="Сортировка оптовых товаров"><option value="name">По названию</option><option value="price">Сначала дешевле</option></select></div></div>
  <div class="business-product-grid"><article v-for="p in filtered" :key="p.id" class="business-product"><div class="business-product-image"><img v-if="image(p)" :src="image(p)" :alt="p.nameRu" @error="failed[p.id]=true"/><Sparkles v-else :size="24"/></div><div class="business-product-heading"><small>{{p.sku}}</small><h3>{{p.nameRu}}</h3></div><div v-for="v in p.variants" :key="v.id" class="business-product-variant"><div><small v-if="p.variants.length>1">{{v.name||v.sku}}</small><div class="business-product-prices"><strong>{{formatPrice(v.b2bPrice)}}</strong><s v-if="Number(v.retailPrice)>Number(v.b2bPrice)">{{formatPrice(v.retailPrice)}}</s></div><small>{{v.available>0?`В наличии: ${v.available} шт.`:'Нет в наличии'}}</small></div><div class="business-quantity"><button type="button" :disabled="busy||!canOrder||!cart[v.id]" :aria-label="`Уменьшить количество ${v.sku}`" @click="set(v,(cart[v.id]||0)-1)"><Minus :size="14"/></button><input type="number" min="0" :max="v.available" :value="cart[v.id]||0" :disabled="busy||!canOrder" :aria-label="`Количество ${v.sku}`" @change="set(v,($event.target as HTMLInputElement).value)"/><button type="button" :disabled="busy||!canOrder||(cart[v.id]||0)>=v.available" :aria-label="`Добавить ${v.sku}`" @click="set(v,(cart[v.id]||0)+1)"><Plus :size="14"/></button></div></div></article></div>
  <div v-if="!filtered.length" class="salon-services-empty"><ShoppingBag :size="24"/><h3>{{products.length?'Товары не найдены':'Каталог пока пуст'}}</h3><p>Измените фильтры или обратитесь к менеджеру.</p></div><small class="business-catalog-count">Найдено товаров: {{filtered.length}}</small>
 </section><aside class="business-cart salon-settings-panel" aria-label="Корзина закупок"><header><h2>Ваш заказ</h2><small>{{lines.length?`${lines.length} позиций`:'Корзина пуста'}}</small></header><p v-if="!lines.length">Выберите количество рядом с нужным товаром.</p><div v-for="line in lines" :key="line.variant.id" class="business-cart-line"><div><strong>{{line.product.nameRu}}</strong><small>{{line.quantity}} × {{formatPrice(line.variant.b2bPrice)}}</small></div><strong>{{formatPrice(line.quantity*line.variant.b2bPrice)}}</strong><button type="button" :disabled="busy" :aria-label="`Убрать ${line.variant.sku} из корзины`" @click="emit('quantity',line.variant.id,0)"><Trash2 :size="16"/></button></div><footer><span>Итого <strong>{{formatPrice(total)}}</strong></span><button type="button" class="primary" :disabled="busy||!canOrder||!lines.length" @click="emit('checkout')"><ShoppingBag :size="16"/>Оформить заказ</button><small v-if="!canOrder">Заказывать может сотрудник с правом закупок.</small></footer></aside></div>
</template>
