<script setup lang="ts">
const props=defineProps<{profile:any;dashboard:any;orders:any[];formatPrice:(value:any)=>string;statusLabels:Record<string,string>;fulfillment:(item:any)=>string}>();
const active=computed(()=>props.orders.filter(o=>!['DELIVERED','CANCELLED','REFUNDED'].includes(o.status)));
const issues=computed(()=>props.orders.filter(o=>o.oneCSyncError));
const canSeeFinance=computed(()=>props.profile.membership?.canSeeFinance);
</script>
<template>
 <section class="business-purchases-overview"><SalonOrganizationCard :profile="profile" :format-price="formatPrice"/><div class="business-overview-metrics"><article><span>Заказы за месяц</span><strong>{{dashboard.purchaseOrdersMonth||0}}</strong></article><article v-if="canSeeFinance"><span>Сумма закупок за месяц</span><strong>{{formatPrice(dashboard.purchasesMonth)}}</strong></article><article><span>Заказы в работе</span><strong>{{active.length}}</strong></article><article><span>Ошибки передачи</span><strong>{{issues.length}}</strong></article></div><div class="business-purchases-columns"><section class="salon-settings-panel"><header class="salon-overview-heading"><h2>Последние заказы</h2><NuxtLink to="/b2b?section=orders">Все заказы →</NuxtLink></header><NuxtLink v-for="item in orders.slice(0,5)" :key="item.id" to="/b2b?section=orders" class="business-dashboard-order"><div><strong>{{item.orderNumber}}</strong><small>{{statusLabels[item.status]||item.status}} · {{fulfillment(item)}}</small></div><strong v-if="canSeeFinance">{{formatPrice(item.finalAmount)}}</strong></NuxtLink><div v-if="!orders.length" class="business-dashboard-empty"><strong>Начните первую закупку</strong><p>Подберите товары по персональным ценам. Заказы и статусы появятся здесь.</p><NuxtLink to="/b2b?section=catalog">Перейти в каталог</NuxtLink></div></section><section class="salon-settings-panel"><h2>Быстрые действия</h2><NuxtLink to="/b2b?section=catalog">Подобрать товары</NuxtLink><NuxtLink to="/b2b?section=orders">Проверить статусы заказов</NuxtLink><NuxtLink to="/b2b?section=support&area=purchases">Связаться с поддержкой</NuxtLink><NuxtLink to="/b2b?section=settings&area=purchases">Данные компании</NuxtLink><small>Финансовые условия и реквизиты договоров уточняются у вашего менеджера. Доступ к созданию заказа зависит от прав сотрудника.</small></section></div></section>
</template>
