<script setup lang="ts">
import { History, RefreshCw } from '@lucide/vue';
const props=defineProps<{kind:'tasks'|'leads';entityId:string;team?:any[];stages?:any[];revision?:number}>();
const {request,message}=useCrmDrive();const items=ref<any[]>([]),more=ref(false),loading=ref(false),error=ref('');let sequence=0;
const labels:Record<string,string>={title:'Название',description:'Описание',status:'Статус',priority:'Приоритет',progress:'Выполнение, %',assignedToId:'Ответственный',managerId:'Ответственный',parentId:'Родительская задача',leadId:'Сделка',startDate:'Начало',dueDate:'Срок',labels:'Метки',estimateMinutes:'Оценка, мин',contactName:'Контакт',contactPhone:'Телефон',contactEmail:'Почта',stageId:'Этап',amount:'Сумма',probability:'Вероятность, %',expectedCloseAt:'План закрытия',nextContactAt:'Следующий контакт',lostReason:'Причина проигрыша',tags:'Теги',file:'Файл',task:'Подзадача'};
const names:Record<string,string>={BACKLOG:'В очереди',TODO:'К выполнению',IN_PROGRESS:'В работе',REVIEW:'На проверке',OVERDUE:'Просрочена',DONE:'Выполнена',CANCELLED:'В архиве',LOW:'Низкий',MEDIUM:'Обычный',HIGH:'Высокий',CRITICAL:'Критический',NEW:'Новая',WON:'Успешно',LOST:'Проиграна',CONTACTED:'Первичный контакт',QUALIFIED:'Квалификация',NEGOTIATION:'Переговоры'};
const person=(u:any)=>[u?.firstName,u?.lastName].filter(Boolean).join(' ')||u?.email||'Система';
function value(field:string,v:any){if(v===null||v===undefined||v==='')return 'Не задано';if(['assignedToId','managerId'].includes(field))return person(props.team?.find(x=>x.id===v))==='Система'?'Сотрудник (не в текущей команде)':person(props.team?.find(x=>x.id===v));if(field==='stageId')return props.stages?.find(x=>x.id===v)?.name||'Этап вне текущей воронки';if(['parentId','leadId'].includes(field))return 'Связанная карточка';if(/Date$|At$/.test(field))return new Date(v).toLocaleString('ru-RU');if(Array.isArray(v))return v.join(', ')||'Не задано';return names[v]||String(v);}
async function load(append=false){const seq=++sequence;loading.value=true;error.value='';try{const result=await request<any>(`${props.kind}/${props.entityId}/history`,{query:{before:append?items.value.at(-1)?.id:undefined}});if(seq===sequence){items.value=append?[...items.value,...result.items]:result.items;more.value=result.more;}}catch(e){error.value=message(e);}finally{if(seq===sequence)loading.value=false;}}
watch(()=>[props.entityId,props.revision],()=>load(),{immediate:true});
</script>
<template><section class="crm-change-history"><header class="crm-work-header"><h3 class="crm-icon-heading"><History :size="18" aria-hidden="true" /><span>История изменений</span></h3><button class="crm-work-button crm-button crm-button--refresh" :disabled="loading" @click="load()"><RefreshCw :size="16" />Обновить</button></header><p class="crm-muted">События фиксируются с момента подключения истории. Старые изменения не восстанавливаются задним числом.</p><p v-if="error" role="alert" class="crm-work-error">{{error}}</p><p v-if="loading" role="status">Загружаем историю…</p><p v-if="!loading&&!items.length" class="crm-muted">Изменений пока нет.</p><article v-for="item in items" :key="item.id"><header><strong>{{person(item.actor)}}</strong><time>{{new Date(item.createdAt).toLocaleString('ru-RU')}}</time></header><p>{{item.action}}</p><dl><template v-for="(change,index) in item.payload?.changes||[]" :key="index"><dt>{{labels[change.field]||change.field}}</dt><dd><span class="crm-history-before">{{value(change.field,change.from)}}</span><span aria-hidden="true"> → </span><span>{{value(change.field,change.to)}}</span></dd></template></dl></article><button v-if="more" class="crm-work-button crm-button" :disabled="loading" @click="load(true)">Ранее</button></section></template>
