<script setup lang="ts">
import { Plus, ExternalLink } from '@lucide/vue';
const props=defineProps<{leadId:string;team:any[];managerId?:string}>(),emit=defineEmits(['busy']);const {user}=useWorkspaceSession(),{can}=useWorkspaceAccess(),{request,message}=useCrmDrive();
const rows=ref<any[]>([]),title=ref(''),assignee=ref(props.managerId||user.value?.id||''),busy=ref(false),error=ref('');
watch(busy,x=>emit('busy',x));
async function load(){try{const lead=await request<any>(`leads/${props.leadId}`);rows.value=(lead.tasks||[]).filter((t:any)=>t.status!=='CANCELLED');}catch(e){error.value=message(e);}}
async function create(){if(busy.value||!title.value.trim())return;busy.value=true;error.value='';try{await request('tasks',{method:'POST',body:{title:title.value.trim(),assignedToId:assignee.value,leadId:props.leadId}});title.value='';await load();}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function toggle(task:any){busy.value=true;error.value='';try{await request(`tasks/${task.id}`,{method:'PATCH',body:{status:task.status==='DONE'?'TODO':'DONE'}});await load();}catch(e){error.value=message(e);}finally{busy.value=false;}}
watch(()=>props.leadId,load,{immediate:true});
</script>
<template><section class="crm-lead-tasks"><h3>Подзадачи сделки · {{rows.filter(x=>x.status==='DONE').length}}/{{rows.length}}</h3><p class="crm-muted">Эти задачи также доступны в общем списке задач команды.</p><p v-if="error" role="alert" class="crm-work-error">{{error}}</p><div v-if="can('crm.write')" class="crm-subtask-create"><label>Название подзадачи<input class="crm-input" v-model="title" maxlength="200" @keydown.enter.prevent="create" /></label><label>Ответственный<select class="crm-input" v-model="assignee"><option v-for="p in team" :key="p.id" :value="p.id">{{[p.firstName,p.lastName].filter(Boolean).join(' ')||p.email}}</option></select></label><button class="crm-work-button crm-button" :disabled="busy||!title.trim()" @click="create"><Plus :size="16" />Добавить подзадачу</button></div><p v-if="!rows.length" class="crm-muted">Подзадач пока нет</p><article v-for="task in rows" :key="task.id" class="crm-lead-task"><input class="crm-check" type="checkbox" :checked="task.status==='DONE'" :disabled="busy||!can('crm.write')" :aria-label="`Выполнено: ${task.title}`" @change="toggle(task)" /><div><strong>{{task.title}}</strong><progress :value="task.progress||0" max="100" :aria-label="`Прогресс: ${task.progress||0}%`" /><small>{{task.progress||0}}%</small></div><NuxtLink class="crm-work-button crm-button crm-button--icon" :to="`/crm/tasks?task=${task.id}`" aria-label="Открыть задачу"><ExternalLink :size="18" /></NuxtLink></article></section></template>
