<script setup lang="ts">
import { AlarmClock, CheckCircle2, Clock3, Play, Plus, Save, Trash2, X } from '@lucide/vue';

defineProps<{ modelValue: boolean }>();
const emit = defineEmits(['update:modelValue', 'created']);
const config = useRuntimeConfig();
const { token } = useWorkspaceSession();
const templates = ref<any[]>([]), reminders = ref<any[]>([]), team = ref<any[]>([]);
const tab = ref('templates'), saving = ref(false), error = ref('');
const draft = reactive<any>({ name: '', title: '', description: '', priority: 'MEDIUM', labels: '', estimateMinutes: 60, dueInHours: 24, reminderBeforeMin: 60, defaultAssigneeId: '' });
const headers = computed(() => ({ Authorization: `Bearer ${token.value}` }));
const priorityLabels: any = { LOW: 'Низкий', MEDIUM: 'Обычный', HIGH: 'Высокий', CRITICAL: 'Критичный' };
function person(user: any) { return [user?.firstName, user?.lastName].filter(Boolean).join(' ') || user?.email || 'Не назначен'; }
async function load() { [templates.value, reminders.value, team.value] = await Promise.all([$fetch<any[]>('/crm/task-templates', { baseURL: config.public.apiBase, headers: headers.value }), $fetch<any[]>('/crm/reminders', { baseURL: config.public.apiBase, headers: headers.value }), $fetch<any[]>('/crm/team', { baseURL: config.public.apiBase, headers: headers.value })]); }
async function createTemplate() { saving.value = true; error.value = ''; try { await $fetch('/crm/task-templates', { baseURL: config.public.apiBase, method: 'POST', headers: headers.value, body: { ...draft, labels: String(draft.labels).split(',').map(item => item.trim()).filter(Boolean), estimateMinutes: Number(draft.estimateMinutes), dueInHours: Number(draft.dueInHours), reminderBeforeMin: Number(draft.reminderBeforeMin), defaultAssigneeId: draft.defaultAssigneeId || undefined } }); Object.assign(draft, { name: '', title: '', description: '', priority: 'MEDIUM', labels: '', estimateMinutes: 60, dueInHours: 24, reminderBeforeMin: 60, defaultAssigneeId: '' }); await load(); } catch (exception: any) { error.value = exception?.data?.message || 'Не удалось создать шаблон'; } finally { saving.value = false; } }
async function launch(template: any) { await $fetch(`/crm/task-templates/${template.id}/create-task`, { baseURL: config.public.apiBase, method: 'POST', headers: headers.value, body: {} }); emit('created'); emit('update:modelValue', false); }
async function archive(template: any) { await $fetch(`/crm/task-templates/${template.id}`, { baseURL: config.public.apiBase, method: 'DELETE', headers: headers.value }); await load(); }
async function dismiss(reminder: any) { await $fetch(`/crm/reminders/${reminder.id}/dismiss`, { baseURL: config.public.apiBase, method: 'POST', headers: headers.value }); await load(); }
onMounted(load);
</script>

<template><Teleport to="body"><div data-v-ui-bd6e1294cf28 v-if="modelValue" class="automation-backdrop admin-dialog-backdrop" @click.self="emit('update:modelValue',false)"><section data-v-ui-bd6e1294cf28 class="automation admin-dialog admin-dialog--drawer"><header data-v-ui-bd6e1294cf28><div data-v-ui-bd6e1294cf28><p data-v-ui-bd6e1294cf28>CRM / АВТОМАТИЗАЦИЯ</p><h2 data-v-ui-bd6e1294cf28>Шаблоны и напоминания</h2><span data-v-ui-bd6e1294cf28>Повторяемые сценарии работы команды</span></div><button data-v-ui-bd6e1294cf28 @click="emit('update:modelValue',false)"><X data-v-ui-bd6e1294cf28 :size="18"/></button></header><nav data-v-ui-bd6e1294cf28><button data-v-ui-bd6e1294cf28 :class="{active:tab==='templates'}" @click="tab='templates'">Шаблоны задач <em data-v-ui-bd6e1294cf28>{{templates.length}}</em></button><button data-v-ui-bd6e1294cf28 :class="{active:tab==='reminders'}" @click="tab='reminders'">Активные напоминания <em data-v-ui-bd6e1294cf28>{{reminders.length}}</em></button></nav>
  <main data-v-ui-bd6e1294cf28 v-if="tab==='templates'"><section data-v-ui-bd6e1294cf28 class="template-list"><article data-v-ui-bd6e1294cf28 v-for="item in templates"><i data-v-ui-bd6e1294cf28><Clock3 data-v-ui-bd6e1294cf28 :size="17"/></i><span data-v-ui-bd6e1294cf28><b data-v-ui-bd6e1294cf28>{{item.name}}</b><strong data-v-ui-bd6e1294cf28>{{item.title}}</strong><small data-v-ui-bd6e1294cf28>{{priorityLabels[item.priority]}} · срок через {{item.dueInHours||'—'}} ч · напомнить за {{item.reminderBeforeMin||0}} мин</small><em data-v-ui-bd6e1294cf28 v-if="item.defaultAssignee">{{person(item.defaultAssignee)}}</em></span><button data-v-ui-bd6e1294cf28 title="Создать задачу" @click="launch(item)"><Play data-v-ui-bd6e1294cf28 :size="14"/></button><button data-v-ui-bd6e1294cf28 class="delete" title="Архивировать шаблон" @click="archive(item)"><Trash2 data-v-ui-bd6e1294cf28 :size="14"/></button></article><p data-v-ui-bd6e1294cf28 v-if="!templates.length">Шаблонов пока нет</p></section>
    <form data-v-ui-bd6e1294cf28 @submit.prevent="createTemplate"><h3 data-v-ui-bd6e1294cf28><Plus data-v-ui-bd6e1294cf28 :size="16"/>Новый шаблон</h3><div data-v-ui-bd6e1294cf28 class="two"><label data-v-ui-bd6e1294cf28>Название шаблона<input data-v-ui-bd6e1294cf28 v-model="draft.name" required/></label><label data-v-ui-bd6e1294cf28>Название задачи<input data-v-ui-bd6e1294cf28 v-model="draft.title" required/></label></div><label data-v-ui-bd6e1294cf28>Описание<textarea data-v-ui-bd6e1294cf28 v-model="draft.description" rows="3"/></label><div data-v-ui-bd6e1294cf28 class="three"><label data-v-ui-bd6e1294cf28>Приоритет<select data-v-ui-bd6e1294cf28 v-model="draft.priority"><option data-v-ui-bd6e1294cf28 v-for="(label,key) in priorityLabels" :value="key">{{label}}</option></select></label><label data-v-ui-bd6e1294cf28>Срок через, часов<input data-v-ui-bd6e1294cf28 v-model.number="draft.dueInHours" type="number" min="1"/></label><label data-v-ui-bd6e1294cf28>Напомнить за, минут<input data-v-ui-bd6e1294cf28 v-model.number="draft.reminderBeforeMin" type="number" min="0"/></label></div><div data-v-ui-bd6e1294cf28 class="two"><label data-v-ui-bd6e1294cf28>Ответственный по умолчанию<select data-v-ui-bd6e1294cf28 v-model="draft.defaultAssigneeId"><option data-v-ui-bd6e1294cf28 value="">Создатель задачи</option><option data-v-ui-bd6e1294cf28 v-for="member in team" :value="member.id">{{person(member)}}</option></select></label><label data-v-ui-bd6e1294cf28>Метки через запятую<input data-v-ui-bd6e1294cf28 v-model="draft.labels" placeholder="звонок, документы"/></label></div><p data-v-ui-bd6e1294cf28 v-if="error" class="error">{{error}}</p><button data-v-ui-bd6e1294cf28 class="save" :disabled="saving"><Save data-v-ui-bd6e1294cf28 :size="14"/>{{saving?'Сохраняем…':'Сохранить шаблон'}}</button></form>
  </main><main data-v-ui-bd6e1294cf28 v-else class="reminders"><article data-v-ui-bd6e1294cf28 v-for="item in reminders"><i data-v-ui-bd6e1294cf28><AlarmClock data-v-ui-bd6e1294cf28 :size="18"/></i><span data-v-ui-bd6e1294cf28><b data-v-ui-bd6e1294cf28>{{item.task.title}}</b><small data-v-ui-bd6e1294cf28>Срок {{item.task.dueDate?new Date(item.task.dueDate).toLocaleString('ru-RU'):'не задан'}}</small></span><button data-v-ui-bd6e1294cf28 @click="dismiss(item)"><CheckCircle2 data-v-ui-bd6e1294cf28 :size="15"/>Выполнено</button></article><p data-v-ui-bd6e1294cf28 v-if="!reminders.length">Сейчас активных напоминаний нет</p></main>
</section></div></Teleport></template>


