<script setup lang="ts">
import { ClipboardList, Link2, RefreshCw, Search, Wifi, X } from '@lucide/vue';
const config = useRuntimeConfig(); const route = useRoute();
const props = defineProps<{ pageSection?: string }>();
const { token, user } = useWorkspaceSession(); const busy = ref(false); const notice = ref('');
const saving = ref(false); const error = ref('');
const { openContextMenu, copyText } = useContextMenu();
const orders = ref<any[]>([]); const integrations = ref<any[]>([]); const search = ref(''); const channel = ref(''); const statusFilter = ref(''); const selected = ref<any>(null);
const channels = [{ id: 'WILDBERRIES', name: 'Wildberries', color: '#cb11ab' }, { id: 'OZON', name: 'Ozon', color: '#005bff' }, { id: 'YANDEX_MARKET', name: 'Яндекс Маркет', color: '#ffcc00' }, { id: 'MEGAMARKET', name: 'Мегамаркет', color: '#e6332a' }];
const integrationDrafts = reactive<Record<string,any>>(Object.fromEntries(channels.map(item => [item.id, {channel:item.id,shopName:''}])));
const integrationBaselines = reactive<Record<string,string>>({});
const statuses = [{ id: 'NEW', label: 'Новые' }, { id: 'CONFIRMED', label: 'Подтверждены' }, { id: 'ASSEMBLING', label: 'Сборка' }, { id: 'SHIPPED', label: 'Отправлены' }, { id: 'DELIVERED', label: 'Доставлены' }, { id: 'CANCELLED', label: 'Отменены' }, { id: 'RETURNED', label: 'Возвраты' }];
const section = computed(() => props.pageSection || (String(route.query.section || 'dashboard') === 'settings' ? 'integrations' : String(route.query.section || 'dashboard')));
const pageTitle = computed(() => section.value === 'orders' ? 'Заказы маркетплейсов' : section.value === 'integrations' ? 'Подключения каналов' : 'Обзор маркетплейсов');
const pageDescription = computed(() => section.value === 'orders' ? 'Заказы площадок, покупатели и этапы обработки.' : section.value === 'integrations' ? 'Кабинеты маркетплейсов и состояние настроек подключения.' : 'Заказы и состояние каналов продаж.');
const loaded = ref(false);
let loadVersion = 0;
let loadController: AbortController | undefined;
watch(() => route.query.section, value => { if(!props.pageSection && value === 'settings') void navigateTo({path:'/crm-marketplaces',query:{...route.query,section:'integrations'}},{replace:true}); },{immediate:true});
const filteredOrders = computed(() => orders.value.filter((order) => (!channel.value || order.channel === channel.value) && (!statusFilter.value || order.status === statusFilter.value) && (!search.value || `${order.externalId} ${order.buyerName || ''} ${order.channel}`.toLowerCase().includes(search.value.toLowerCase()))));
const stats = computed(() => ({ total: orders.value.length, new: orders.value.filter(o => o.status === 'NEW').length, assembling: orders.value.filter(o => o.status === 'ASSEMBLING').length, revenue: orders.value.reduce((sum, o) => sum + Number(o.totalAmount || 0), 0) }));
function integration(id: string) { return integrationDrafts[id]; }
function configurationLabel(id:string) { const saved=integrations.value.find(item=>item.channel===id); return !saved ? 'Не настроен' : saved.isActive ? 'Включён · связь не подтверждена' : 'Выключен'; }
function syncDrafts() { for(const channel of channels){const draft=integration(channel.id); if(integrationBaselines[channel.id] !== undefined && JSON.stringify(draft) !== integrationBaselines[channel.id])continue; const saved=integrations.value.find(item=>item.channel===channel.id); Object.assign(draft,{channel:channel.id,shopName:saved?.shopName||''});integrationBaselines[channel.id]=JSON.stringify(draft);} }
const transitions:Record<string,string[]>={NEW:['CONFIRMED','CANCELLED'],CONFIRMED:['ASSEMBLING','CANCELLED'],ASSEMBLING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED','RETURNED'],DELIVERED:['RETURNED'],CANCELLED:[],RETURNED:[]};
function allowedStatuses(order:any){return statuses.filter(item=>item.id===order.status || (transitions[order.status]||[]).includes(item.id));}
function fail(e:any){error.value=Array.isArray(e?.data?.message)?e.data.message.join(', '):e?.data?.message||'Действие не выполнено. Повторите попытку.';}
function flash(message:string){notice.value=message;setTimeout(()=>notice.value='',3000);}
function labelStatus(value: string) { return statuses.find(s => s.id === value)?.label || value; }
function labelChannel(value: string) { return channels.find(c => c.id === value)?.name || value; }
async function load() {
  if (!token.value || saving.value) return;
  const version = ++loadVersion, identity = token.value;
  loadController?.abort(); const controller = new AbortController(); loadController = controller;
  busy.value = true; error.value = '';
  try {
    const options = { baseURL: config.public.apiBase, headers: { Authorization: `Bearer ${identity}` }, signal: controller.signal, timeout: 20000 };
    const [nextOrders, nextIntegrations] = await Promise.all([
      section.value === 'integrations' ? Promise.resolve(null) : $fetch<any[]>('/marketplaces/orders', options),
      section.value === 'orders' ? Promise.resolve(null) : $fetch<any[]>('/marketplaces/integrations', options),
    ]);
    if (version !== loadVersion || token.value !== identity) return;
    if (nextOrders) orders.value = nextOrders;
    if (nextIntegrations) { integrations.value = nextIntegrations; syncDrafts(); }
    if (selected.value) selected.value = orders.value.find(item => item.id === selected.value.id) || null;
    loaded.value = true;
  } catch (e: any) { if (version === loadVersion && token.value === identity && !controller.signal.aborted) fail(e); }
  finally { if (version === loadVersion) busy.value = false; }
}
const integrationDirty = computed(() => section.value === 'integrations' && channels.some(item => integrationBaselines[item.id] !== undefined && JSON.stringify(integration(item.id)) !== integrationBaselines[item.id]));
onBeforeRouteLeave(() => !saving.value && (!integrationDirty.value || window.confirm('Уйти без сохранения названия кабинета?')));
onUnmounted(() => { ++loadVersion; loadController?.abort(); });
async function updateStatus(order: any, value: string) {
  if(saving.value || busy.value || value===order.status)return;
  if(!(transitions[order.status]||[]).includes(value)){error.value='Этот переход недоступен. Обновите заказ и выберите допустимое действие.';return;}
  if(['CANCELLED','RETURNED'].includes(value) && !window.confirm(`Подтвердить действие «${labelStatus(value)}» для заказа ${order.externalId}?`))return;
  saving.value=true;error.value='';
  try{await $fetch(`/marketplaces/orders/${order.id}`,{baseURL:config.public.apiBase,method:'PATCH',headers:{Authorization:`Bearer ${token.value}`},body:{status:value}});order.status=value;flash('Статус заказа обновлён');}
  catch(e:any){fail(e);}finally{saving.value=false;}
}
async function changeStatus(event:Event,order:any){const input=event.target as HTMLSelectElement;await updateStatus(order,input.value);input.value=order.status;}
async function saveIntegration(item: any) {
  if(saving.value || busy.value)return;
  if(!item.shopName.trim()){error.value='Укажите название кабинета.';return;}
  saving.value=true;error.value='';
  try{const saved=await $fetch<any>('/marketplaces/integrations',{baseURL:config.public.apiBase,method:'POST',headers:{Authorization:`Bearer ${token.value}`},body:{channel:item.channel,shopName:item.shopName.trim()}});integrations.value=[...integrations.value.filter(record=>record.channel!==item.channel),saved];Object.assign(item,{channel:item.channel,shopName:saved.shopName||item.shopName.trim()});integrationBaselines[item.channel]=JSON.stringify(item);flash('Название кабинета сохранено. Ключи и режим подключения не изменены.');}
  catch(e:any){fail(e);}finally{saving.value=false;}
}
async function testIntegration(id: string) {
  if(saving.value || busy.value)return;
  if(!integrations.value.some(item=>item.channel===id)){error.value='Сначала сохраните название кабинета.';return;}
  saving.value=true;error.value='';
  try{const result=await $fetch<any>(`/marketplaces/integrations/${id}/test`,{baseURL:config.public.apiBase,method:'POST',headers:{Authorization:`Bearer ${token.value}`}});flash(`${result.message || 'Тестовый адаптер проверен'}. Реальная связь с площадкой этой проверкой не подтверждается.`);}
  catch(e:any){fail(e);}finally{saving.value=false;}
}
function orderMenu(event:MouseEvent,order:any){openContextMenu(event,order.externalId,[{label:'Открыть карточку',icon:'open',action:()=>selected.value=order},{label:'Копировать номер площадки',icon:'copy',action:()=>copyText(order.externalId,'Номер заказа скопирован')},{label:'Копировать номер OMS',icon:'copy',action:()=>copyText(order.orderNumber,'Номер OMS скопирован')},...(transitions[order.status]||[]).map((status,index)=>({label:`Статус: ${labelStatus(status)}`,icon:'status' as const,separator:index===0,disabled:saving.value||busy.value,action:()=>updateStatus(order,status)}))],labelChannel(order.channel));}
function integrationMenu(event:MouseEvent,item:any){openContextMenu(event,item.name,[{label:'Проверить тестовый адаптер',icon:'refresh',disabled:saving.value||busy.value,action:()=>testIntegration(item.id)},{label:'Сохранить название',icon:'edit',disabled:saving.value||busy.value,action:()=>saveIntegration(integration(item.id))},{label:'Копировать код канала',icon:'copy',separator:true,action:()=>copyText(item.id,'Код канала скопирован')}],configurationLabel(item.id));}
onMounted(load);
</script>
<template>
  <main data-v-ui-ef7d3601c6cf class="marketplace-page crm-standard">
      <header data-v-ui-ef7d3601c6cf class="mp-header crm-page-header"><div data-v-ui-ef7d3601c6cf><h1 data-v-ui-ef7d3601c6cf>{{ pageTitle }}</h1><p data-v-ui-ef7d3601c6cf class="subtitle">{{ pageDescription }}</p></div><div data-v-ui-ef7d3601c6cf class="header-actions"><button class="crm-button crm-button--refresh" data-v-ui-ef7d3601c6cf :disabled="busy || saving" @click="load"><RefreshCw data-v-ui-ef7d3601c6cf :size="16" :class="{spin: busy}" /> Обновить</button></div></header>
      <div data-v-ui-ef7d3601c6cf class="mp-body crm-page-content"><p data-v-ui-ef7d3601c6cf v-if="error" class="operation-error" role="alert">{{ error }}</p><WorkspaceLoading v-if="busy && !loaded" label="Загружаем канал продаж" />
        <section data-v-ui-ef7d3601c6cf v-if="loaded && section === 'dashboard'" class="dashboard-view"><div data-v-ui-ef7d3601c6cf class="kpi-grid"><article class="crm-surface" data-v-ui-ef7d3601c6cf><span data-v-ui-ef7d3601c6cf>Всего заказов</span><strong data-v-ui-ef7d3601c6cf>{{ stats.total }}</strong><small data-v-ui-ef7d3601c6cf>за всё время</small></article><article class="crm-surface" data-v-ui-ef7d3601c6cf><span data-v-ui-ef7d3601c6cf>Новые</span><strong data-v-ui-ef7d3601c6cf class="coral">{{ stats.new }}</strong><small data-v-ui-ef7d3601c6cf>требуют внимания</small></article><article class="crm-surface" data-v-ui-ef7d3601c6cf><span data-v-ui-ef7d3601c6cf>В сборке</span><strong data-v-ui-ef7d3601c6cf>{{ stats.assembling }}</strong><small data-v-ui-ef7d3601c6cf>на складе</small></article><article class="crm-surface" data-v-ui-ef7d3601c6cf><span data-v-ui-ef7d3601c6cf>Оборот заказов</span><strong data-v-ui-ef7d3601c6cf>{{ stats.revenue.toLocaleString('ru-RU') }} ₽</strong><small data-v-ui-ef7d3601c6cf>по загруженным заказам</small></article></div><div data-v-ui-ef7d3601c6cf class="dashboard-grid"><article data-v-ui-ef7d3601c6cf class="panel channel-overview crm-surface"><div data-v-ui-ef7d3601c6cf class="panel-head"><div data-v-ui-ef7d3601c6cf><p data-v-ui-ef7d3601c6cf class="eyebrow">ПОДКЛЮЧЕНИЯ</p><h2 data-v-ui-ef7d3601c6cf>Каналы продаж</h2></div><NuxtLink data-v-ui-ef7d3601c6cf to="/crm-marketplaces/integrations">Настроить</NuxtLink></div><div data-v-ui-ef7d3601c6cf v-for="item in channels" :key="item.id" class="channel-line"><i data-v-ui-ef7d3601c6cf :style="{background:item.color}"></i><strong data-v-ui-ef7d3601c6cf>{{ item.name }}</strong><span data-v-ui-ef7d3601c6cf>{{ configurationLabel(item.id) }}</span></div></article><article data-v-ui-ef7d3601c6cf class="panel attention crm-surface"><div data-v-ui-ef7d3601c6cf class="panel-head"><div data-v-ui-ef7d3601c6cf><p data-v-ui-ef7d3601c6cf class="eyebrow">ОПЕРАЦИОННАЯ ЛЕНТА</p><h2 data-v-ui-ef7d3601c6cf>Последние заказы</h2></div><NuxtLink data-v-ui-ef7d3601c6cf to="/crm-marketplaces/orders">Все заказы</NuxtLink></div><div data-v-ui-ef7d3601c6cf v-for="order in orders.slice(0,5)" :key="order.id" class="compact-order crm-data-row"><div data-v-ui-ef7d3601c6cf><strong data-v-ui-ef7d3601c6cf>{{ order.externalId }}</strong><small data-v-ui-ef7d3601c6cf>{{ labelChannel(order.channel) }} · {{ order.buyerName || 'Покупатель не указан' }}</small></div><span data-v-ui-ef7d3601c6cf class="crm-badge" :data-status="order.status" :class="`status status-${order.status.toLowerCase()}`">{{ labelStatus(order.status) }}</span></div><p data-v-ui-ef7d3601c6cf v-if="!orders.length" class="empty">Заказов пока нет</p></article></div></section>
        <section data-v-ui-ef7d3601c6cf v-else-if="loaded && section === 'orders'" class="panel orders-panel crm-surface"><div data-v-ui-ef7d3601c6cf class="filters crm-toolbar"><label data-v-ui-ef7d3601c6cf class="search crm-input-group"><Search data-v-ui-ef7d3601c6cf :size="16" /><input class="crm-input" data-v-ui-ef7d3601c6cf id="channel-order-query" v-model="search" aria-label="Поиск заказов маркетплейсов" placeholder="Поиск по номеру или покупателю" /></label><select class="crm-input" data-v-ui-ef7d3601c6cf v-model="channel" aria-label="Канал продаж"><option data-v-ui-ef7d3601c6cf value="">Все каналы</option><option data-v-ui-ef7d3601c6cf v-for="item in channels" :key="item.id" :value="item.id">{{ item.name }}</option></select><select class="crm-input" data-v-ui-ef7d3601c6cf v-model="statusFilter" aria-label="Статус заказа"><option data-v-ui-ef7d3601c6cf value="">Все статусы</option><option data-v-ui-ef7d3601c6cf v-for="item in statuses" :key="item.id" :value="item.id">{{ item.label }}</option></select><button data-v-ui-ef7d3601c6cf v-if="search || channel || statusFilter" class="clear crm-button" type="button" @click="search='';channel='';statusFilter=''"><X data-v-ui-ef7d3601c6cf :size="16" /> Сбросить</button></div><div data-v-ui-ef7d3601c6cf class="table-wrap"><div data-v-ui-ef7d3601c6cf class="order-row table-head crm-table-head"><span data-v-ui-ef7d3601c6cf>Заказ</span><span data-v-ui-ef7d3601c6cf>Канал</span><span data-v-ui-ef7d3601c6cf>Покупатель</span><span data-v-ui-ef7d3601c6cf>Сумма</span><span data-v-ui-ef7d3601c6cf>Статус</span><span data-v-ui-ef7d3601c6cf>Дата</span></div><div data-v-ui-ef7d3601c6cf v-for="order in filteredOrders" :key="order.id" class="order-row clickable crm-data-row crm-interactive crm-table-row" role="button" tabindex="0" @keydown.enter.self="selected=order" @keydown.space.self.prevent="selected=order" @click="selected=order" @contextmenu.prevent="orderMenu($event,order)"><div data-v-ui-ef7d3601c6cf><strong data-v-ui-ef7d3601c6cf>{{ order.externalId }}</strong><small data-v-ui-ef7d3601c6cf>{{ order.trackingNumber || 'Трек-номер не указан' }}</small></div><span data-v-ui-ef7d3601c6cf>{{ labelChannel(order.channel) }}</span><span data-v-ui-ef7d3601c6cf>{{ order.buyerName || 'Не указан' }}</span><strong data-v-ui-ef7d3601c6cf>{{ Number(order.totalAmount || 0).toLocaleString('ru-RU') }} ₽</strong><span data-v-ui-ef7d3601c6cf :class="`status status-${order.status.toLowerCase()}`">{{ labelStatus(order.status) }}</span><span data-v-ui-ef7d3601c6cf>{{ new Date(order.createdAt).toLocaleDateString('ru-RU') }}</span></div><p data-v-ui-ef7d3601c6cf v-if="!filteredOrders.length" class="empty">По выбранным фильтрам заказов не найдено</p></div></section>
        <section data-v-ui-ef7d3601c6cf v-else-if="loaded && section === 'integrations'" class="integrations-view"><div data-v-ui-ef7d3601c6cf class="section-intro"><div data-v-ui-ef7d3601c6cf><h2 data-v-ui-ef7d3601c6cf>Кабинеты маркетплейсов</h2><p data-v-ui-ef7d3601c6cf>Здесь сохраняется название кабинета. Проверка использует адаптер разработки, а не реальный API площадки.</p><NuxtLink data-v-ui-ef7d3601c6cf v-if="user?.role === 'ADMIN'" :to="route.path.startsWith('/crm/') ? '/crm/settings/integrations' : '/system-settings/integrations'">Ключи API и секретные настройки — в центре интеграций</NuxtLink><p data-v-ui-ef7d3601c6cf v-else class="muted">Для настройки ключей API обратитесь к администратору платформы.</p></div></div><div data-v-ui-ef7d3601c6cf class="integration-grid"><article data-v-ui-ef7d3601c6cf v-for="item in channels" :key="item.id" class="integration-card crm-surface crm-item-card" @contextmenu.prevent="integrationMenu($event,item)"><div data-v-ui-ef7d3601c6cf class="integration-top"><i data-v-ui-ef7d3601c6cf :style="{background:item.color}"></i><div data-v-ui-ef7d3601c6cf><h3 data-v-ui-ef7d3601c6cf>{{ item.name }}</h3><span data-v-ui-ef7d3601c6cf >{{ configurationLabel(item.id) }}</span></div></div><label data-v-ui-ef7d3601c6cf>Название кабинета<input class="crm-input" data-v-ui-ef7d3601c6cf v-model="integration(item.id).shopName" :disabled="saving || busy" :placeholder="`${item.name} магазин`" /></label><div data-v-ui-ef7d3601c6cf class="card-actions"><button data-v-ui-ef7d3601c6cf class="primary crm-button crm-button--primary" :disabled="saving || busy" @click="saveIntegration(integration(item.id))">Сохранить название</button><button class="crm-button" data-v-ui-ef7d3601c6cf :disabled="saving || busy" @click="testIntegration(item.id)"><Wifi data-v-ui-ef7d3601c6cf :size="15" /> Проверить тестовый адаптер</button></div></article></div></section>
      </div>
    <aside data-v-ui-ef7d3601c6cf v-if="selected" class="drawer-backdrop admin-dialog-backdrop" @click.self="!saving && (selected=null)"><div data-v-ui-ef7d3601c6cf class="drawer admin-dialog admin-dialog--drawer admin-dialog--simple" role="dialog" aria-modal="true" aria-label="Заказ маркетплейса"><button data-v-ui-ef7d3601c6cf type="button" class="close crm-button crm-button--icon" aria-label="Закрыть заказ маркетплейса" :disabled="saving" @click="selected=null"><X data-v-ui-ef7d3601c6cf :size="18" /></button><p data-v-ui-ef7d3601c6cf class="eyebrow">ЗАКАЗ МАРКЕТПЛЕЙСА</p><h2 data-v-ui-ef7d3601c6cf>{{ selected.externalId }}</h2><div data-v-ui-ef7d3601c6cf class="drawer-status">{{ labelStatus(selected.status) }}</div><p data-v-ui-ef7d3601c6cf v-if="error" class="operation-error" role="alert">{{ error }}</p><div data-v-ui-ef7d3601c6cf class="order-actions"><button class="crm-button" data-v-ui-ef7d3601c6cf v-for="status in transitions[selected.status] || []" :key="status" :disabled="saving || busy" @click="updateStatus(selected,status)">{{ labelStatus(status) }}</button></div><p data-v-ui-ef7d3601c6cf class="muted">Допустимость смены статуса проверяет сервер.</p><dl data-v-ui-ef7d3601c6cf><dt data-v-ui-ef7d3601c6cf>Номер в системе</dt><dd data-v-ui-ef7d3601c6cf>{{ selected.orderNumber }}</dd><dt data-v-ui-ef7d3601c6cf>Канал</dt><dd data-v-ui-ef7d3601c6cf>{{ labelChannel(selected.channel) }}</dd><dt data-v-ui-ef7d3601c6cf>Покупатель</dt><dd data-v-ui-ef7d3601c6cf>{{ selected.buyerName || 'Не указан' }}</dd><dt data-v-ui-ef7d3601c6cf>Сумма</dt><dd data-v-ui-ef7d3601c6cf>{{ Number(selected.totalAmount || 0).toLocaleString('ru-RU') }} ₽</dd><dt data-v-ui-ef7d3601c6cf>Создан</dt><dd data-v-ui-ef7d3601c6cf>{{ new Date(selected.createdAt).toLocaleString('ru-RU') }}</dd></dl></div></aside><div data-v-ui-ef7d3601c6cf v-if="notice" class="toast">{{ notice }}</div>
  </main>
</template>
