import { CrmContentService, contentTimezone, contentUrl } from './content.service';
import { CrmContentController } from './content.controller';
import { PERMISSIONS_KEY } from '../common/decorators/permissions.decorator';
describe('CRM content plan',()=>{
 let row:any,db:any,service:CrmContentService;
 beforeEach(()=>{row={id:'post',taskId:'task',ideaId:'idea',platform:'INSTAGRAM',format:'REELS',status:'REVIEW',script:'Сценарий',caption:'Текст',cta:'',brief:'',version:3,archivedAt:null,scheduledAt:new Date('2099-09-23'),approvedAt:null,task:{title:'Обзор',assignedToId:'author'}};
 db={$executeRaw:jest.fn(),user:{findFirst:jest.fn().mockResolvedValue({id:'author'})},task:{update:jest.fn(),count:jest.fn().mockResolvedValue(0)},crmTaskComment:{create:jest.fn()},crmTaskReminder:{deleteMany:jest.fn(),upsert:jest.fn()},crmPublication:{findUnique:jest.fn().mockImplementation(()=>({...row})),update:jest.fn().mockImplementation(({data}:any)=>{for(const [k,v]of Object.entries(data))row[k]=k==='version'?row.version+1:v;return {...row};})}};db.$transaction=(fn:any)=>fn(db);service=new CrmContentService(db);});
 it('checks timezone and safe external link protocols',()=>{expect(contentTimezone('Europe/Moscow')).toBe('Europe/Moscow');expect(()=>contentTimezone('No/Zone')).toThrow();expect(()=>contentUrl('javascript:alert(1)')).toThrow();expect(()=>contentUrl('https://user:pass@example.org')).toThrow();expect(contentUrl('https://example.org/post/1')).toBe('https://example.org/post/1');});
 it('rejects stale writes before any mutation',async()=>{await expect(service.update('post',{version:2,title:'Другой'} as any,'author')).rejects.toThrow('другим сотрудником');expect(db.task.update).not.toHaveBeenCalled();});
 it('requires approval before ready/published states',async()=>{await expect(service.update('post',{version:3,status:'SCHEDULED'} as any,'author')).rejects.toThrow('согласуйте');});
 it('requires publication date and URL',async()=>{row.approvedAt=new Date();row.scheduledAt=null;await expect(service.update('post',{version:3,status:'SCHEDULED'} as any,'author')).rejects.toThrow('дату');row.scheduledAt=new Date();await expect(service.update('post',{version:3,status:'PUBLISHED'} as any,'author')).rejects.toThrow('ссылку');});
 it('invalidates approval after script edits',async()=>{row.approvedAt=new Date();const result=await service.update('post',{version:3,script:'Новый сценарий'} as any,'author');expect(result.approvedAt).toBeNull();expect(result.version).toBe(4);});
 it('does not accept changed copy as already approved',async()=>{row.approvedAt=new Date();await expect(service.update('post',{version:3,caption:'Изменение',status:'SCHEDULED'} as any,'author')).rejects.toThrow('согласуйте');});
 it('approves only review and records actor plus history',async()=>{const result=await service.approve('post',3,'boss');expect(result.approvedById).toBe('boss');expect(result.approvedAt).toBeInstanceOf(Date);expect(db.crmTaskComment.create).toHaveBeenCalled();row.status='IDEA';await expect(service.approve('post',4,'boss')).rejects.toThrow('Согласование');});
 it('protects approval with its own permission',()=>{expect(Reflect.getMetadata(PERMISSIONS_KEY,CrmContentController.prototype.approve)).toEqual(['content_plan.approve']);expect(Reflect.getMetadata(PERMISSIONS_KEY,CrmContentController.prototype.update)).toEqual(['content_plan.write']);});
 it('archives recoverably, removes pending reminder and rejects editing archive',async()=>{await service.archive('post',3,false);expect(row.archivedAt).toBeInstanceOf(Date);expect(db.crmTaskReminder.deleteMany).toHaveBeenCalled();await expect(service.update('post',{version:4,title:'Изменение'} as any,'author')).rejects.toThrow('восстановите');});
 it('blocks fake completed production while subtasks remain',async()=>{row.approvedAt=new Date();db.task.count.mockResolvedValue(1);await expect(service.update('post',{version:3,status:'PUBLISHED',publishedUrl:'https://example.org/post'} as any,'author')).rejects.toThrow('подзадачи');});
});
