<script setup lang="ts">
import { ArrowRight, Building2, Eye, EyeOff } from '@lucide/vue';
const { login, hydrate, token }=useB2BSession(); const route=useRoute(); const email=ref(''); const password=ref(''); const show=ref(false); const loading=ref(false); const error=ref('');
onMounted(()=>{hydrate();if(token.value)navigateTo('/b2b')});
async function submit(){loading.value=true;error.value='';try{await login(email.value,password.value);navigateTo(String(route.query.redirect||'/b2b'))}catch(e:any){error.value=e?.data?.message||e?.message||'Не удалось войти'}finally{loading.value=false}}
</script>
<template><main class="login"><section class="story"><img src="/sarkisian-logo.png" alt="SARKISIAN"/><div><p>SARKISIAN ДЛЯ БИЗНЕСА</p><h1>Ваш салон.<br/>В одном окне.</h1><span>Клиенты, календарь записей, услуги, команда и закупки профессиональных материалов.</span></div><small>Единая экосистема B2B</small></section><section class="form-area"><form @submit.prevent="submit"><i><Building2 :size="22"/></i><p>КАБИНЕТ ПАРТНЁРА</p><h2>Вход для бизнеса</h2><span>Используйте учётную запись владельца или сотрудника организации.</span><label>Email<input v-model.trim="email" type="email" autocomplete="username" placeholder="name@company.ru" required/></label><label>Пароль<div><input v-model="password" :type="show?'text':'password'" autocomplete="current-password" placeholder="Введите пароль" required/><button type="button" @click="show=!show"><EyeOff v-if="show" :size="16"/><Eye v-else :size="16"/></button></div></label><b v-if="error">{{error}}</b><button class="submit" :disabled="loading">{{loading?'Проверяем данные…':'Войти в кабинет'}}<ArrowRight :size="17"/></button><small>Нет B2B-доступа? Обратитесь к персональному менеджеру Sarkisian.</small></form></section></main></template>
<style scoped>
.login{min-height:100vh;display:grid;grid-template-columns:42% 58%;font-family:var(--sb-font);background:#f4f5f6;color:#1e2023}.story{background:#191919;color:#fff;padding:48px 9%;display:flex;flex-direction:column;justify-content:space-between}.story>img{width:180px;filter:brightness(0) invert(1)}.story p,.form-area form>p{color:var(--sb-coral);font-size:9px;letter-spacing:.18em;font-weight:600}.story h1{font-size:48px;line-height:1.05;margin:17px 0 23px;letter-spacing:-.04em}.story span{display:block;max-width:410px;color:#b5b7bb;font-size:13px;line-height:1.8}.story>small{font-size:9px;color:#777a80;letter-spacing:.12em}.form-area{display:grid;place-items:center;padding:35px}.form-area form{width:min(440px,100%);background:#fff;border:1px solid var(--sb-line);padding:45px;box-sizing:border-box}.form-area form>i{width:44px;height:44px;background:#fff1ee;color:var(--sb-coral);display:grid;place-items:center;font-style:normal}.form-area h2{font-size:30px;margin:14px 0 10px}.form-area form>span{display:block;color:var(--sb-muted);font-size:11px;line-height:1.65;margin-bottom:27px}.form-area label{display:grid;gap:7px;margin:14px 0;font-size:9px;color:#676a70}.form-area input{height:48px;border:1px solid var(--sb-line);padding:0 13px;font:12px var(--sb-font);box-sizing:border-box;width:100%}.form-area label div{display:grid;grid-template-columns:1fr 44px}.form-area label div button{border:1px solid var(--sb-line);border-left:0;background:#fff}.form-area form>b{display:block;color:#b34c3d;background:#fff0ed;padding:10px;font-size:9px}.submit{height:48px;width:100%;border:0;background:#1d1e22;color:#fff;margin-top:9px;padding:0 15px;display:flex;justify-content:center;align-items:center;gap:10px;font:11px var(--sb-font)}.form-area form>small{display:block;text-align:center;color:var(--sb-muted);font-size:8px;line-height:1.5;margin-top:18px}@media(max-width:850px){.login{grid-template-columns:1fr}.story{display:none}.form-area{padding:20px}.form-area form{padding:30px}}
</style>
