<script setup lang="ts">
const config=useRuntimeConfig(),{accessToken,authHeaders,loadMe}=useStorefront(),{openAuth}=useStorefrontPanels();
const token=useCookie<string|null>('sb-partner-attribution');
const form=reactive({companyName:'',inn:'',kpp:'',legalAddress:''}),busy=ref(false),error=ref(''),created=ref<any>(null);
async function submit(){busy.value=true;error.value='';try{created.value=await $fetch('/b2b/profile',{baseURL:config.public.apiBase,headers:authHeaders.value,method:'POST',body:{...Object.fromEntries(Object.entries(form).filter(([,v])=>!!v.trim()).map(([k,v])=>[k,v.trim()])),...(/^[a-f0-9]{64}$/.test(token.value||'')?{partnerToken:token.value}:{})}});await loadMe();}catch(e:any){error.value=Array.isArray(e?.data?.message)?e.data.message.join(' · '):e?.data?.message||'Не удалось зарегистрировать организацию. Проверьте, не создана ли она ранее.';}finally{busy.value=false;}}
onMounted(loadMe);
useHead({title:'Регистрация бизнеса · SARKISIAN',meta:[{name:'robots',content:'noindex, nofollow'}]});
</script>
<template><SiteShell><section class="sa-ui sa-panel sp-landing"><h1>Зарегистрировать салон или бизнес</h1><p>Закупки SARKISIAN и рабочее пространство салона в одном кабинете. Организация будет проверена командой перед активацией.</p><p v-if="error" class="sa-feedback" role="alert">{{error}}</p><template v-if="created"><h2>Организация зарегистрирована</h2><p>{{created.name}} · ожидает проверки</p><NuxtLink to="/b2b-login" class="sa-button">Войти в кабинет бизнеса</NuxtLink></template><template v-else-if="!accessToken"><p>Сначала войдите или создайте личную учётную запись.</p><div class="sa-actions"><button class="sa-button" @click="openAuth('login')">Войти</button><button class="sa-button sa-secondary" @click="openAuth('register')">Создать аккаунт</button></div></template><form v-else class="sp-join" @submit.prevent="submit"><label>Название организации<input v-model="form.companyName" minlength="2" maxlength="160" required/></label><div class="sp-form-grid"><label>ИНН<input v-model="form.inn" inputmode="numeric" pattern="[0-9]{10}|[0-9]{12}" maxlength="12"/></label><label>КПП<input v-model="form.kpp" inputmode="numeric" pattern="[0-9]{9}" maxlength="9"/></label></div><label>Адрес<input v-model="form.legalAddress" maxlength="500"/></label><p class="sa-muted">Регистрация не подключает бонусную или реферальную программу к B2B-закупкам.</p><button class="sa-button" :disabled="busy" type="submit">Зарегистрировать организацию</button></form></section></SiteShell></template>
