<script setup lang="ts">
import { ChevronLeft, ChevronRight, SlidersHorizontal, X } from '@lucide/vue';
const route = useRoute(); const router = useRouter(); const config = useRuntimeConfig();
const search = ref(String(route.query.search || '')); const sort = ref(String(route.query.sort || 'new')); const page = ref(Math.max(1, Number(route.query.page || 1))); const mobileFilters = ref(false);
const query = computed(() => ({ search: search.value || undefined, page: page.value, limit: 24 }));
const { data, pending, error, refresh } = await useFetch<any>('/products', { baseURL: config.public.apiBase, query, watch: [query] });
const products = computed(() => { const items = [...(data.value?.items || [])]; if (sort.value === 'price-asc') return items.sort((a, b) => Number(a.basePrice) - Number(b.basePrice)); if (sort.value === 'price-desc') return items.sort((a, b) => Number(b.basePrice) - Number(a.basePrice)); if (sort.value === 'name') return items.sort((a, b) => a.nameRu.localeCompare(b.nameRu, 'ru')); return items; });
const pagination = computed(() => data.value?.pagination || { page: 1, pages: 1, total: 0 }); const title = computed(() => search.value ? `Поиск: ${search.value}` : 'Каталог');
function applyCategory(value: string) { search.value = value; page.value = 1; mobileFilters.value = false; } function clearSearch() { search.value = ''; page.value = 1; }
watch([search, sort, page], () => router.replace({ query: { ...(search.value ? { search: search.value } : {}), ...(sort.value !== 'new' ? { sort: sort.value } : {}), ...(page.value > 1 ? { page: page.value } : {}) } }));
watch(() => route.query.search, (value) => { search.value = String(value || ''); page.value = 1; });
useSeoMeta({ title: () => `${title.value} — SARKISIAN BRAND`, description: 'Каталог профессиональных материалов SARKISIAN BRAND для мастеров маникюра.' });
</script>
<template><SiteShell><div class="sb-catalog-page"><div class="sb-breadcrumbs"><NuxtLink to="/">Главная</NuxtLink><span>/</span><span>Каталог</span></div><div class="sb-catalog-title"><div><p>SARKISIAN BRAND</p><h1>{{ title }}</h1><span>{{ pagination.total }} товаров</span></div><button class="sb-filter-mobile" @click="mobileFilters = true"><SlidersHorizontal :size="17" /> Фильтры</button></div><div class="sb-catalog-layout"><aside class="sb-filters" :class="{ 'is-open': mobileFilters }"><div class="sb-filters__head"><b>Категории</b><button @click="mobileFilters = false"><X :size="19" /></button></div><button :class="{ active: !search }" @click="clearSearch">Все товары <span>{{ pagination.total }}</span></button><button v-for="category in storefrontCategories" :key="category.title" :class="{ active: search === category.query }" @click="applyCategory(category.query)">{{ category.title }} <ChevronRight :size="15" /></button><div class="sb-filter-info"><b>Нужна помощь?</b><span>Подскажем материал под вашу технику и задачу.</span><a href="mailto:info@sarkisianbrand.ru">Написать консультанту</a></div></aside><section class="sb-catalog-results"><div class="sb-catalog-toolbar"><div v-if="search" class="sb-active-filter">{{ search }} <button @click="clearSearch"><X :size="14" /></button></div><span v-else>Профессиональные материалы для уверенной работы</span><select v-model="sort" aria-label="Сортировка"><option value="new">Сначала новинки</option><option value="price-asc">Сначала дешевле</option><option value="price-desc">Сначала дороже</option><option value="name">По названию</option></select></div><div v-if="pending" class="sb-state">Загружаем товары…</div><div v-else-if="error" class="sb-state is-error">Не удалось загрузить каталог. <button @click="refresh()">Повторить</button></div><div v-else-if="products.length" class="sb-product-grid is-catalog"><ProductCard v-for="product in products" :key="product.id" :product="product" /></div><div v-else class="sb-empty"><h2>Ничего не нашли</h2><p>Попробуйте другой запрос или посмотрите весь каталог.</p><button class="sb-primary" @click="clearSearch">Показать все товары</button></div><div v-if="pagination.pages > 1" class="sb-pagination"><button :disabled="page <= 1" @click="page--"><ChevronLeft :size="17" /></button><span>{{ page }} из {{ pagination.pages }}</span><button :disabled="page >= pagination.pages" @click="page++"><ChevronRight :size="17" /></button></div></section></div></div></SiteShell></template>
