<script setup lang="ts">
import { ArrowLeft, RefreshCw } from '@lucide/vue';
const config=useRuntimeConfig();const {token}=useWorkspaceSession();const tasks=ref<any[]>([]);
const {openContextMenu,copyText}=useContextMenu();
const taskLabels:Record<string,string>={TODO:'К выполнению',IN_PROGRESS:'В работе',DONE:'Выполнена',OVERDUE:'Просрочена'};
async function load(){tasks.value=await $fetch<any[]>('/crm/tasks',{baseURL:config.public.apiBase,headers:{Authorization:`Bearer ${token.value}`}})}
function taskMenu(event:MouseEvent,task:any){openContextMenu(event,task.title,[{label:'Копировать название',icon:'copy',action:()=>copyText(task.title,'Название задачи скопировано')},...(task.assignedTo?.email?[{label:'Копировать email ответственного',icon:'copy' as const,action:()=>copyText(task.assignedTo.email,'Email скопирован')}]:[]),{label:'Обновить список',icon:'refresh',separator:true,action:load}],taskLabels[task.status]||task.status)}
onMounted(load);
</script>
<template><main class="simple-console"><section class="simple-panel"><header><div><NuxtLink to="/crm"><ArrowLeft :size="16"/> CRM</NuxtLink><p class="kicker">CRM / ЗАДАЧИ</p><h1>Задачи команды</h1></div><button @click="load"><RefreshCw :size="16"/> Обновить</button></header><div class="simple-table"><div class="simple-row head"><span>Задача</span><span>Статус</span><span>Ответственный</span><span>Срок</span></div><div v-for="task in tasks" :key="task.id" class="simple-row" @contextmenu.prevent="taskMenu($event,task)"><strong>{{ task.title }}</strong><span>{{ taskLabels[task.status]||task.status }}</span><span>{{ task.assignedTo?.email||'—' }}</span><span>{{ task.dueDate?new Date(task.dueDate).toLocaleDateString('ru-RU'):'—' }}</span></div></div></section></main></template>
<style scoped>.simple-console,.simple-panel{min-height:100vh;background:#f4f5f7;color:#202124;font-family:var(--sb-font)}.simple-login{min-height:100vh;display:grid;place-items:center}.simple-login form{width:430px;background:#fff;padding:40px;display:grid;gap:14px}.simple-login h1,.simple-panel h1{font-size:30px;margin:0}.simple-login input{height:44px;border:1px solid #e2e4e8;padding:0 12px}.simple-login button,.simple-panel button{height:44px;border:0;background:#1a1919;color:#fff;padding:0 16px}.simple-panel header{height:96px;background:#fff;border-bottom:1px solid #e2e4e8;padding:20px 5%;display:flex;justify-content:space-between;align-items:center}.simple-panel header a{display:flex;gap:7px;align-items:center;color:#80838b}.simple-panel h1{margin-top:8px}.simple-table{background:#fff;margin:30px 5%;padding:26px}.simple-row{display:grid;grid-template-columns:2fr 2fr 1fr 1fr;gap:15px;align-items:center;min-height:50px;border-bottom:1px solid #ececef;font-size:12px}.simple-row.head{color:#80838b;font-size:10px;text-transform:uppercase}.simple-login span{color:#d05d4d;font-size:12px}
</style>
