<script setup lang="ts">
import { ArrowRight, BriefcaseBusiness, Eye, EyeOff, LockKeyhole, UserPlus } from '@lucide/vue';
const config = useRuntimeConfig(); const route = useRoute(); const mode = ref<'login'|'register'>('login'); const showPassword = ref(false); const busy = ref(false); const error = ref(''); const socialNotice = ref('');
const form = reactive({ email: '', password: '', firstName: '', lastName: '', phone: '' }); const { user, login, register } = useStorefront();
if (route.query.social_error) socialNotice.value = String(route.query.social_error);
onMounted(() => { if (user.value) navigateTo('/account'); });
async function submit() { error.value = ''; busy.value = true; try { if (mode.value === 'login') await login(form.email, form.password); else await register(form); await navigateTo(String(route.query.return || '/account')); } catch (e: any) { error.value = Array.isArray(e?.data?.message) ? e.data.message.join('. ') : (e?.data?.message || 'Не удалось войти. Проверьте данные.'); } finally { busy.value = false; } }
async function social(provider: 'yandex'|'vk') { socialNotice.value = ''; try { const result = await $fetch<any>(`/auth/social/${provider}/start`, { baseURL: config.public.apiBase, query: { returnUrl: String(route.query.return || '/account') } }); if (result.authorizationUrl) window.location.href = result.authorizationUrl; } catch (e: any) { socialNotice.value = e?.data?.message || `Вход через ${provider === 'yandex' ? 'Яндекс' : 'VK'} будет доступен после подключения приложения в настройках экосистемы.`; } }
useSeoMeta({ title: 'Вход и регистрация — SARKISIAN BRAND' });
</script>
<template><SiteShell><div class="sb-auth-page"><section class="sb-auth-intro"><p>ЛИЧНЫЙ КАБИНЕТ</p><h1>Покупки становятся <em>удобнее</em></h1><ul><li>История и статусы заказов</li><li>Бонусный баланс и персональные предложения</li><li>Быстрое оформление с сохранёнными данными</li></ul><NuxtLink to="/b2b-login"><BriefcaseBusiness :size="18" /><span><b>Вы покупаете для салона?</b>Перейти во вход для B2B-клиентов</span><ArrowRight :size="18" /></NuxtLink></section><section class="sb-auth-card"><div class="sb-auth-tabs"><button :class="{ active: mode === 'login' }" @click="mode = 'login'">Вход</button><button :class="{ active: mode === 'register' }" @click="mode = 'register'">Регистрация</button></div><div><p class="sb-kicker">SARKISIAN CLUB</p><h2>{{ mode === 'login' ? 'С возвращением' : 'Создать аккаунт' }}</h2><span>{{ mode === 'login' ? 'Войдите, чтобы продолжить покупки.' : 'Получайте бонусы уже с первого заказа.' }}</span></div><form @submit.prevent="submit"><div v-if="mode === 'register'" class="sb-auth-row"><label>Имя<input v-model="form.firstName" autocomplete="given-name" required /></label><label>Фамилия<input v-model="form.lastName" autocomplete="family-name" /></label></div><label>Email<input v-model="form.email" type="email" autocomplete="email" required /></label><label v-if="mode === 'register'">Телефон<input v-model="form.phone" type="tel" autocomplete="tel" placeholder="+7 999 000-00-00" /></label><label>Пароль<div class="sb-password"><input v-model="form.password" :type="showPassword ? 'text' : 'password'" :autocomplete="mode === 'login' ? 'current-password' : 'new-password'" minlength="10" required /><button type="button" :aria-label="showPassword ? 'Скрыть пароль' : 'Показать пароль'" @click="showPassword = !showPassword"><EyeOff v-if="showPassword" :size="18" /><Eye v-else :size="18" /></button></div></label><p v-if="error" class="sb-form-error">{{ error }}</p><button class="sb-primary" :disabled="busy"><LockKeyhole v-if="mode === 'login'" :size="18" /><UserPlus v-else :size="18" />{{ busy ? 'Подождите…' : mode === 'login' ? 'Войти' : 'Зарегистрироваться' }}</button></form><div class="sb-social-divider"><span>или продолжить через</span></div><SiteSocialLoginButtons @select="social" /><p v-if="socialNotice" class="sb-social-notice">{{ socialNotice }}</p></section></div></SiteShell></template>
