<script setup lang="ts">
import { ArrowRight, Gauge, Headphones, ShieldCheck, ShoppingBag, Store, Users } from '@lucide/vue';
const { user } = useWorkspaceSession();
const spaces = [
  { label: 'Управление сайтом', description: 'Каталог, заказы интернет-магазина, контент, остатки и настройки.', to: '/admin-workspace?section=dashboard', icon: Store, roles: ['ADMIN','CONTENT_MANAGER','MANAGER_SALES','WAREHOUSE'], tone: '#f8604a' },
  { label: 'CRM и клиенты', description: 'Единая клиентская база, лиды, история коммуникаций и задачи команды.', to: '/crm', icon: Users, roles: ['ADMIN','MANAGER_B2B','MANAGER_SALES','SUPERVISOR'], tone: '#6f7fce' },
  { label: 'Маркетплейсы', description: 'Заказы каналов, подключения, синхронизация и операционный контроль.', to: '/crm-marketplaces?section=dashboard', icon: ShoppingBag, roles: ['ADMIN','MARKETPLACE_MANAGER','SUPERVISOR','WAREHOUSE'], tone: '#b652a0' },
  { label: 'Кабинет руководителя', description: 'Результаты компании, продажи, клиенты, риски и точки внимания.', to: '/leadership', icon: Gauge, roles: ['ADMIN','EXECUTIVE','SUPERVISOR'], tone: '#278b64' },
  { label: 'IT Helpdesk', description: 'Обращения сотрудников и клиентов, SLA, очереди и история решений.', to: '/helpdesk', icon: Headphones, roles: ['ADMIN','IT_SUPPORT','SUPERVISOR'], tone: '#d18b33' },
  { label: 'Настройки экосистемы', description: 'Сотрудники, роли, индивидуальные права, активные сессии, аудит и технические журналы.', to: '/system-settings', icon: ShieldCheck, roles: ['ADMIN'], tone: '#4e6678' },
];
const visible = computed(() => spaces.filter(space => !user.value || space.roles.includes(user.value.role)));
const roleLabels: Record<string,string> = { ADMIN:'Администратор платформы',CONTENT_MANAGER:'Контент-менеджер',MANAGER_B2B:'Менеджер B2B',MANAGER_SALES:'Менеджер продаж',MARKETPLACE_MANAGER:'Менеджер маркетплейсов',SUPERVISOR:'Руководитель направления',EXECUTIVE:'Руководитель компании',IT_SUPPORT:'IT-поддержка',CURATOR:'Куратор',WAREHOUSE:'Сотрудник склада' };
</script>

<template><main class="hub"><header><div><p class="eyebrow">SARKISIAN WORKSPACE</p><h1>Добрый день, {{ user?.firstName || 'коллега' }}</h1><span>{{ roleLabels[user?.role || ''] || user?.role }} · доступно разделов: {{ visible.length }}</span></div><div class="system-state"><i></i><span><b>Системы работают</b><small>Последняя проверка только что</small></span></div></header><section class="hub-body"><div class="intro"><div><p class="eyebrow">РАБОЧИЕ ПРОСТРАНСТВА</p><h2>Куда переходим?</h2></div><p>Все разделы работают с общей базой данных. Переключайтесь между задачами без повторного входа.</p></div><div class="space-grid"><NuxtLink v-for="space in visible" :key="space.to" :to="space.to" class="space-card"><div class="space-icon" :style="{color:space.tone,background:`${space.tone}12`}"><component :is="space.icon" :size="23" /></div><div><h3>{{ space.label }}</h3><p>{{ space.description }}</p></div><ArrowRight :size="18" /></NuxtLink></div><aside class="platform-note"><span>ЕДИНОЕ ЯДРО</span><p>Клиент, заказ и обращение сохраняют один идентификатор во всей экосистеме — от магазина до отчёта руководителя.</p></aside></section></main></template>

<style scoped>
.hub{min-height:100vh;background:var(--sb-bg);color:#202124;font-family:var(--sb-font)}.hub>header{height:126px;padding:25px 5%;box-sizing:border-box;background:#fff;border-bottom:1px solid var(--sb-line);display:flex;justify-content:space-between;align-items:center}.eyebrow{margin:0 0 9px;color:var(--sb-coral);font-size:9px;font-weight:600;letter-spacing:.17em}.hub h1{margin:0 0 8px;font-size:29px;letter-spacing:-.03em}.hub header>div>span{font-size:10px;color:var(--sb-muted)}.system-state{display:flex;align-items:center;gap:10px;padding:12px 15px;border:1px solid var(--sb-line);background:#fff}.system-state>i{width:8px;height:8px;border-radius:50%;background:#2c9566;box-shadow:0 0 0 4px #e8f6ef}.system-state span{display:grid;gap:3px}.system-state b{font-size:10px}.system-state small{font-size:8px;color:var(--sb-muted)}.hub-body{max-width:1180px;margin:auto;padding:42px 5% 80px}.intro{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.intro h2{font-size:25px;margin:0}.intro>p{max-width:430px;color:var(--sb-muted);font-size:11px;line-height:1.7;margin:0}.space-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.space-card{min-height:132px;padding:24px;background:#fff;border:1px solid var(--sb-line);display:grid;grid-template-columns:48px 1fr auto;gap:16px;align-items:start;color:#202124;text-decoration:none;box-sizing:border-box;transition:.18s}.space-card:hover{transform:translateY(-2px);box-shadow:0 14px 35px #2021240d;border-color:#cdd0d5}.space-icon{width:46px;height:46px;display:grid;place-items:center}.space-card h3{font-size:16px;margin:2px 0 9px}.space-card p{max-width:390px;color:var(--sb-muted);font-size:10px;line-height:1.7;margin:0}.space-card>svg{color:#a1a4aa;margin-top:14px}.platform-note{margin-top:16px;background:#1d1e22;color:#fff;padding:23px 26px;display:flex;align-items:center;gap:28px}.platform-note span{color:#f58b7b;font-size:9px;font-weight:600;letter-spacing:.15em;white-space:nowrap}.platform-note p{margin:0;color:#bfc1c6;font-size:11px;line-height:1.6}@media(max-width:850px){.space-grid{grid-template-columns:1fr}.intro{display:block}.intro>p{margin-top:13px}.system-state{display:none}}@media(max-width:550px){.hub>header{height:auto;padding:24px 20px}.hub-body{padding:30px 20px}.space-card{grid-template-columns:42px 1fr}.space-card>svg{display:none}.platform-note{display:block}.platform-note p{margin-top:10px}}
</style>
