<script setup lang="ts">
import { Archive, CalendarDays, Check, ChevronLeft, ChevronRight, Clapperboard, Copy, ExternalLink, Kanban, List, MessageSquare, Plus, RefreshCw, Search, X } from '@lucide/vue';
import { contentPlatforms as platforms, contentFormats as formats, contentStages as stages, contentLocal, contentInstant } from '~/shared/content-plan';
useHead({title:'Контент-план — SARKISIAN CRM'});
const config=useRuntimeConfig(),route=useRoute(),{token,user}=useWorkspaceSession(),{can}=useWorkspaceAccess();
const writable=computed(()=>can('content_plan.write'));
const request=<T=any>(path='',options:any={})=>$fetch<T>(`/crm/content-plan${path}`,{baseURL:config.public.apiBase,...options,headers:{Authorization:`Bearer ${token.value}`},retry:0});
const items=ref<any[]>([]),team=ref<any[]>([]),total=ref(0),loading=ref(false),busy=ref(false),error=ref(''),notice=ref('');
const view=ref('list'),search=ref(''),platform=ref(''),status=ref(''),assignee=ref(''),archived=ref(false),period=ref('month'),date=ref(new Date().toISOString().slice(0,10)),zone=ref('Europe/Moscow');
const opened=ref(false),selected=ref<any>(null),baseline=ref(''),formError=ref(''),comments=ref<any[]>([]),comment=ref(''),commentsMore=ref(false),attachmentBusy=ref(false);
const blank=()=>({title:'',platform:'INSTAGRAM',format:'REELS',assignedToId:user.value?.id||'',campaign:'',brief:'',script:'',caption:'',cta:'',scheduledAt:'',timezone:zone.value,status:'IDEA',publishedUrl:''});
const draft=reactive(blank());const dirty=computed(()=>opened.value&&(JSON.stringify(draft)!==baseline.value||!!comment.value.trim()));
function discard(){return !busy.value&&!attachmentBusy.value&&(!dirty.value||window.confirm('Закрыть без сохранения изменений и комментария?'));}
function close(){if(discard()){opened.value=false;formError.value='';}}
const {panel,keyboard}=useCatalogDialog(computed(()=>opened.value),close);
onBeforeRouteLeave(()=>discard());
function beforeUnload(e:BeforeUnloadEvent){if(dirty.value||busy.value||attachmentBusy.value){e.preventDefault();e.returnValue='';}}
const person=(p:any)=>[p?.firstName,p?.lastName].filter(Boolean).join(' ')||p?.email||'Не назначен';
const message=(e:any)=>Array.isArray(e?.data?.message)?e.data.message.join(', '):e?.data?.message||e?.message||'Не удалось выполнить действие';
const dayKey=(row:any)=>contentLocal(row.scheduledAt,zone.value).slice(0,10);
const today=computed(()=>contentLocal(new Date().toISOString(),zone.value).slice(0,10));
const bounds=computed(()=>{const start=new Date(date.value+'T12:00:00Z');if(period.value==='month')start.setUTCDate(1);else start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);const end=new Date(start);if(period.value==='month')end.setUTCMonth(end.getUTCMonth()+1);else end.setUTCDate(end.getUTCDate()+7);return {from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)};});
const days=computed(()=>{const result:string[]=[];const d=new Date(bounds.value.from+'T12:00:00Z');while(d.toISOString().slice(0,10)<bounds.value.to){result.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1);}return result;});
const heading=computed(()=>new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date.value+'T12:00:00Z')));
const planned=computed(()=>items.value.filter(x=>x.scheduledAt)),unscheduled=computed(()=>items.value.filter(x=>!x.scheduledAt));
const late=(row:any)=>row.status!=='PUBLISHED'&&row.scheduledAt&&new Date(row.scheduledAt).getTime()<Date.now();
let sequence=0,timer:ReturnType<typeof setTimeout>|undefined;
async function load(more=false){const seq=++sequence;loading.value=true;error.value='';try{const result=await request<any>('',{query:{from:contentInstant(bounds.value.from+'T00:00',zone.value),to:contentInstant(bounds.value.to+'T00:00',zone.value),search:search.value||undefined,platform:platform.value||undefined,status:status.value||undefined,assignedToId:assignee.value||undefined,archived:String(archived.value),offset:more?items.value.length:0}});if(seq!==sequence)return;items.value=more?[...items.value,...result.items]:result.items;total.value=result.total;}catch(e){if(seq===sequence)error.value=message(e);}finally{if(seq===sequence)loading.value=false;}}
watch([platform,status,assignee,archived,date,period,zone],()=>load());watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(),300);});
function shift(direction:number){const d=new Date(date.value+'T12:00:00Z');if(period.value==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+direction);}else d.setUTCDate(d.getUTCDate()+7*direction);date.value=d.toISOString().slice(0,10);}
function setForm(row:any){Object.assign(draft,blank(),row?{title:row.task.title,platform:row.platform,format:row.format,assignedToId:row.task.assignedToId,campaign:row.campaign,brief:row.brief,script:row.script,caption:row.caption,cta:row.cta,scheduledAt:contentLocal(row.scheduledAt,row.timezone),timezone:row.timezone,status:row.status,publishedUrl:row.publishedUrl}:{});baseline.value=JSON.stringify(draft);}
async function open(row:any=null,day=''){if(!discard())return;selected.value=row;setForm(row);if(day){draft.scheduledAt=day+'T12:00';baseline.value=JSON.stringify(draft);}formError.value='';comment.value='';comments.value=[];opened.value=true;if(row)await loadComments();}
async function loadComments(more=false){const id=selected.value?.id;if(!id)return;try{const result=await request<any[]>(`/${id}/comments`,{query:{before:more?comments.value.at(-1)?.id:undefined}});if(selected.value?.id!==id)return;comments.value=more?[...comments.value,...result]:result;commentsMore.value=result.length===30;}catch(e){formError.value=message(e);}}
function payload(){return {title:draft.title.trim(),platform:draft.platform,format:draft.format,assignedToId:draft.assignedToId||undefined,campaign:draft.campaign,brief:draft.brief,script:draft.script,caption:draft.caption,cta:draft.cta,scheduledAt:contentInstant(draft.scheduledAt,draft.timezone),timezone:draft.timezone};}
async function save(){if(busy.value||attachmentBusy.value||!writable.value)return;busy.value=true;formError.value='';try{const body:any=payload();if(!body.title)throw new Error('Введите тему публикации');if(selected.value?.id){body.version=selected.value.version;body.status=draft.status;body.publishedUrl=draft.publishedUrl;}
 if(selected.value?.sourceId)body.sourceId=selected.value.sourceId;
 const row=await request<any>(selected.value?.id?`/${selected.value.id}`:'',{method:selected.value?.id?'PATCH':'POST',body});selected.value=row;setForm(row);notice.value='Публикация сохранена';await load();await loadComments();}catch(e){formError.value=message(e);}finally{busy.value=false;}}
async function action(kind:'approve'|'archive'|'restore'){if(busy.value||attachmentBusy.value||!selected.value?.id)return;if(dirty.value){formError.value='Сначала сохраните изменения';return;}if(kind==='archive'&&!window.confirm('Переместить публикацию в архив? Материалы и задача сохранятся.'))return;
 busy.value=true;formError.value='';try{const row=await request<any>(`/${selected.value.id}/${kind}`,{method:'POST',body:{version:selected.value.version}});selected.value=row;setForm(row);if(kind!=='approve')opened.value=false;await load();await loadComments();}catch(e){formError.value=message(e);}finally{busy.value=false;}}
function variant(){if(!discard()||!selected.value?.id)return;const source=selected.value;selected.value={sourceId:source.id};draft.status='IDEA';draft.scheduledAt='';draft.publishedUrl='';comment.value='';comments.value=[];baseline.value=JSON.stringify(draft);notice.value='Выберите площадку и время для новой версии. Материалы будут прикреплены автоматически.';}
async function addComment(){if(busy.value||!comment.value.trim()||!selected.value?.id)return;busy.value=true;try{const row=await request<any>(`/${selected.value.id}/comments`,{method:'POST',body:{body:comment.value}});comments.value=[row,...comments.value];comment.value='';}catch(e){formError.value=message(e);}finally{busy.value=false;}}
async function move(id:string,next:string){const row=items.value.find(x=>x.id===id);if(!row||busy.value||!writable.value||archived.value)return;busy.value=true;error.value='';try{await request(`/${id}`,{method:'PATCH',body:{version:row.version,status:next}});await load();}catch(e){error.value=message(e);}finally{busy.value=false;}}
const drag=useCrmCardDrag((id,next)=>move(id,next));
async function moveDay(e:DragEvent,day:string){e.preventDefault();const id=e.dataTransfer?.getData('text/plain'),row=items.value.find(x=>x.id===id);if(!row||busy.value||!writable.value)return;busy.value=true;try{await request(`/${row.id}`,{method:'PATCH',body:{version:row.version,scheduledAt:contentInstant(day+'T'+(contentLocal(row.scheduledAt,zone.value).slice(11)||'12:00'),zone.value)}});await load();}catch(err){error.value=message(err);}finally{busy.value=false;}}
async function fresh(){if(!discard())return;try{const row=await request<any>(`/${selected.value.id}`);selected.value=row;setForm(row);formError.value='';await loadComments();}catch(e){formError.value=message(e);}}
async function attachmentsChanged(){const id=selected.value?.id;if(!id)return;try{const row=await request<any>(`/${id}`);if(selected.value?.id!==id)return;selected.value=row;if(row.status==='REVIEW'&&draft.status!=='REVIEW'){draft.status='REVIEW';notice.value='Материалы изменились. Публикацию нужно согласовать повторно.';}await load();}catch(e){formError.value=message(e);}}
onMounted(async()=>{window.addEventListener('beforeunload',beforeUnload);await load();try{team.value=await request<any[]>('/team');if(typeof route.query.id==='string')await open(await request('/'+route.query.id));}catch(e){error.value=message(e);}});
onBeforeUnmount(()=>{sequence++;clearTimeout(timer);window.removeEventListener('beforeunload',beforeUnload);});
</script>
<template>
 <main class="crm-work-page crm-content-page crm-standard">
  <header class="crm-work-header crm-page-header"><div><h1>Контент-план</h1><p class="crm-muted">От идеи до публикации: сценарии, материалы и работа SMM-команды</p></div><div class="crm-work-actions"><button class="crm-work-button crm-button crm-button--refresh" :disabled="loading" @click="load()"><RefreshCw :size="18" />Обновить</button><button v-if="writable" class="crm-primary-button crm-button crm-button--primary" @click="open()"><Plus :size="18" />Новая публикация</button></div></header>
  <p v-if="error" role="alert" class="crm-work-error">{{ error }}</p><p v-if="notice" role="status" class="crm-content-notice">{{ notice }}</p>
  <section class="crm-content-toolbar crm-surface" aria-label="Фильтры контент-плана">
   <label class="crm-content-search crm-input-group"><Search :size="18" /><input class="crm-input" v-model="search" type="search" placeholder="Найти публикацию" aria-label="Поиск публикаций" /></label>
   <select class="crm-input" v-model="platform" aria-label="Площадка"><option value="">Все площадки</option><option v-for="(name,key) in platforms" :key="key" :value="key">{{ name }}</option></select>
   <select class="crm-input" v-model="status" aria-label="Этап"><option value="">Все этапы</option><option v-for="(name,key) in stages" :key="key" :value="key">{{ name }}</option></select>
   <select class="crm-input" v-model="assignee" aria-label="Ответственный"><option value="">Вся команда</option><option v-for="p in team" :key="p.id" :value="p.id">{{ person(p) }}</option></select>
   <label class="crm-content-archive"><input class="crm-check" v-model="archived" type="checkbox" />Архив</label>
  </section>
  <div class="crm-content-controls"><div class="crm-work-actions"><button class="crm-icon-button crm-button crm-button--icon" aria-label="Предыдущий период" @click="shift(-1)"><ChevronLeft :size="20" /></button><strong>{{ heading }}</strong><button class="crm-icon-button crm-button crm-button--icon" aria-label="Следующий период" @click="shift(1)"><ChevronRight :size="20" /></button><button class="crm-work-button crm-button" @click="date=today">Сегодня</button><select class="crm-input" v-model="period" aria-label="Период"><option value="month">Месяц</option><option value="week">Неделя</option></select></div><div class="crm-content-views" aria-label="Вид контент-плана"><button class="crm-button" :aria-pressed="view==='list'" @click="view='list'"><List :size="18" />Список</button><button class="crm-button" :aria-pressed="view==='calendar'" @click="view='calendar'"><CalendarDays :size="18" />Календарь</button><button class="crm-button" :aria-pressed="view==='board'" @click="view='board'"><Kanban :size="18" />Этапы</button></div></div>
  <p class="crm-muted crm-content-period">{{ bounds.from }} — {{ days.at(-1) }} · Время: {{ zone }} · Найдено {{ total }}. Публикации без даты показаны отдельно.</p>
  <p v-if="loading" role="status">Загружаем контент-план…</p>
  <div v-if="!loading&&!items.length" class="crm-content-empty crm-surface"><Clapperboard :size="32" /><h2>{{ archived?'Архив пуст':'Здесь начинается следующая публикация' }}</h2><p>{{ search||platform||status||assignee?'По выбранным фильтрам публикаций нет. Измените условия поиска.':'Добавьте тему, выберите площадку и время. Сценарий и материалы можно подготовить позже.' }}</p><button v-if="writable&&!archived" class="crm-work-button crm-button" @click="open()"><Plus :size="16" />Добавить идею</button></div>
  <div v-else-if="view==='board'" class="crm-content-board crm-board"><section class="crm-board-column crm-surface" v-for="(name,key) in stages" :key="key" :data-crm-drop="key" @dragover.prevent @drop.prevent="move(drag.active.value || $event.dataTransfer?.getData('text/plain') || '', String(key)); drag.finish()"><header><h2>{{ name }}</h2><small>{{ items.filter(x=>x.status===key).length }}</small></header><article role="button" tabindex="0" @keydown.enter="open(row)" @keydown.space.prevent="open(row)" v-for="row in items.filter(x=>x.status===key)" :key="row.id" class="crm-publication crm-item-card" :draggable="writable&&!archived" :data-crm-card="row.id" @dragstart="drag.start($event,row.id)" @dragend="drag.finish" @touchstart="drag.touchStart($event,row.id)" @click="drag.allowClick()&&open(row)"><small>{{ platforms[row.platform] }} · {{ formats[row.format] }}</small><strong>{{ row.task.title }}</strong><time :class="{'crm-content-late':late(row)}">{{ row.scheduledAt?contentLocal(row.scheduledAt,zone).replace('T',' · '):'Без даты' }}</time><small>{{ person(row.task.assignedTo) }}</small></article></section></div>
  <div v-else-if="view==='calendar'" class="crm-content-calendar" :class="{'is-week':period==='week'}"><section v-for="day in days" :key="day" class="crm-content-day crm-item-card" :class="{'is-today':day===today}" @dragover.prevent @drop="moveDay($event,day)"><header><strong>{{ new Date(day+'T12:00:00Z').toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',timeZone:'UTC'}) }}</strong><button v-if="writable&&!archived" class="crm-icon-button crm-button crm-button--icon" :aria-label="`Добавить публикацию на ${day}`" @click="open(null,day)"><Plus :size="16" /></button></header><button v-for="row in planned.filter(x=>dayKey(x)===day)" :key="row.id" :draggable="writable&&!archived" class="crm-publication crm-button crm-card-action crm-item-card" @dragstart="$event.dataTransfer?.setData('text/plain',row.id)" @click="open(row)"><small>{{ contentLocal(row.scheduledAt,zone).slice(11) }} · {{ formats[row.format] }}</small><strong>{{ row.task.title }}</strong><small>{{ platforms[row.platform] }}</small><span class="crm-content-status crm-badge" :data-stage="row.status">{{ stages[row.status] }}</span></button><small v-if="!planned.some(x=>dayKey(x)===day)" class="crm-muted">Нет публикаций</small></section></div>
  <section v-else class="crm-content-list"><button v-for="row in planned" :key="row.id" class="crm-publication crm-button crm-card-action crm-item-card" @click="open(row)"><div><small>{{ platforms[row.platform] }} · {{ formats[row.format] }}</small><strong>{{ row.task.title }}</strong><small>{{ row.campaign || person(row.task.assignedTo) }}</small></div><time :class="{'crm-content-late':late(row)}">{{ contentLocal(row.scheduledAt,zone).replace('T',' · ') }}</time><span class="crm-content-status crm-badge" :data-stage="row.status">{{ stages[row.status] }}</span></button></section>
  <section v-if="unscheduled.length&&view!=='board'" class="crm-content-unscheduled"><h2>Идеи без даты · {{ unscheduled.length }}</h2><div class="crm-content-list"><button v-for="row in unscheduled" :key="row.id" class="crm-publication crm-button crm-card-action crm-item-card" @click="open(row)"><div><small>{{ platforms[row.platform] }} · {{ formats[row.format] }}</small><strong>{{ row.task.title }}</strong></div><span class="crm-content-status crm-badge" :data-stage="row.status">{{ stages[row.status] }}</span></button></div></section>
  <button v-if="items.length<total" :disabled="loading" class="crm-work-button crm-button" @click="load(true)">Показать ещё · {{ total-items.length }}</button>
  <p class="crm-muted crm-content-footnote">Это план работы команды. Автоматическая публикация в соцсети не подключена. После размещения добавьте ссылку и отметьте «Опубликовано».</p>
  <Teleport to="body"><div v-if="opened" class="crm-work-overlay" @click.self="close"><section ref="panel" class="admin-dialog crm-content-editor" tabindex="-1" role="dialog" aria-modal="true" aria-label="Карточка публикации" @keydown="keyboard">
   <header class="crm-work-header"><div><h2>{{ selected?.id?'Публикация':selected?.sourceId?'Версия для другой площадки':'Новая публикация' }}</h2><p class="crm-muted">{{ selected?.archivedAt?'В архиве':selected?.approvedAt?'Сценарий и текст согласованы':'Подготовка и согласование материала' }}</p></div><button class="crm-icon-button crm-button crm-button--icon" aria-label="Закрыть публикацию" @click="close"><X :size="20" /></button></header>
   <p v-if="formError" class="crm-work-error" role="alert">{{ formError }}<button v-if="selected?.id" class="crm-work-button crm-button" @click="fresh">Перезагрузить карточку</button></p>
   <form @submit.prevent="save"><fieldset :disabled="busy||!writable||!!selected?.archivedAt" class="crm-content-fields"><label class="wide">Тема публикации<input class="crm-input" v-model="draft.title" maxlength="200" required /></label><label>Площадка<select class="crm-input" v-model="draft.platform"><option v-for="(name,key) in platforms" :key="key" :value="key">{{ name }}</option></select></label><label>Формат<select class="crm-input" v-model="draft.format"><option v-for="(name,key) in formats" :key="key" :value="key">{{ name }}</option></select></label><label>Когда публикуем<input class="crm-input" v-model="draft.scheduledAt" type="datetime-local" /></label><label>Часовой пояс<input class="crm-input" v-model="draft.timezone" placeholder="Europe/Moscow" required /><small>Время выше относится к этому поясу</small></label><label>Ответственный<select class="crm-input" v-model="draft.assignedToId" required><option v-for="p in team" :key="p.id" :value="p.id">{{ person(p) }}</option></select></label><label>Кампания / рубрика<input class="crm-input" v-model="draft.campaign" maxlength="150" placeholder="Например, запуск новой коллекции" /></label>
    <label v-if="selected?.id">Этап<select class="crm-input" v-model="draft.status"><option v-for="(name,key) in stages" :key="key" :value="key">{{ name }}</option></select></label><label v-if="selected?.id">Ссылка на публикацию<input class="crm-input" v-model="draft.publishedUrl" type="url" maxlength="2048" placeholder="https://…" /></label>
    <label class="wide">Задача и идея<textarea class="crm-input" v-model="draft.brief" rows="3" maxlength="10000" placeholder="Для кого материал, что показываем и какой результат хотим получить" /></label><label class="wide">Сценарий<textarea class="crm-input" v-model="draft.script" rows="7" maxlength="30000" placeholder="Зацепка → сцены и реплики → демонстрация → финал. Можно указать таймкоды и что должно быть в кадре." /></label><label class="wide">Текст публикации<textarea class="crm-input" v-model="draft.caption" rows="4" maxlength="10000" /></label><label class="wide">Призыв к действию<input class="crm-input" v-model="draft.cta" maxlength="1000" placeholder="Что зритель должен сделать после просмотра" /></label></fieldset>
    <p v-if="selected?.approvedAt" class="crm-content-notice">При изменении сценария или текста потребуется повторное согласование. Перед правкой переведите материал на этап «Согласование».</p>
    <footer class="crm-work-actions"><button v-if="writable&&!selected?.archivedAt" type="submit" class="crm-primary-button crm-button crm-button--primary" :disabled="busy||attachmentBusy"><Check :size="18" />{{ busy?'Сохраняем…':'Сохранить' }}</button><button v-if="selected?.id&&can('content_plan.approve')&&draft.status==='REVIEW'&&!selected.approvedAt&&!selected.archivedAt" type="button" class="crm-work-button crm-button" :disabled="busy" @click="action('approve')">Согласовать</button><button type="button" class="crm-work-button crm-button" @click="close">Закрыть</button></footer>
   </form>
   <div v-if="selected?.id" class="crm-content-related"><div class="crm-work-actions"><NuxtLink v-if="can('crm.read')" class="crm-work-button crm-button" :to="`/crm/tasks?task=${selected.taskId}`"><ExternalLink :size="16" />Задача подготовки</NuxtLink><button v-if="writable&&!selected.archivedAt" class="crm-work-button crm-button" :disabled="busy" @click="variant"><Copy :size="16" />Версия для площадки</button><button v-if="writable" class="crm-work-button crm-button" :disabled="busy" @click="action(selected.archivedAt?'restore':'archive')"><Archive :size="16" />{{ selected.archivedAt?'Восстановить':'В архив' }}</button></div>
    <CrmTaskFiles :key="selected.id" :task-id="selected.taskId" :publication-id="selected.id" @busy="attachmentBusy=$event" @changed="attachmentsChanged" />
    <section class="crm-content-comments"><h3><MessageSquare :size="18" />Обсуждение и согласование</h3><div v-if="writable" class="crm-content-comment-form"><label>Комментарий<textarea class="crm-input" v-model="comment" maxlength="10000" rows="3" @keydown.ctrl.enter.prevent="addComment" /></label><button class="crm-work-button crm-button" :disabled="busy||!comment.trim()" @click="addComment">Отправить комментарий</button></div><article v-for="entry in comments" :key="entry.id"><header><strong>{{ person(entry.author) }}</strong><time>{{ new Date(entry.createdAt).toLocaleString('ru-RU',{timeZone:zone}) }}</time></header><p>{{ entry.body }}</p></article><button v-if="commentsMore" class="crm-work-button crm-button" @click="loadComments(true)">Предыдущие комментарии</button></section>
   </div>
  </section></div></Teleport>
 </main>
</template>
