<script setup lang="ts">
const emit = defineEmits<{ open: [order: any] }>();
const config = useRuntimeConfig(), session = useWorkspaceSession();
const data = ref<any>(null), page = ref(1), search = ref(''), busy = ref(false), error = ref('');let generation = 0;
const money = (value: any, currency: string) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency }).format(Number(value));
async function load() { const n = ++generation;busy.value = true;error.value = '';try { const value = await $fetch('/oms/receivables', { baseURL: config.public.apiBase, headers: { Authorization: `Bearer ${session.token.value}` }, query: { page: page.value, search: search.value }, retry: 0 });if (n === generation) data.value = value; } catch (e: any) { if (n === generation) { data.value = null; error.value = e?.data?.message || 'Не удалось загрузить задолженность'; } } finally { if (n === generation) busy.value = false; } }
onMounted(load);onBeforeUnmount(() => { ++generation; });watch(() => session.token.value, () => { data.value = null;void load(); });
</script>
<template><details class="crm-surface crm-register crm-stack"><summary>Расчёты B2B из 1С</summary><p>Долг, возвраты и разрешение отгрузки поступают из 1С. Отсутствие ответа не означает нулевую задолженность.</p><div class="crm-action-bar"><label class="crm-field">Номер заказа<input v-model="search" class="crm-input" maxlength="150" @keydown.enter.prevent="page = 1; load()" /></label><button type="button" class="crm-button" :disabled="busy" @click="page = 1; load()">Обновить расчёты</button></div><p v-if="error" role="alert">{{ error }}</p><div v-if="data" class="crm-record-list"><button v-for="row in data.items" :key="row.id" type="button" class="crm-item-card crm-record" @click="emit('open', row)"><strong>{{ row.orderNumber }}</strong><span>Долг: {{ row.snapshot ? money(row.snapshot.debt, row.currency) : 'Нет данных 1С' }}<small>{{ row.reason }}</small></span><span>К возврату: {{ row.snapshot ? money(row.snapshot.refundDue, row.currency) : '—' }}<small v-if="row.snapshot">На {{ new Date(row.snapshot.asOf).toLocaleString('ru-RU') }}</small></span></button><p v-if="!data.items.length">Заказов по этому номеру нет.</p><nav class="crm-pagination" aria-label="Страницы расчётов"><button type="button" class="crm-button" :disabled="busy || page === 1" @click="page--; load()">Назад</button><span>{{ page }} / {{ Math.max(1, Math.ceil(data.total / data.limit)) }}</span><button type="button" class="crm-button" :disabled="busy || page * data.limit >= data.total" @click="page++; load()">Далее</button></nav></div></details></template>
