/* All private/public partner API traffic is fixture-only. No real registration or money. */
const {test,expect}=require('@playwright/test');
const {isolatedContext}=require('../../scripts/admin-design-mock.cjs');
const {auditTypography}=require('../../scripts/workspace-typography-audit.cjs');
const settings={name:'Партнёры SARKISIAN',isEnabled:true,rewardPercent:5,attributionDays:30,holdDays:14,minimumOrderAmount:0,firstOrderOnly:false,minimumPayout:1000,signupRewardAmount:2500,signupRewardUnit:'RUB',signupHoldDays:7,termsText:'Условия участия: начисление после доставки, без самоприглашений.',termsVersion:'v1',autoSettlement:true};
const partner={id:'qa-partner',code:'B'+'a'.repeat(20),kind:'BLOGGER',displayName:'Анна Партнёр',status:'PENDING',channels:[{label:'Telegram',url:'https://example.invalid/channel'}],description:'Обзоры материалов для мастеров',rewardPercent:null,payoutVerified:false,user:{email:'qa@example.invalid'},_count:{clicks:12,attributions:3,registrations:1}};
const totals=[{unit:'RUB',status:'PENDING',_sum:{amount:1500}},{unit:'RUB',status:'APPROVED',_sum:{amount:4000}},{unit:'BONUS',status:'APPROVED',_sum:{amount:150}}];
const summary={participants:4,pending:1,uniqueVisitors:24,registrations:2,totals};
const rows={participants:[partner],registrations:[{organizationId:'qa-company',participant:{displayName:partner.displayName},organization:{name:'Студия красоты',inn:'7701234567',status:'ACTIVE'},amount:2500,unit:'RUB',verifiedAt:null}],rewards:[{id:'qa-reward',participant:{displayName:partner.displayName},registrationId:'qa-company',registration:{organization:{name:'Студия красоты'}},amount:2500,unit:'RUB',status:'PENDING',readyAt:'2026-10-01T00:00:00Z',createdAt:'2026-09-18T00:00:00Z'}],payouts:[{id:'qa-payout',participant:{id:partner.id,displayName:partner.displayName,payoutVerified:true},amount:1000,status:'APPROVED',createdAt:'2026-09-18T00:00:00Z'}]};
const routes=[['referral-settings','REFERRAL','settings'],['referral-participants','REFERRAL','participants'],['referral-rewards','REFERRAL','rewards'],...['overview','participants','registrations','rewards','payouts','settings'].map(section=>['bloggers-'+section,'BLOGGER',section])];

for(const width of [1440,390,320])test(`Blogger add modal and distinct navigation icons ${width}`,async({browser},info)=>{
 const registry={settings,summary,rows:[],total:0,page:1,pages:1},writes=[];
 const fixtures=new Map([['/auth/access',{permissions:['partners.read','partners.write','partners.payouts','loyalty.read','web_orders.read'],denied:[]}],['/partners/admin/BLOGGER/participants',registry]]);
 const f=await isolatedContext(browser,width,false,false,{fixtures,allowFixtureForms:true});
 try{
  await f.context.route('**/api/v1/partners/admin/bloggers/invite',async route=>{const req=route.request();const headers={'Access-Control-Allow-Origin':'http://127.0.0.1:3001','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'};if(req.method()==='OPTIONS')return route.fulfill({status:204,headers});expect(req.method()).toBe('POST');writes.push(req.postDataJSON());registry.rows=[{...partner,status:'INVITED',acceptedTermsAt:null}];registry.total=1;return route.fulfill({status:200,headers,json:{id:partner.id,status:'INVITED'}});});
  await f.page.goto('/admin-workspace/bloggers-participants');
  if(width===1440){const icons=[];for(const name of ['Бонусная программа','Реферальная программа','Блогеры','Маркетинг'])icons.push(await f.page.locator('.studio-rail').getByRole('button',{name,exact:true}).locator('svg').first().innerHTML());expect(new Set(icons).size).toBe(4);}
  await f.page.getByRole('button',{name:'Добавить блогера',exact:true}).click();const dialog=f.page.getByRole('dialog');await expect(dialog).toBeVisible();await auditTypography(f.page,'.admin-dialog');await expect(dialog.getByLabel('Email клиента',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Новый блогер',exact:true}).click();await expect(dialog.getByLabel('Email клиента',{exact:true})).toHaveCount(0);await expect(dialog.getByLabel('Страница для блогера',{exact:true})).toHaveValue(/\/account\?tab=bloggers$/);await expect(dialog.getByRole('button',{name:'Добавить блогера',exact:true})).toHaveCount(0);expect(writes).toEqual([]);
  expect(await dialog.evaluate(el=>el.getBoundingClientRect().width)).toBeLessThanOrEqual(width);await info.attach('invitation-new',{body:await f.page.screenshot({fullPage:true}),contentType:'image/png'});
  await dialog.getByRole('button',{name:'Клиент уже на сайте',exact:true}).click();await dialog.getByLabel('Email клиента',{exact:true}).fill('qa@example.invalid');await dialog.getByLabel('Публичное имя',{exact:true}).fill('Анна Партнёр');await dialog.getByRole('button',{name:'Добавить блогера',exact:true}).click();await expect(dialog).toBeHidden();await expect(f.page.getByText('Ждём согласия',{exact:true})).toBeVisible();expect(writes).toEqual([{email:'qa@example.invalid',displayName:'Анна Партнёр'}]);expect(f.traffic.prohibitedWrites).toEqual([]);expect(f.errors).toEqual([]);
 }finally{await f.context.close();}
});

for(const width of [1440,390,320])test(`Partner settings grouped layout, summary and validation ${width}`,async({browser},info)=>{
 const fixtures=new Map([['/auth/access',{permissions:['partners.read','partners.write'],denied:[]}],['/partners/admin/REFERRAL/settings',{settings:{...settings,kind:'REFERRAL',signupRewardAmount:0},summary,rows:[],total:0,page:1,pages:1}]]);
 const f=await isolatedContext(browser,width,false,false,{fixtures});try{await f.page.goto('/admin-workspace/referral-settings');await expect(f.page.getByRole('heading',{name:'Бонусы за покупки',exact:true})).toBeVisible();await f.page.getByLabel('Бонусами за покупку, %',{exact:true}).fill('10');await expect(f.page.locator('.partner-example')).toContainText('500 бонусов');await expect(f.page.locator('.partner-program-summary dd').first()).toHaveText('10%');await expect(f.page.locator('.partner-save-state')).toHaveText('Есть несохранённые изменения');await f.page.getByLabel('Название программы',{exact:true}).fill('');await f.page.getByRole('button',{name:'Сохранить',exact:true}).click();expect(f.traffic.prohibitedWrites).toEqual([]);expect(await f.page.getByLabel('Название программы',{exact:true}).evaluate(el=>el.validity.valid)).toBe(false);expect(await f.page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+2);await f.page.getByLabel('Название программы',{exact:true}).fill('Пригласите друзей');await f.page.getByRole('heading',{name:'Бонусы за покупки',exact:true}).click();await info.attach('settings',{body:await f.page.screenshot({fullPage:true}),contentType:'image/png'});if(width===1440)await f.page.screenshot({path:'.screenshots/partner-referral-settings.png',fullPage:true});expect(f.errors).toEqual([]);}finally{await f.context.close();}
});
for(const width of [1440,390])for(const [path,kind,section] of routes)test(`Partner admin ${path} ${width}`,async({browser},info)=>{
 const fixtures=new Map([['/auth/access',{permissions:['partners.read','partners.write','partners.payouts'],denied:[]}],[`/partners/admin/${kind}/${section}`,{settings:{...settings,kind,signupRewardAmount:kind==='REFERRAL'?0:2500},summary,rows:rows[section]||[],total:(rows[section]||[]).length,page:1,pages:1}]]);
 const f=await isolatedContext(browser,width,false,false,{fixtures,allowFixtureForms:true});
 try{await f.page.goto('/admin-workspace/'+path);await expect(f.page.locator('.partner-workspace')).toBeVisible();await expect(f.page.locator('.partner-panel').first()).toBeVisible();await auditTypography(f.page);expect(await f.page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+2);
  const heights=await f.page.locator('.partner-workspace button,.partner-workspace input:not([type=checkbox]),.partner-workspace select,.partner-search').evaluateAll(els=>els.filter(el=>el.getClientRects().length&&!(el.tagName==='INPUT'&&el.closest('.partner-search'))).map(el=>el.getBoundingClientRect().height));for(const height of heights)expect(height).toBeGreaterThanOrEqual(43);
  if(section==='settings'){await expect(f.page.getByRole('button',{name:'Сохранить',exact:true})).toBeDisabled();await f.page.getByLabel('Название программы',{exact:true}).fill('Новая программа');await expect(f.page.getByRole('button',{name:'Сохранить',exact:true})).toBeEnabled();await expect(f.page.getByRole('button',{name:'Обновить',exact:true})).toBeDisabled();if(kind==='BLOGGER')await expect(f.page.getByText('Привлечение салонов и бизнеса',{exact:true})).toBeVisible();}
  if(['participants','registrations','payouts'].includes(section)){await f.page.getByRole('button',{name:section==='participants'?'Изменить':section==='registrations'?'Проверить':'Решение',exact:true}).first().click();const dialog=f.page.getByRole('dialog');await expect(dialog).toBeVisible();await auditTypography(f.page,'.admin-dialog');if(section==='payouts'){await expect(dialog.getByText('Это подтверждение уже выполненного перевода, не команда отправить деньги.',{exact:true})).toBeVisible();await expect(dialog.getByLabel('Уникальный номер платёжного документа',{exact:true})).toBeVisible();}await f.page.keyboard.press('Escape');await expect(dialog).toBeHidden();}
  for(const key of ['unknownReads','externalRequests','prohibitedWrites','credentialLeaks'])expect(f.traffic[key]).toEqual([]);expect(f.errors).toEqual([]);await info.attach('screen',{body:await f.page.screenshot({fullPage:true}),contentType:'image/png'});
 }finally{await f.context.close();}
});
test('Sales manager can inspect partners but cannot see payout actions',async({browser})=>{
 const fixtures=new Map([['/auth/access',{permissions:['partners.read'],denied:[]}],['/partners/admin/BLOGGER/participants',{settings,summary,rows:rows.participants,total:1,page:1,pages:1}]]);
 const f=await isolatedContext(browser,1440,false,false,{actor:{role:'MANAGER_SALES'},fixtures});try{await f.page.goto('/admin-workspace/bloggers-participants');await expect(f.page.getByText(partner.displayName,{exact:true})).toBeVisible();await expect(f.page.getByRole('button',{name:'Изменить',exact:true})).toHaveCount(0);await expect(f.page.getByRole('button',{name:'Получатель',exact:true})).toHaveCount(0);await f.page.locator('.studio-rail').getByRole('button',{name:'Блогеры',exact:true}).click();await expect(f.page.locator('.studio-rail').getByRole('link',{name:'Выплаты',exact:true})).toHaveCount(0);expect(f.errors).toEqual([]);}finally{await f.context.close();}
});

for(const width of [1440,390])test(`Invited blogger opens deep link and personally accepts terms ${width}`,async({browser})=>{const f=await publicFixture(browser,width,true);try{await f.page.goto('http://127.0.0.1:3001/account?tab=bloggers');await expect(f.page.getByRole('heading',{name:'Кабинет блогера',exact:true})).toBeVisible();await expect(f.page.getByLabel('Публичное имя',{exact:true})).toHaveValue(partner.displayName);await expect(f.page.getByRole('button',{name:'Отправить заявку',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);await f.page.getByLabel('Принимаю условия программы',{exact:true}).check();await f.page.getByRole('button',{name:'Отправить заявку',exact:true}).click();await expect(f.page.getByText('На проверке',{exact:true})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0]).toMatchObject({endpoint:'/partners/join',body:{kind:'BLOGGER',acceptedTerms:true,termsVersion:'v1',displayName:partner.displayName}});await expect(f.page.getByRole('button',{name:'Копировать',exact:true})).toHaveCount(0);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);}finally{await f.context.close();}});

async function publicFixture(browser,width,invited=false){
 const context=await browser.newContext({viewport:{width,height:960},serviceWorkers:'block'}),writes=[],unexpected=[];
 await context.addCookies([{name:'sb-customer-token',value:'qa-customer-token',url:'http://127.0.0.1:3001'}]);
 const me={settings,participant:{...partner,status:invited?'INVITED':'ACTIVE',payoutVerified:true,rewardPercent:5},summary:{uniqueVisitors:24,visits:30,orders:3,registrations:1,availableCash:3000,totals},rewards:rows.rewards,payouts:[]};
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(!['127.0.0.1','localhost','[::1]'].includes(url.hostname))return route.abort('blockedbyclient');if(!url.pathname.startsWith('/api/v1/')){if(req.method()!=='GET')return route.abort('blockedbyclient');return route.continue();}const endpoint=url.pathname.replace('/api/v1','');const reply=(json,status=200)=>route.fulfill({status,json,headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:3001','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}});if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:3001','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}});
  if(req.method()==='POST'&&endpoint==='/storefront/cart/bind')return reply({items:[],total:0});if(req.method()==='POST'){const body=req.postDataJSON();writes.push({endpoint,body});if(endpoint.endsWith('/visit'))return reply({token:'c'.repeat(64),expiresAt:new Date(Date.now()+30*86400000).toISOString()});if(endpoint==='/partners/join'){me.participant.status='PENDING';return reply({id:partner.id,status:'PENDING'});}if(endpoint==='/partners/payouts'){me.payouts.push({id:'qa-pay',status:'REQUESTED',amount:body.amount,createdAt:new Date().toISOString()});return reply({id:'qa-pay',status:'REQUESTED'});}unexpected.push(req.method()+' '+endpoint);return reply({},405);}
  if(endpoint==='/auth/me'||endpoint==='/auth/profile')return reply({id:'qa-customer',role:'CUSTOMER_B2C',firstName:'Анна',email:'qa@example.invalid',isActive:true});
  if(endpoint==='/storefront/dashboard')return reply({summary:{orders:0,spent:0},orders:[],giftCards:[],addresses:[],loyalty:null});
  if(endpoint.startsWith('/partners/me/'))return reply({...me,participant:{...me.participant,kind:endpoint.endsWith('REFERRAL')?'REFERRAL':'BLOGGER'}});
  if(endpoint.startsWith('/partners/link/'))return reply({name:settings.name,displayName:partner.displayName,kind:'BLOGGER',attributionDays:30,businessRegistration:true});
  if(endpoint==='/products/storefront-content')return reply({settings:{announcementText:'SARKISIAN'},banners:[],categories:[],socialLinks:[],menuItems:[],pages:[]});
  if(endpoint==='/cart')return reply({items:[],total:0});if(endpoint==='/storefront/favorites')return reply([]);
  if(endpoint==='/products/categories')return reply([]);if(endpoint.startsWith('/products')||endpoint.startsWith('/seo')||endpoint==='/gift-cards/product')return reply({items:[],total:0});
  unexpected.push(req.method()+' '+endpoint);return reply({},404);
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));return {context,page,writes,unexpected,errors};
}
for(const width of [1440,390])test(`B2C referral and blogger account ${width}`,async({browser},info)=>{const f=await publicFixture(browser,width);try{await f.page.goto('http://127.0.0.1:3001/account');await f.page.getByRole('button',{name:'Пригласить друзей',exact:true}).click();await expect(f.page.getByRole('heading',{name:'Приглашайте друзей',exact:true})).toBeVisible();await expect(f.page.getByRole('heading',{name:'Денежные выплаты',exact:true})).toHaveCount(0);await f.page.getByRole('button',{name:'Блогерам',exact:true}).click();await expect(f.page.getByRole('heading',{name:'Кабинет блогера',exact:true})).toBeVisible();await f.page.getByLabel('Сумма выплаты, ₽',{exact:true}).fill('1000');await f.page.getByRole('button',{name:'Запросить выплату',exact:true}).click();await expect(f.page.getByRole('status').filter({hasText:'Заявка на выплату создана'})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0].endpoint).toBe('/partners/payouts');expect(f.writes[0].body.requestKey).toMatch(/^[a-f0-9-]{36}$/);expect(await f.page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+2);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);await info.attach('account',{body:await f.page.screenshot({fullPage:true}),contentType:'image/png'});}finally{await f.context.close();}});
for(const width of [1440,390])test(`Blogger link requires consent, business entry preserves attribution ${width}`,async({browser})=>{const f=await publicFixture(browser,width);try{await f.page.goto('http://127.0.0.1:3001/r/'+partner.code);await expect(f.page.getByRole('button',{name:'Перейти в магазин',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);expect((await f.context.cookies()).some(c=>c.name==='sb-partner-attribution')).toBe(false);await f.page.getByRole('checkbox').check();await f.page.getByRole('button',{name:'Зарегистрировать бизнес',exact:true}).click();await expect(f.page).toHaveURL(/business-registration/);expect(f.writes).toHaveLength(1);expect(f.writes[0].body.consent).toBe(true);const cookie=(await f.context.cookies()).find(c=>c.name==='sb-partner-attribution');expect(cookie).toBeTruthy();expect(cookie.expires-Date.now()/1000).toBeLessThanOrEqual(30*86400+2);await expect(f.page.getByLabel('Название организации',{exact:true})).toBeVisible();expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);}finally{await f.context.close();}});
