/* Isolated tests only: no database, bank, emails, login or external API. */
import 'reflect-metadata';
import { ConfigService } from '@nestjs/config';
import { validate } from 'class-validator';
import { plainToInstance } from 'class-transformer';
import { attachPartner, attachPartnerRegistration, partnerBusinessActivated, partnerHash, partnerOrderDelivered, partnerOrderPaid, rewardValue } from './partner-lifecycle';
import { cashAvailable, partnerKind, PartnersService } from './partners.service';
import { PartnerAdminController } from './partners.controller';
import { PartnerSettingsDto, PartnerTrackDto } from './partners.dto';
import { DEFAULT_LOYALTY_SETTINGS } from '../loyalty/loyalty-core.helpers';

const participant={id:'p',userId:'partner',kind:'BLOGGER',status:'ACTIVE',acceptedTermsAt:new Date(),code:'B'+'a'.repeat(20),rewardPercent:null,payoutVerified:true,bonusDebt:0,user:{id:'partner',role:'CUSTOMER_B2C',isActive:true,email:'partner@example.invalid',phone:'+79001234567'}};
const settings={kind:'BLOGGER',name:'Partners',isEnabled:true,rewardPercent:5,attributionDays:30,holdDays:14,minimumOrderAmount:0,firstOrderOnly:false,minimumPayout:1000,signupRewardAmount:2500,signupRewardUnit:'RUB',signupHoldDays:7,termsText:'Conditions',autoSettlement:true,updatedAt:new Date()};
const order={id:'o',source:'WEB',organizationId:null,currency:'RUB',buyerEmail:'buyer@example.invalid',buyerPhone:'+79002223344',finalAmount:1200,shippingCost:200,items:[{productType:'PHYSICAL'}],partnerCode:'Btest',paymentStatus:'SUCCEEDED',status:'DELIVERED',payments:[{status:'SUCCEEDED'}]};
const token='c'.repeat(64);
function fixture(){
 const reward:any={id:'reward',orderId:'o',registrationId:null,participantId:'p',amount:50,unit:'RUB',status:'PENDING',readyAt:new Date(Date.now()-1000),order:{...order},registration:null};
 const registration:any={organizationId:'org',participantId:'p',ownerId:'buyer',amount:2500,unit:'RUB',holdDays:7,verifiedAt:new Date(),verifiedBy:'admin',activatedAt:null,organization:{id:'org',status:'ACTIVE'}};
 const payout:any={id:'pay',participantId:'p',requestKey:'key',amount:1000,status:'REQUESTED',requestNote:'',paymentReference:null};
 const tx:any={
  $queryRaw:jest.fn().mockResolvedValue([{id:'locked'}]),
  user:{findUnique:jest.fn().mockResolvedValue({id:'buyer',role:'CUSTOMER_B2C',isActive:true,email:'buyer@example.invalid'})},
  partnerParticipant:{findUnique:jest.fn().mockResolvedValue(participant),findUniqueOrThrow:jest.fn().mockResolvedValue({...participant,user:{...participant.user}}),update:jest.fn().mockResolvedValue(participant)},
  partnerClick:{findUnique:jest.fn().mockResolvedValue({id:'click',expiresAt:new Date(Date.now()+86400000),participant:{...participant,user:{...participant.user}}})},
  partnerProgramSetting:{findUnique:jest.fn().mockResolvedValue({...settings}),upsert:jest.fn().mockResolvedValue(settings)},
  partnerAttribution:{create:jest.fn(),findUnique:jest.fn().mockResolvedValue({orderId:'o',participantId:'p',baseAmount:1000,rewardPercent:5,holdDays:14,firstOrderOnly:false,participant}),update:jest.fn()},
  partnerReward:{findUnique:jest.fn().mockResolvedValue(null),findUniqueOrThrow:jest.fn().mockResolvedValue(reward),findMany:jest.fn().mockResolvedValue([reward]),upsert:jest.fn(),updateMany:jest.fn(),update:jest.fn(),aggregate:jest.fn().mockResolvedValue({_sum:{amount:4000}})},
  partnerBusinessRegistration:{create:jest.fn(),findUnique:jest.fn().mockResolvedValue(registration),update:jest.fn()},
  organizationMember:{count:jest.fn().mockResolvedValue(0),findFirst:jest.fn().mockResolvedValue({user:{isActive:true}})},
  loyaltyProgramSetting:{findUnique:jest.fn().mockResolvedValue({isEnabled:true})},
  partnerEvent:{create:jest.fn()},
  order:{count:jest.fn().mockResolvedValue(0)},
  partnerPayout:{findUnique:jest.fn().mockImplementation(async({where}:any)=>where.id?payout:null),findUniqueOrThrow:jest.fn().mockResolvedValue(payout),aggregate:jest.fn().mockResolvedValue({_sum:{amount:1000}}),create:jest.fn().mockImplementation(async({data}:any)=>({id:'new',status:'REQUESTED',...data})),update:jest.fn()},
 };
 const prisma:any={...tx,$transaction:jest.fn(async(fn:any)=>fn(tx))};
 const service=new PartnersService(prisma,new ConfigService({ECOSYSTEM_AUTOMATION_ENABLED:'false'}));
 return {tx,prisma,service,reward,registration,payout};
}
describe('Partner money and validation',()=>{
 test('exact cash kopeks and integer bonus rounding',()=>{expect(rewardValue('1995','5','BLOGGER')).toBe(99.75);expect(rewardValue('1995','5','REFERRAL')).toBe(99);expect(rewardValue('0.19','5','BLOGGER')).toBe(0);expect(cashAvailable('2000.11','1000.12')).toBe(999.99);expect(cashAvailable(100,200)).toBe(-100);});
 test('unknown programs fail closed',()=>{expect(()=>partnerKind('B2B')).toThrow();});
 test('tracking requires actual consent and UUID',async()=>{expect((await validate(plainToInstance(PartnerTrackDto,{visitorId:'20000000-0000-4000-8000-000000000001',consent:'false'},{enableImplicitConversion:true}))).length).toBeGreaterThan(0);});
 test('settings booleans cannot implicitly convert false string',async()=>{expect((await validate(plainToInstance(PartnerSettingsDto,{...settings,isEnabled:'false'},{enableImplicitConversion:true}))).some(x=>x.property==='isEnabled')).toBe(true);});
 test('enable requires conditions; referral cannot include signup bounty',async()=>{const {service,tx}=fixture();await expect(service.updateSettings('BLOGGER',{...settings,termsText:''} as any)).rejects.toThrow();await expect(service.updateSettings('REFERRAL',settings as any)).rejects.toThrow();expect(tx.partnerProgramSetting.upsert).not.toHaveBeenCalled();});
});
describe('B2C attribution',()=>{
 test.each([{source:'B2B'},{source:'OZON'},{organizationId:'org'},{currency:'USD'},{items:[{productType:'GIFT_CARD'}]}])('excluded source/item: %j',async change=>{const {tx}=fixture();expect(await attachPartner(tx,{...order,...change},token)).toBeNull();expect(tx.partnerAttribution.create).not.toHaveBeenCalled();});
 test('opaque token lookup stores hash and snapshots cash merchandise only',async()=>{const {tx}=fixture();expect(await attachPartner(tx,order,token)).toBe(participant.code);expect(tx.partnerClick.findUnique.mock.calls[0][0].where.tokenHash).toBe(partnerHash(token));expect(tx.partnerAttribution.create.mock.calls[0][0].data).toMatchObject({baseAmount:1000,rewardPercent:5,holdDays:14});});
 test.each([{sub:'partner',role:'CUSTOMER_B2C'},{sub:'staff',role:'ADMIN'},{sub:'buyer',role:'CUSTOMER_B2B'}])('self/staff/B2B cannot attribute: %j',async actor=>{const {tx}=fixture();expect(await attachPartner(tx,order,token,actor)).toBeNull();});
 test('same normalized phone is a self referral',async()=>{const {tx}=fixture();expect(await attachPartner(tx,{...order,buyerPhone:'8 (900) 123-45-67'},token)).toBeNull();});
 test('disabled loyalty blocks referral attribution',async()=>{const {tx}=fixture();tx.partnerClick.findUnique.mockResolvedValue({expiresAt:new Date(Date.now()+DAY),participant:{...participant,kind:'REFERRAL'}});tx.loyaltyProgramSetting.findUnique.mockResolvedValue({isEnabled:false});expect(await attachPartner(tx,order,token)).toBeNull();});
 test('expired click cannot attribute',async()=>{const {tx}=fixture();tx.partnerClick.findUnique.mockResolvedValue({expiresAt:new Date(0)});expect(await attachPartner(tx,order,token)).toBeNull();});
 test('verified payment creates pending reward once; repeated callback returns early',async()=>{const {tx}=fixture();await partnerOrderPaid(tx,order);expect(tx.partnerReward.upsert).toHaveBeenCalledTimes(1);tx.partnerReward.findUnique.mockResolvedValue({id:'existing'});await partnerOrderPaid(tx,order);expect(tx.partnerReward.upsert).toHaveBeenCalledTimes(1);});
 test('first order qualification guarded by buyer lock',async()=>{const {tx}=fixture();tx.partnerAttribution.findUnique.mockResolvedValue({participant,firstOrderOnly:true});tx.order.count.mockResolvedValue(1);await partnerOrderPaid(tx,order);expect(tx.$queryRaw).toHaveBeenCalled();expect(tx.partnerAttribution.update).toHaveBeenCalled();expect(tx.partnerReward.upsert).not.toHaveBeenCalled();});
 test('delivery only initializes retention date once',async()=>{const {tx}=fixture();await partnerOrderDelivered(tx,order);expect(tx.partnerReward.updateMany.mock.calls[0][0].where).toMatchObject({status:'PENDING',readyAt:null});});
});
const DAY=86400000;

describe('Blogger invitations and explicit consent',()=>{
 test('invite creates an inactive profile, never accepts terms for the blogger',async()=>{const {service,tx}=fixture();tx.partnerParticipant.findUnique.mockResolvedValue(null);tx.partnerParticipant.create=jest.fn().mockImplementation(async({data}:any)=>({id:'invited',...data}));await expect(service.invite({email:'BUYER@example.invalid',displayName:'Анна'},'admin')).resolves.toEqual({id:'invited',status:'INVITED'});expect(tx.user.findUnique).toHaveBeenCalledWith(expect.objectContaining({where:{email:'buyer@example.invalid'}}));expect(tx.partnerParticipant.create.mock.calls[0][0].data).toMatchObject({status:'INVITED',acceptedTermsAt:null,termsSnapshot:'',kind:'BLOGGER'});expect(tx.partnerEvent.create.mock.calls[0][0].data).toMatchObject({actorId:'admin',type:'INVITED'});expect(tx.partnerReward.upsert).not.toHaveBeenCalled();});
 test('replaying invitation does not create a second profile',async()=>{const {service,tx}=fixture();tx.partnerParticipant.findUnique.mockResolvedValue({id:'invited',status:'INVITED'});await expect(service.invite({email:'buyer@example.invalid'},'admin')).resolves.toEqual({id:'invited',status:'INVITED'});expect(tx.partnerEvent.create).not.toHaveBeenCalled();});
 test('missing email suggests public application, without creating a user',async()=>{const {service,tx}=fixture();tx.user.findUnique.mockResolvedValue(null);await expect(service.invite({email:'new@example.invalid'},'admin')).rejects.toThrow('Скопируйте ссылку');expect(tx.partnerEvent.create).not.toHaveBeenCalled();});
 test('B2B clients cannot be invited',async()=>{const {service,tx}=fixture();tx.user.findUnique.mockResolvedValue({id:'business',role:'CUSTOMER_B2B',isActive:true});await expect(service.invite({email:'business@example.invalid'},'admin')).rejects.toThrow();expect(tx.partnerEvent.create).not.toHaveBeenCalled();});
 test('existing application cannot be overwritten by invitation',async()=>{const {service,tx}=fixture();await expect(service.invite({email:'buyer@example.invalid'},'admin')).rejects.toThrow('уже есть');expect(tx.partnerParticipant.update).not.toHaveBeenCalled();});
 test('admin cannot activate an invitation without user acceptance',async()=>{const {service,tx}=fixture();tx.partnerParticipant.findUniqueOrThrow.mockResolvedValue({...participant,status:'INVITED',acceptedTermsAt:null});await expect(service.participant('p',{status:'ACTIVE',decisionNote:'Approved'},'admin')).rejects.toThrow('принять условия');expect(tx.partnerParticipant.update).not.toHaveBeenCalled();});
 test('invite becomes pending only after current terms accepted personally',async()=>{const {service,tx}=fixture();tx.partnerParticipant.findUnique.mockResolvedValue({...participant,status:'INVITED',acceptedTermsAt:null});const publicSettings=(service as any).publicSettings(settings);await service.join('buyer',{kind:'BLOGGER',acceptedTerms:true,termsVersion:publicSettings.termsVersion,displayName:'Блогер',channels:[{label:'Канал',url:'https://example.invalid/channel'}]});expect(tx.partnerParticipant.update.mock.calls[0][0].data).toMatchObject({status:'PENDING',acceptedTermsAt:expect.any(Date)});expect(tx.partnerEvent.create.mock.calls[0][0].data.actorId).toBe('buyer');});
 test('an active profile without consent cannot attribute or settle',async()=>{const {service,tx}=fixture();tx.partnerClick.findUnique.mockResolvedValue({expiresAt:new Date(Date.now()+DAY),participant:{...participant,acceptedTermsAt:null}});expect(await attachPartner(tx,order,token)).toBeNull();tx.partnerParticipant.findUniqueOrThrow.mockResolvedValue({...participant,acceptedTermsAt:null});expect(await service.settle('admin')).toEqual({processed:0});});
 test('invitation endpoint has server write permission and staff roles',()=>{expect(Reflect.getMetadata('roles',PartnerAdminController.prototype.invite)).toEqual(['ADMIN','SUPERVISOR']);expect(Reflect.getMetadata('permissions',PartnerAdminController.prototype.invite)).toEqual(['partners.write']);});
});
describe('Blogger business registration bounty, never B2B sales',()=>{
 const org={id:'org',status:'PROSPECT'},owner={id:'buyer',email:'buyer@example.invalid',phone:'+79002223344',role:'CUSTOMER_B2C',isActive:true};
 test('new registration snapshots a fixed amount independent of purchases',async()=>{const {tx}=fixture();await attachPartnerRegistration(tx,org,owner,token);expect(tx.partnerBusinessRegistration.create.mock.calls[0][0].data).toMatchObject({organizationId:'org',amount:2500,unit:'RUB',holdDays:7});expect(tx.partnerAttribution.create).not.toHaveBeenCalled();expect(tx.partnerReward.upsert).not.toHaveBeenCalled();});
 test('referral participants cannot earn business bounty',async()=>{const {tx}=fixture();tx.partnerClick.findUnique.mockResolvedValue({expiresAt:new Date(Date.now()+DAY),participant:{...participant,kind:'REFERRAL'}});await attachPartnerRegistration(tx,org,owner,token);expect(tx.partnerBusinessRegistration.create).not.toHaveBeenCalled();});
 test('own registration and existing business owner excluded',async()=>{const {tx}=fixture();await attachPartnerRegistration(tx,org,{...owner,id:'partner'},token);tx.organizationMember.count.mockResolvedValue(1);await attachPartnerRegistration(tx,org,owner,token);expect(tx.partnerBusinessRegistration.create).not.toHaveBeenCalled();});
 test('zero or disabled bounty excluded',async()=>{const {tx}=fixture();tx.partnerProgramSetting.findUnique.mockResolvedValue({...settings,signupRewardAmount:0});await attachPartnerRegistration(tx,org,owner,token);expect(tx.partnerBusinessRegistration.create).not.toHaveBeenCalled();});
 test('active organization without independent verification cannot earn',async()=>{const {tx,registration}=fixture();registration.verifiedAt=null;await partnerBusinessActivated(tx,{id:'org',status:'ACTIVE'});expect(tx.partnerReward.upsert).not.toHaveBeenCalled();});
 test('verification without activation cannot earn',async()=>{const {tx}=fixture();await partnerBusinessActivated(tx,org);expect(tx.partnerReward.upsert).not.toHaveBeenCalled();});
 test('verification plus activation upserts one fixed reward per company',async()=>{const {tx}=fixture();await partnerBusinessActivated(tx,{id:'org',status:'ACTIVE'});expect(tx.partnerReward.upsert.mock.calls[0][0]).toMatchObject({where:{registrationId:'org'},update:{},create:{registrationId:'org',amount:2500}});});
 test('same company activation preserves original retention date',async()=>{const {tx,registration}=fixture();registration.activatedAt=new Date(2026,0,1);await partnerBusinessActivated(tx,{id:'org',status:'ACTIVE'});expect(tx.partnerReward.upsert.mock.calls[0][0].create.readyAt.getTime()).toBe(registration.activatedAt.getTime()+7*DAY);});
 test('verification requires an active owner and audit note',async()=>{const {service,tx,registration}=fixture();registration.verifiedAt=null;tx.organizationMember.findFirst.mockResolvedValue(null);await expect(service.verifyRegistration('org','Проверено','admin')).rejects.toThrow();expect(tx.partnerEvent.create).not.toHaveBeenCalled();});
});
describe('Maturity and payout safety',()=>{
 function bonusFixture(kind='REFERRAL'){
  const f=fixture();f.reward.unit='BONUS';f.reward.amount=50;f.tx.partnerParticipant.findUniqueOrThrow.mockResolvedValue({...participant,kind,user:{...participant.user}});
  f.tx.loyaltyProgramSetting.findUnique.mockResolvedValue({...DEFAULT_LOYALTY_SETTINGS});
  const account={id:'account',userId:'partner',balance:100,level:'START'};
  f.tx.loyaltyAccount={upsert:jest.fn().mockResolvedValue(account),findUniqueOrThrow:jest.fn().mockResolvedValue(account),update:jest.fn()};
  f.tx.loyaltyTransaction={findMany:jest.fn().mockResolvedValue([]),create:jest.fn().mockResolvedValue({id:'bonus-entry'})};
  f.tx.customer={findUnique:jest.fn().mockResolvedValue(null)};return f;
 }
 test('referral reward credits existing loyalty ledger with TTL and unique source',async()=>{const {service,tx}=bonusFixture();expect(await service.settle('admin')).toEqual({processed:1});expect(tx.loyaltyTransaction.create.mock.calls[0][0].data).toMatchObject({amount:50,type:'ACCRUAL',metadata:{source:'PARTNER',rewardId:'reward',ledgerVersion:1}});expect(tx.loyaltyTransaction.create.mock.calls[0][0].data.metadata.expiresAt).toBeTruthy();expect(tx.partnerReward.update.mock.calls[0][0].data).toMatchObject({loyaltyEntryId:'bonus-entry',creditedBonus:50});});
 test('blogger registration can credit bonus units without making them withdrawable',async()=>{const {service,tx,reward,registration}=bonusFixture('BLOGGER');reward.orderId=null;reward.order=null;reward.registrationId='org';reward.registration=registration;expect(await service.settle('admin')).toEqual({processed:1});expect(tx.loyaltyTransaction.create.mock.calls[0][0].data.reason).toContain('организации');expect(tx.partnerPayout.create).not.toHaveBeenCalled();});
 test('disabled loyalty retains bonus reward pending',async()=>{const {service,tx}=bonusFixture();tx.loyaltyProgramSetting.findUnique.mockResolvedValue({...DEFAULT_LOYALTY_SETTINGS,isEnabled:false});expect(await service.settle('admin')).toEqual({processed:0});expect(tx.loyaltyTransaction.create).not.toHaveBeenCalled();});
 test('bonus overflow cannot partially approve reward',async()=>{const {service,tx}=bonusFixture();tx.loyaltyAccount.findUniqueOrThrow.mockResolvedValue({id:'account',balance:2147483640});await expect(service.settle('admin')).rejects.toThrow();expect(tx.partnerReward.update).not.toHaveBeenCalled();});
 test('mature delivered cash reward is approved once with audit',async()=>{const {service,tx,reward}=fixture();expect(await service.settle('admin')).toEqual({processed:1});expect(tx.partnerReward.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:'APPROVED'})}));reward.status='APPROVED';expect(await service.settle('admin')).toEqual({processed:0});expect(tx.partnerEvent.create).toHaveBeenCalledTimes(1);});
 test.each([{paymentStatus:'PENDING'},{status:'SHIPPED'},{source:'B2B'},{payments:[]}])('cannot approve unverified/unfulfilled order %j',async change=>{const {service,reward,tx}=fixture();Object.assign(reward.order,change);expect(await service.settle('admin')).toEqual({processed:0});expect(tx.partnerReward.update).not.toHaveBeenCalled();});
 test('signup maturity also rechecks organization activation',async()=>{const {service,reward,registration}=fixture();reward.order=null;reward.orderId=null;reward.registrationId='org';reward.registration=registration;registration.organization.status='ON_HOLD';expect(await service.settle('admin')).toEqual({processed:0});});
 test('future maturity or paused partner cannot credit',async()=>{const {service,reward,tx}=fixture();reward.readyAt=new Date(Date.now()+DAY);expect(await service.settle('admin')).toEqual({processed:0});reward.readyAt=new Date(0);tx.partnerParticipant.findUniqueOrThrow.mockResolvedValue({...participant,status:'SUSPENDED'});expect(await service.settle('admin')).toEqual({processed:0});});
 test('payout reserves funds and records audit under participant lock',async()=>{const {service,tx}=fixture();await service.requestPayout('buyer',{requestKey:'key',amount:1000});expect(tx.$queryRaw).toHaveBeenCalled();expect(tx.partnerPayout.create).toHaveBeenCalledTimes(1);expect(tx.partnerEvent.create).toHaveBeenCalled();});
 test('insufficient cash cannot request payout',async()=>{const {service,tx}=fixture();await expect(service.requestPayout('buyer',{requestKey:'key',amount:3000.01})).rejects.toThrow();expect(tx.partnerPayout.create).not.toHaveBeenCalled();});
 test('unverified payee cannot request payout',async()=>{const {service,tx}=fixture();tx.partnerParticipant.findUniqueOrThrow.mockResolvedValue({...participant,payoutVerified:false});await expect(service.requestPayout('buyer',{requestKey:'key',amount:1000})).rejects.toThrow();});
 test('idempotent payout replay never reserves twice',async()=>{const {service,tx,payout}=fixture();tx.partnerPayout.findUnique.mockResolvedValue(payout);await service.requestPayout('buyer',{requestKey:'key',amount:1000});expect(tx.partnerPayout.create).not.toHaveBeenCalled();await expect(service.requestPayout('buyer',{requestKey:'key',amount:1001})).rejects.toThrow();});
 test('cannot bypass approval or missing transfer document',async()=>{const {service,payout,tx}=fixture();await expect(service.decidePayout('pay',{status:'PAID',note:'Done',paymentReference:'DOC'},'admin')).rejects.toThrow();payout.status='APPROVED';await expect(service.decidePayout('pay',{status:'PAID',note:'Done'},'admin')).rejects.toThrow();expect(tx.partnerPayout.update).not.toHaveBeenCalled();});
 test('actual transfer confirmation is audit-only, unique and replay-safe',async()=>{const {service,payout,tx}=fixture();payout.status='APPROVED';await service.decidePayout('pay',{status:'PAID',note:'Actual transfer',paymentReference:'DOC-001'},'admin');expect(tx.partnerPayout.update.mock.calls[0][0].data).toMatchObject({status:'PAID',paymentReference:'DOC-001',decidedBy:'admin'});payout.status='PAID';payout.paymentReference='DOC-001';await service.decidePayout('pay',{status:'PAID',note:'Replay',paymentReference:'DOC-001'},'admin');expect(tx.partnerPayout.update).toHaveBeenCalledTimes(1);await expect(service.decidePayout('pay',{status:'PAID',note:'Other',paymentReference:'OTHER'},'admin')).rejects.toThrow();});
 test('server requires admin cash permission independently of menu',()=>{expect(Reflect.getMetadata('roles',PartnerAdminController.prototype.decide)).toEqual(['ADMIN']);expect(Reflect.getMetadata('permissions',PartnerAdminController.prototype.decide)).toEqual(['partners.payouts']);expect(Reflect.getMetadata('permissions',PartnerAdminController.prototype.registration)).toEqual(['partners.write']);});
});
