<script setup lang="ts">
import { ArrowRight, RotateCcw, X } from '@lucide/vue';
defineProps<{ orders: any[]; title: string }>(); const emit = defineEmits<{ updated: [] }>();
const config = useRuntimeConfig(); const { authHeaders, cartSession, cart } = useStorefront();
const { storefrontMediaUrl } = useStorefrontContent();
const selected = ref<any>(null), detail = ref<any>(null), busy = ref(''), error = ref(''), repeated = ref(false), confirmingCancel = ref(false);
const unavailable = ref<{ productName: string; reason: string }[]>([]);
const statuses: Record<string, string> = { NEW: 'Новый', CONFIRMED: 'Подтверждён', PAYMENT_WAITING: 'Ожидает оплаты', PAID: 'Оплачен', ASSEMBLING: 'Собирается', SHIPPED: 'Отправлен', DELIVERED: 'Доставлен', CANCELLED: 'Отменён', REFUNDED: 'Возврат выполнен' };
const status = (value: string) => statuses[value] || 'Статус уточняется';
const money = (value: any) => `${Number(value || 0).toLocaleString('ru-RU')} ₽`;
const date = (value: string) => new Date(value).toLocaleDateString('ru-RU');
const delivery = computed(() => { const address = detail.value?.shippingAddress; if (typeof address === 'string') return address; if (!address || typeof address !== 'object') return ''; return [address.city, address.street, address.house, address.apartment ? `кв. ${address.apartment}` : '', address.address, address.pickupPointAddress].filter(Boolean).join(', '); });
const cancellable = computed(() => detail.value && ['NEW', 'PAYMENT_WAITING'].includes(detail.value.status));
const paymentStatuses: Record<string,string> = { PENDING: 'Ожидает оплаты', WAITING_FOR_CAPTURE: 'Ожидает подтверждения', SUCCEEDED: 'Оплачен', FAILED: 'Ошибка оплаты', CANCELED: 'Отменён', CANCELLED: 'Отменён', REFUNDED: 'Возвращён' };
const unavailableReasons: Record<string, string> = { OUT_OF_STOCK: 'Нет в наличии', INACTIVE: 'Товар снят с продажи', NOT_FOUND: 'Товар больше недоступен', INSUFFICIENT_STOCK: 'Доступно меньше, чем в прежнем заказе' };
const reason = (value: string) => unavailableReasons[value] || (/[а-яё]/i.test(value) ? value : 'Позиция недоступна');
function requestOptions() { return { baseURL: config.public.apiBase, headers: authHeaders.value }; }
function message(exception: any) { const text = exception?.data?.message; return Array.isArray(text) ? text.join('. ') : typeof text === 'string' && !text.startsWith('Cannot ') ? text : 'Не удалось выполнить действие. Попробуйте ещё раз.'; }
async function loadDetail() { if (!selected.value || busy.value) return; busy.value = 'detail'; error.value = ''; try { detail.value = await $fetch(`/storefront/orders/${encodeURIComponent(selected.value.orderNumber)}`, requestOptions()); } catch (exception) { error.value = message(exception); } finally { busy.value = ''; } }
function open(order: any) { selected.value = order; detail.value = null; repeated.value = false; unavailable.value = []; confirmingCancel.value = false; loadDetail(); }
async function repeat() { if (busy.value || repeated.value) return; busy.value = 'repeat'; error.value = ''; try { const result = await $fetch<any>(`/storefront/orders/${encodeURIComponent(selected.value.orderNumber)}/repeat`, { ...requestOptions(), method: 'POST', headers: { ...authHeaders.value, 'x-cart-session': cartSession.value } }); cart.value = result.cart; unavailable.value = result.unavailable || []; repeated.value = Number(result.added) > 0 || Array.isArray(result.added) && result.added.length > 0; if (!repeated.value && !unavailable.value.length) error.value = 'В заказе нет доступных для повтора товаров.'; } catch (exception) { error.value = message(exception); } finally { busy.value = ''; } }
async function cancel() { if (busy.value || !cancellable.value) return; busy.value = 'cancel'; error.value = ''; try { detail.value = await $fetch(`/storefront/orders/${encodeURIComponent(selected.value.orderNumber)}/cancel`, { ...requestOptions(), method: 'POST' }); confirmingCancel.value = false; } catch (exception) { error.value = message(exception); } finally { busy.value = ''; } }
function close() { if (busy.value) return; selected.value = null; if (detail.value?.status === 'CANCELLED') emit('updated'); }
</script>
<template>
  <section class="sa-panel"><h2>{{ title }}</h2><div v-if="orders.length"><button v-for="order in orders" :key="order.id" class="sa-order" @click="open(order)"><span><b>{{ order.orderNumber }}</b><small>{{ date(order.createdAt) }} · {{ order.items?.length || 0 }} поз.</small></span><span class="sa-badge">{{ status(order.status) }}</span><strong>{{ money(order.finalAmount) }}</strong><ArrowRight :size="20" /></button></div><div v-else><p>Заказов пока нет. После покупки здесь появится история и состав заказа.</p><NuxtLink class="sa-button" to="/catalog">Перейти в каталог <ArrowRight :size="20" /></NuxtLink></div><small v-if="orders.length >= 30" class="sa-muted">Показаны последние 30 заказов. Более ранние заказы можно уточнить в поддержке.</small></section>
  <SiteAccountDrawer :open="!!selected" :title="`Заказ ${selected?.orderNumber || ''}`" @close="close">
    <p v-if="busy === 'detail'" role="status">Загружаем заказ…</p><p v-if="error" class="sa-feedback" role="alert">{{ error }}</p><button v-if="!detail && !busy" class="sa-button" @click="loadDetail">Повторить загрузку <ArrowRight :size="20" /></button>
    <template v-if="detail"><p>{{ date(detail.createdAt) }} · {{ status(detail.status) }}</p><div class="sa-order-items"><article v-for="item in detail.items" :key="item.id"><img v-if="item.variant?.product?.images?.[0]?.url" :src="storefrontMediaUrl(item.variant.product.images[0].url)" alt="" /><div><b>{{ item.productName }}</b><small v-if="item.variantName && item.variantName !== item.productName">{{ item.variantName }}</small><small>{{ item.quantity }} шт. × {{ money(item.price) }}</small></div><strong>{{ money(item.total) }}</strong></article></div><div class="sa-totals"><span>Сумма заказа</span><b>{{ money(detail.finalAmount) }}</b></div><template v-if="delivery"><h3>Адрес доставки</h3><p>{{ delivery }}</p></template><template v-if="detail.comments"><h3>Комментарий к заказу</h3><p>{{ detail.comments }}</p></template>
      <template v-if="detail.history?.length"><h3>История заказа</h3><ol class="sa-timeline"><li v-for="entry in detail.history" :key="entry.id"><b>{{ status(entry.toStatus) }}</b><small>{{ date(entry.createdAt) }}</small></li></ol></template>
      <template v-if="detail.payments?.length"><h3>Оплата</h3><article v-for="payment in detail.payments" :key="payment.id" class="sa-history"><span>{{ paymentStatuses[payment.status] || 'Статус оплаты уточняется' }}</span><b>{{ money(payment.amount) }}</b></article></template>
      <p class="sa-muted">При повторе товары добавляются в корзину по текущим ценам и наличию. Новый заказ оформляется только после вашей проверки.</p><p v-if="repeated" class="sa-feedback" role="status">Доступные товары добавлены в корзину.</p><ul v-if="unavailable.length" class="sa-feedback"><li v-for="(item, index) in unavailable" :key="index">{{ item.productName }} — {{ reason(item.reason) }}</li></ul>
      <div class="sa-actions"><button v-if="!repeated" class="sa-button" :disabled="!!busy" @click="repeat">{{ busy === 'repeat' ? 'Добавляем…' : 'Повторить заказ' }}<RotateCcw :size="20" /></button><NuxtLink v-else class="sa-button" to="/cart">Перейти в корзину <ArrowRight :size="20" /></NuxtLink><button v-if="cancellable && !confirmingCancel" class="sa-button sa-secondary" :disabled="!!busy" @click="confirmingCancel = true">Отменить заказ <X :size="20" /></button></div>
      <section v-if="confirmingCancel" class="sa-feedback"><h3>Отменить заказ?</h3><p>Заказ будет отменён, резерв товаров освободится. Это действие нельзя отменить.</p><div class="sa-actions"><button class="sa-button sa-secondary" :disabled="!!busy" @click="confirmingCancel = false">Оставить заказ</button><button class="sa-button" :disabled="!!busy" @click="cancel">{{ busy === 'cancel' ? 'Отменяем…' : 'Подтвердить отмену' }}<X :size="20" /></button></div></section>
      <NuxtLink class="sa-text-button" to="/contacts">Связаться с поддержкой <ArrowRight :size="18" /></NuxtLink>
    </template>
  </SiteAccountDrawer>
</template>
