<script setup lang="ts">
import { ArrowRight, Building2 } from '@lucide/vue';
const props=defineProps<{code:string}>(),config=useRuntimeConfig();
const data=ref<any>(null),loading=ref(true),busy=ref(false),error=ref(''),consent=ref(false);
const visitor=useCookie<string|null>('sb-partner-visitor',{watch:false});
function saveCookie(name:string,value:string,maxAge:number){document.cookie=`${name}=${encodeURIComponent(JSON.stringify(value))}; Path=/; SameSite=Lax; Max-Age=${Math.max(1,maxAge)}${location.protocol==='https:'?'; Secure':''}`;refreshCookie(name);}
async function load(){loading.value=true;try{data.value=await $fetch(`/partners/link/${encodeURIComponent(props.code)}`,{baseURL:config.public.apiBase});}catch{error.value='Партнёрская ссылка недоступна или программа приостановлена.';}finally{loading.value=false;}}
async function go(business=false){if(busy.value||!consent.value)return;busy.value=true;error.value='';try{const visitorId=visitor.value||crypto.randomUUID();const result=await $fetch<any>(`/partners/link/${encodeURIComponent(props.code)}/visit`,{baseURL:config.public.apiBase,method:'POST',body:{visitorId,consent:true}});const maxAge=Math.ceil((Date.parse(result.expiresAt)-Date.now())/1000);saveCookie('sb-partner-visitor',visitorId,maxAge);saveCookie('sb-partner-attribution',result.token,maxAge);await navigateTo(business?'/business-registration':'/catalog');}catch{error.value='Не удалось сохранить переход. Попробуйте снова.';}finally{busy.value=false;}}
onMounted(load);
</script>
<template><section class="sa-ui sp-landing sa-panel"><p class="sa-eyebrow">SARKISIAN · ПАРТНЁРСКАЯ ПРОГРАММА</p><h1>{{data?'Вас приглашает '+data.displayName:'Приглашение в SARKISIAN'}}</h1><p v-if="loading" role="status">Проверяем ссылку…</p><p v-if="error" class="sa-feedback" role="alert">{{error}}</p><template v-if="data"><p>Выберите товары в магазине{{data.businessRegistration?' или зарегистрируйте свой салон или бизнес':''}}.</p><label class="sp-check"><input v-model="consent" type="checkbox"/>Согласен сохранить партнёрский переход на этом устройстве для привязки покупок{{data.businessRegistration?' и регистрации организации':''}} в течение {{data.attributionDays}} дней.</label><p class="sa-muted">Сохранение происходит после вашего согласия. Партнёр не получает ваши контакты или адрес. <NuxtLink to="/privacy">Политика обработки данных</NuxtLink></p><div class="sa-actions"><button class="sa-button" :disabled="busy||!consent" @click="go()">Перейти в магазин<ArrowRight :size="18"/></button><button v-if="data.businessRegistration" class="sa-button sa-secondary" :disabled="busy||!consent" @click="go(true)"><Building2 :size="18"/>Зарегистрировать бизнес</button></div></template><NuxtLink v-else-if="!loading" to="/catalog" class="sa-button sa-secondary">Открыть магазин</NuxtLink></section></template>
