<script setup lang="ts">
import { Copy, ExternalLink, Wallet, Users, Link2, Check } from '@lucide/vue';
const props=defineProps<{kind:'REFERRAL'|'BLOGGER'}>();
const config=useRuntimeConfig(),{authHeaders}=useStorefront();
const data=ref<any>(null),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),accepted=ref(false);
const name=ref(''),channelLabel=ref(''),channelUrl=ref(''),description=ref(''),payoutAmount=ref<number|undefined>(),requestKey=ref('');
const link=computed(()=>data.value?.participant&&import.meta.client?`${location.origin}/r/${data.value.participant.code}`:'');
const number=(v:any)=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const sum=(unit:string,status:string)=>number(data.value?.summary?.totals?.find((v:any)=>v.unit===unit&&v.status===status)?._sum.amount);
const statuses:Record<string,string>={INVITED:'Вы приглашены',PENDING:'На проверке',ACTIVE:'Активен',SUSPENDED:'Приостановлен',REJECTED:'Отклонено',APPROVED:'Подтверждено',REQUESTED:'Запрошено',PAID:'Выплачено',CANCELLED:'Отменено',REVERSED:'Сторнировано'};
const api=(path:string,options:any={})=>$fetch<any>('/partners/'+path,{baseURL:config.public.apiBase,headers:authHeaders.value,timeout:15000,...options});
const message=(e:any)=>Array.isArray(e?.data?.message)?e.data.message.join(' · '):e?.data?.message||'Не удалось выполнить действие. Повторите запрос.';
async function load(){loading.value=true;error.value='';try{data.value=await api(`me/${props.kind}`);if(data.value.participant?.status==='INVITED'){const p=data.value.participant;name.value=p.displayName;description.value=p.description||'';channelLabel.value=p.channels?.[0]?.label||'';channelUrl.value=p.channels?.[0]?.url||'';}}catch(e){error.value=message(e);}finally{loading.value=false;}}
async function action(callback:()=>Promise<any>,success:string){if(busy.value)return;busy.value=true;notice.value='';error.value='';try{await callback();notice.value=success;await load();}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function join(){await action(()=>api('join',{method:'POST',body:{kind:props.kind,acceptedTerms:accepted.value,termsVersion:data.value.settings.termsVersion,...(props.kind==='BLOGGER'?{displayName:name.value,channels:[{label:channelLabel.value,url:channelUrl.value}],description:description.value}:{})}}),props.kind==='BLOGGER'?'Заявка отправлена. Мы рассмотрим ваши каналы.':'Вы участвуете в программе. Ваша ссылка готова.');}
async function copy(){try{await navigator.clipboard.writeText(link.value);notice.value='Ссылка скопирована';}catch{notice.value='Не удалось скопировать автоматически. Выделите и скопируйте ссылку.';}}
async function payout(){if(!requestKey.value)requestKey.value=crypto.randomUUID();await action(async()=>{try{await api('payouts',{method:'POST',body:{requestKey:requestKey.value,amount:payoutAmount.value}});}catch(e:any){if(Number(e?.statusCode||e?.status)>=400&&Number(e?.statusCode||e?.status)<500)requestKey.value='';throw e;}requestKey.value='';payoutAmount.value=undefined;},'Заявка на выплату создана');}
onMounted(load);watch(()=>props.kind,()=>{accepted.value=false;notice.value='';requestKey.value='';data.value=null;load();});
</script>
<template>
 <section class="sp-account" :aria-busy="loading||busy"><header class="sa-panel"><h2>{{kind==='REFERRAL'?'Приглашайте друзей':'Кабинет блогера'}}</h2><p>{{kind==='REFERRAL'?'Персональная ссылка и бонусы для покупок на сайте — без денежных выплат.':'Ваша ссылка, начисления за B2C-заказы и привлечение организаций, аналитика и заявки на денежные выплаты.'}}</p></header>
 <p v-if="error" class="sa-feedback" role="alert">{{error}}</p><p v-if="notice" class="sa-feedback" role="status">{{notice}}</p><p v-if="loading&&!data" class="sa-panel" role="status">Загружаем программу…</p><button v-if="error&&!data" class="sa-button sa-secondary" @click="load">Повторить</button>
 <template v-if="data">
  <form v-if="!data.participant||['REJECTED','INVITED'].includes(data.participant.status)" class="sa-panel sp-join" @submit.prevent="join"><p v-if="data.participant?.status==='INVITED'" class="sa-feedback">Вас пригласили в партнёрскую программу. Укажите канал и примите условия — после этого менеджер одобрит заявку.</p><h3>{{kind==='BLOGGER'?'Стать партнёром':'Присоединиться к программе'}}</h3><p v-if="data.participant?.decisionNote" class="sa-feedback">{{data.participant.decisionNote}}</p><p v-if="!data.settings.isEnabled" class="sa-muted">Программа пока не открыта. Участие станет доступно после запуска.</p><template v-else><p>Вознаграждение за покупку — {{number(data.settings.rewardPercent)}}{{kind==='REFERRAL'?'% бонусами':'% деньгами'}}. Ссылка действует {{data.settings.attributionDays}} дней; начисление после доставки и {{data.settings.holdDays}} дней ожидания.</p><p v-if="kind==='BLOGGER'&&Number(data.settings.signupRewardAmount)>0">За новую проверенную и активированную организацию — {{number(data.settings.signupRewardAmount)}} {{data.settings.signupRewardUnit==='BONUS'?'бонусов':'₽'}}, однократно. B2B-продажи не участвуют.</p><template v-if="kind==='BLOGGER'"><div class="sp-form-grid"><label>Публичное имя<input v-model="name" maxlength="120" required/></label><label>Название канала<input v-model="channelLabel" maxlength="40" required placeholder="Например, Telegram"/></label></div><label>Ссылка на ваш канал<input v-model="channelUrl" type="url" maxlength="500" pattern="https://.*" placeholder="https://…" required/></label><label>Расскажите о своей аудитории<textarea v-model="description" maxlength="2000" rows="3"/></label></template><details class="sp-terms"><summary>Условия участия</summary><p>{{data.settings.termsText}}</p></details><label class="sp-check"><input v-model="accepted" type="checkbox" required/>Принимаю условия программы</label><button class="sa-button" :disabled="busy||!accepted" type="submit"><Check :size="18"/>{{kind==='BLOGGER'?'Отправить заявку':'Получить ссылку'}}</button></template></form>
  <template v-else><article class="sa-panel sp-link"><header><h3>Ваша персональная ссылка</h3><span class="sp-status">{{statuses[data.participant.status]}}</span></header><p v-if="data.participant.status==='PENDING'">Заявка рассматривается. Ссылка станет доступна после одобрения.</p><p v-else-if="data.participant.status==='SUSPENDED'">Участие приостановлено. Начисления и история сохранены.</p><p v-if="!data.settings.isEnabled" class="sa-muted">Программа сейчас приостановлена. Новые переходы и начисления недоступны.</p><p v-if="data.participant.decisionNote" class="sa-muted">{{data.participant.decisionNote}}</p><div v-if="data.participant.status==='ACTIVE'" class="sp-copy-row"><input :value="link" readonly aria-label="Персональная ссылка" @focus="($event.target as HTMLInputElement).select()"/><button class="sa-button sa-secondary" @click="copy"><Copy :size="18"/>Копировать</button></div><p>За B2C-покупки — {{number(data.participant.rewardPercent)}}% {{kind==='REFERRAL'?'бонусами':'деньгами'}}. Самоприглашения и B2B-заказы исключены.</p><p v-if="kind==='BLOGGER'&&Number(data.settings.signupRewardAmount)>0">За привлечение организации — {{number(data.settings.signupRewardAmount)}} {{data.settings.signupRewardUnit==='BONUS'?'бонусов':'₽'}} после проверки и активации. Не процент с оптовых продаж.</p></article>
   <div class="sp-metrics"><article class="sa-panel"><Users :size="20"/><span>Посетители по ссылке</span><strong>{{data.summary.uniqueVisitors}}</strong><small>{{data.summary.visits}} переходов с согласием</small></article><article class="sa-panel"><Link2 :size="20"/><span>Привязанные заказы</span><strong>{{data.summary.orders}}</strong><small v-if="kind==='BLOGGER'">{{data.summary.registrations}} организаций</small></article><article class="sa-panel"><Wallet :size="20"/><span>{{kind==='REFERRAL'?'Бонусы подтверждены':'Доступно к выплате'}}</span><strong>{{kind==='REFERRAL'?sum('BONUS','APPROVED'):number(data.summary.availableCash)}}{{kind==='BLOGGER'?' ₽':''}}</strong><small>В ожидании: {{sum(kind==='REFERRAL'?'BONUS':'RUB','PENDING')}}</small></article></div>
   <article class="sa-panel"><h3>Последние начисления</h3><p v-if="!data.rewards?.length" class="sa-muted">Начисления появятся после подтверждённой оплаты приглашённым покупателем или проверки новой организации.</p><div v-else class="sp-history"><article v-for="reward in data.rewards" :key="reward.id"><span><strong>{{reward.registrationId?'Привлечение организации':'B2C-заказ'}}</strong><small>{{new Date(reward.createdAt).toLocaleDateString('ru-RU')}} · {{statuses[reward.status]}}</small><small v-if="reward.readyAt&&reward.status==='PENDING'">Доступно не ранее {{new Date(reward.readyAt).toLocaleDateString('ru-RU')}}</small></span><b>{{number(reward.amount)}} {{reward.unit==='BONUS'?'бонусов':'₽'}}</b></article></div><small class="sa-muted">Показаны последние 30 начислений; показатели выше учитывают всю историю.</small></article>
   <article v-if="kind==='BLOGGER'" class="sa-panel sp-payouts"><h3>Денежные выплаты</h3><p v-if="!data.participant.payoutVerified" class="sa-muted">Перед первой выплатой менеджер проверит получателя и необходимые документы. Реквизиты банковской карты здесь не запрашиваются.</p><form v-else-if="data.participant.status==='ACTIVE'&&data.settings.isEnabled" @submit.prevent="payout"><label>Сумма выплаты, ₽<input v-model.number="payoutAmount" type="number" :min="Number(data.settings.minimumPayout)" :max="Number(data.summary.availableCash)" step="0.01" required :disabled="busy||!!requestKey"/></label><button class="sa-button" :disabled="busy||Number(data.summary.availableCash)<Number(data.settings.minimumPayout)" type="submit">{{requestKey?'Повторить запрос':'Запросить выплату'}}</button><small>Минимум {{number(data.settings.minimumPayout)}} ₽. Бонусы на сайте не выводятся деньгами.</small></form><div v-if="data.payouts?.length" class="sp-history"><article v-for="entry in data.payouts" :key="entry.id"><span><strong>{{number(entry.amount)}} ₽ · {{statuses[entry.status]}}</strong><small>{{new Date(entry.createdAt).toLocaleDateString('ru-RU')}}</small><small v-if="entry.decisionNote">{{entry.decisionNote}}</small></span><button v-if="entry.status==='REQUESTED'" class="sa-button sa-secondary" :disabled="busy" @click="action(()=>api(`payouts/${entry.id}/cancel`,{method:'POST'}),'Заявка отменена')">Отменить</button></article></div></article>
  </template>
 </template></section>
</template>
