<script setup lang="ts">
import { ArrowRight, MapPin, Pencil, Plus, Trash2 } from '@lucide/vue';
const props = defineProps<{ addresses: any[]; profile: any }>(); const emit = defineEmits<{ updated: [value: any[]] }>();
const config = useRuntimeConfig(); const { authHeaders } = useStorefront();
const editor = ref(false), editingId = ref(''), deleting = ref<any>(null), busy = ref(false), error = ref(''), notice = ref('');
const form = reactive({ label: '', recipientName: '', phone: '', city: '', street: '', house: '', apartment: '', isDefault: false });
function edit(address?: any) { error.value = ''; notice.value = ''; editingId.value = address?.id || ''; Object.assign(form, { label: address?.label || '', recipientName: address?.recipientName || `${props.profile.firstName || ''} ${props.profile.lastName || ''}`.trim(), phone: address?.phone || props.profile.phone || '', city: address?.city || props.profile.city || '', street: address?.street || '', house: address?.house || '', apartment: address?.apartment || '', isDefault: address?.isDefault || !props.addresses.length }); editor.value = true; }
async function refresh() { emit('updated', await $fetch<any[]>('/storefront/addresses', { baseURL: config.public.apiBase, headers: authHeaders.value })); }
async function mutate(fn: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; notice.value = ''; try { await fn(); } catch (exception: any) { const message = exception?.data?.message; error.value = Array.isArray(message) ? message.join('. ') : typeof message === 'string' ? message : 'Не удалось изменить адрес. Попробуйте ещё раз.'; } finally { busy.value = false; } }
function save() { return mutate(async () => { const body = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, typeof value === 'string' ? value.trim() : value])); await $fetch(`/storefront/addresses${editingId.value ? `/${encodeURIComponent(editingId.value)}` : ''}`, { baseURL: config.public.apiBase, method: editingId.value ? 'PATCH' : 'POST', headers: authHeaders.value, body }); editor.value = false; await refresh(); notice.value = 'Адрес сохранён.'; }); }
function remove() { return mutate(async () => { await $fetch(`/storefront/addresses/${encodeURIComponent(deleting.value.id)}`, { baseURL: config.public.apiBase, method: 'DELETE', headers: authHeaders.value }); deleting.value = null; await refresh(); notice.value = 'Адрес удалён.'; }); }
function askDelete(address: any) { error.value = ''; deleting.value = address; }
</script>
<template>
  <section class="sa-panel"><div class="sa-section-head"><h2>Адреса доставки</h2><button class="sa-button" @click="edit()"><Plus :size="20" />Добавить адрес</button></div><p v-if="notice" class="sa-feedback" role="status">{{ notice }}</p><p v-if="error && !editor && !deleting" class="sa-feedback" role="alert">{{ error }}</p><p v-if="!addresses.length" class="sa-muted">Сохраните адрес, чтобы не вводить его при следующем заказе.</p><div v-else><article v-for="address in addresses" :key="address.id" class="sa-address"><MapPin :size="24" /><div><h3>{{ address.label || 'Адрес доставки' }}<small v-if="address.isDefault" class="sa-badge">Основной</small></h3><p>{{ address.city }}, {{ address.street }}, {{ address.house }}{{ address.apartment ? `, кв. ${address.apartment}` : '' }}</p><small>{{ address.recipientName }} · {{ address.phone }}</small><div class="sa-actions"><button class="sa-button sa-secondary" @click="edit(address)">Изменить <Pencil :size="18" /></button><button class="sa-button sa-secondary" @click="askDelete(address)">Удалить <Trash2 :size="18" /></button></div></div></article></div></section>
  <SiteAccountDrawer :open="editor" :title="editingId ? 'Изменить адрес' : 'Новый адрес'" @close="!busy && (editor = false)"><form class="sa-form" @submit.prevent="save"><p v-if="error" class="sa-feedback" role="alert">{{ error }}</p><label>Название адреса<input v-model="form.label" maxlength="40" placeholder="Например, дом или работа" /></label><label>Имя получателя<input v-model="form.recipientName" required minlength="2" maxlength="160" autocomplete="name" /></label><label>Телефон получателя<input v-model="form.phone" type="tel" required minlength="7" maxlength="30" autocomplete="tel" /></label><label>Город<input v-model="form.city" required minlength="2" maxlength="120" autocomplete="address-level2" /></label><label>Улица<input v-model="form.street" required minlength="2" maxlength="180" autocomplete="address-line1" /></label><div class="sa-field-grid"><label>Дом<input v-model="form.house" required maxlength="40" /></label><label>Квартира или офис<input v-model="form.apartment" maxlength="40" autocomplete="address-line2" /></label></div><label class="sa-checkbox"><input v-model="form.isDefault" type="checkbox" />Использовать как основной адрес</label><button class="sa-button" :disabled="busy">{{ busy ? 'Сохраняем…' : 'Сохранить адрес' }}<ArrowRight :size="20" /></button></form></SiteAccountDrawer>
  <SiteAccountDrawer :open="!!deleting" title="Удалить адрес?" @close="!busy && (deleting = null)"><p>Удалить адрес «{{ deleting?.label || 'Адрес доставки' }}»? Данные в уже оформленных заказах не изменятся.</p><p v-if="error" class="sa-feedback" role="alert">{{ error }}</p><div class="sa-actions"><button class="sa-button sa-secondary" :disabled="busy" @click="deleting = null">Отмена</button><button class="sa-button" :disabled="busy" @click="remove">{{ busy ? 'Удаляем…' : 'Удалить адрес' }}<Trash2 :size="20" /></button></div></SiteAccountDrawer>
</template>
