<script setup lang="ts">
import { ArrowRight, Camera, Trash2 } from '@lucide/vue';
const props = defineProps<{ profile: any }>(); const emit = defineEmits<{ updated: [value: any]; 'password-changed': [] }>();
const config = useRuntimeConfig(); const { authHeaders } = useStorefront();
const busy = ref(''), error = ref(''), notice = ref(''), confirmAvatar = ref(false);
const form = reactive({ firstName: '', lastName: '', phone: '', birthday: '' });
const birthdayMax = ref('');
const isB2C = computed(() => props.profile.role === 'CUSTOMER_B2C');
onMounted(() => { const now = new Date(); birthdayMax.value = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; });
const password = reactive({ currentPassword: '', newPassword: '', confirmation: '' });
watch(() => props.profile, value => Object.assign(form, { firstName: value.firstName || '', lastName: value.lastName || '', phone: value.phone || '', birthday: value.birthday || '' }), { immediate: true });
const avatar = computed(() => { try { const url = new URL(props.profile.avatarUrl || '', config.public.apiBase); return props.profile.avatarUrl && ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } });
async function action(name: string, fn: () => Promise<void>) { if (busy.value) return; busy.value = name; error.value = ''; notice.value = ''; try { await fn(); } catch (exception: any) { const value = exception?.data?.message; error.value = Array.isArray(value) ? value.join('. ') : typeof value === 'string' ? value : 'Не удалось сохранить изменения. Попробуйте ещё раз.'; } finally { busy.value = ''; } }
function requestChange() { return action('request', async () => {
  const body: Record<string, string> = {};
  for (const key of ['firstName', 'lastName', 'phone', 'birthday'] as const) if ((key !== 'birthday' || isB2C.value) && form[key].trim() !== (props.profile[key] || '') && form[key].trim()) body[key] = form[key].trim();
  if (body.birthday) {
    const date = new Date(`${body.birthday}T00:00:00Z`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(body.birthday) || !Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== body.birthday || body.birthday < '1900-01-01' || !birthdayMax.value || body.birthday > birthdayMax.value) { error.value = 'Укажите дату рождения с 1 января 1900 года по сегодняшний день.'; return; }
  }
  if (!Object.keys(body).length) { error.value = isB2C.value ? 'Измените имя, фамилию, телефон или дату рождения перед отправкой запроса.' : 'Измените имя, фамилию или телефон перед отправкой запроса.'; return; }
  const pendingChangeRequest = await $fetch('/auth/profile/change-request', { baseURL: config.public.apiBase, method: 'POST', headers: authHeaders.value, body });
  emit('updated', { pendingChangeRequest }); notice.value = 'Запрос отправлен. Данные изменятся после подтверждения сотрудником.';
}); }
function changePassword() { return action('password', async () => { if (password.newPassword !== password.confirmation) { error.value = 'Новые пароли не совпадают.'; return; } if (password.newPassword.length < 10 || !/[a-zа-яё]/i.test(password.newPassword) || !/\d/.test(password.newPassword)) { error.value = 'Нужен пароль от 10 символов с буквами и цифрами.'; return; } await $fetch('/auth/profile/password', { baseURL: config.public.apiBase, method: 'POST', headers: authHeaders.value, body: { currentPassword: password.currentPassword, newPassword: password.newPassword } }); Object.assign(password, { currentPassword: '', newPassword: '', confirmation: '' }); emit('password-changed'); }); }
async function upload(event: Event) { const input = event.target as HTMLInputElement, file = input.files?.[0]; input.value = ''; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { error.value = 'Выберите JPG, PNG или WebP размером до 5 МБ.'; return; } await action('avatar', async () => { const body = new FormData(); body.append('file', file); emit('updated', await $fetch('/auth/profile/avatar', { baseURL: config.public.apiBase, method: 'POST', headers: authHeaders.value, body })); notice.value = 'Фото обновлено.'; }); }
function removeAvatar() { return action('avatar', async () => { await $fetch('/auth/profile/avatar', { baseURL: config.public.apiBase, method: 'DELETE', headers: authHeaders.value }); emit('updated', { avatarUrl: null }); confirmAvatar.value = false; notice.value = 'Фото удалено.'; }); }
</script>
<template><div>
  <p v-if="error" class="sa-feedback" role="alert">{{ error }}</p><p v-if="notice" class="sa-feedback" role="status">{{ notice }}</p>
  <section class="sa-panel"><h2>Мои данные</h2><div class="sa-avatar-row"><img v-if="avatar" :src="avatar" alt="Ваше фото" class="sa-avatar" /><span v-else class="sa-avatar sa-initials">{{ (profile.firstName || profile.email || 'К').slice(0, 1).toUpperCase() }}</span><div><label class="sa-button sa-secondary sa-upload"><Camera :size="20" />{{ busy === 'avatar' ? 'Сохраняем фото…' : 'Загрузить фото' }}<input type="file" accept="image/jpeg,image/png,image/webp" :disabled="!!busy" @change="upload" /></label><small>JPG, PNG, WebP — до 5 МБ</small><button v-if="avatar" class="sa-text-button" :disabled="!!busy" @click="confirmAvatar = true"><Trash2 :size="18" />Удалить фото</button></div></div>
    <form class="sa-form" @submit.prevent="requestChange"><div class="sa-field-grid sa-profile-fields"><label>Имя<input v-model="form.firstName" required maxlength="80" autocomplete="given-name" :disabled="!!profile.pendingChangeRequest || !!busy" /></label><label>Фамилия<input v-model="form.lastName" required maxlength="80" autocomplete="family-name" :disabled="!!profile.pendingChangeRequest || !!busy" /></label><label>Телефон<input v-model="form.phone" type="tel" maxlength="24" pattern="\+?[0-9 \(\)\-]{7,24}" autocomplete="tel" aria-label="Телефон" aria-describedby="sa-phone-hint" :disabled="!!profile.pendingChangeRequest || !!busy" /><small id="sa-phone-hint">Изменение телефона подтверждает сотрудник.</small></label><label>Электронная почта<input :value="profile.email" type="email" aria-label="Электронная почта" readonly /><small>Для изменения почты обратитесь в поддержку.</small></label><label v-if="isB2C">Дата рождения<input v-model="form.birthday" type="date" aria-label="Дата рождения" aria-describedby="sa-birthday-hint" autocomplete="bday" min="1900-01-01" :max="birthdayMax || undefined" :disabled="!!profile.pendingChangeRequest || !!busy" /><small id="sa-birthday-hint">Для бонусов ко дню рождения. Дату изменяем после подтверждения сотрудником.</small></label></div><p class="sa-muted">{{ isB2C ? 'Изменение имени, фамилии, телефона и даты рождения подтверждает сотрудник.' : 'Изменение имени, фамилии и телефона подтверждает сотрудник.' }} До подтверждения действуют прежние данные.</p><p v-if="profile.pendingChangeRequest" class="sa-feedback" role="status">Запрос на изменение данных ожидает подтверждения.</p><button v-else class="sa-button" :disabled="!!busy">{{ busy === 'request' ? 'Отправляем…' : 'Запросить изменение' }}<ArrowRight :size="20" /></button></form>
  </section>
  <section class="sa-panel"><h2>Смена пароля</h2><p class="sa-muted">После смены пароля все сеансы будут завершены. Понадобится войти снова.</p><form class="sa-form" @submit.prevent="changePassword"><label>Текущий пароль<input v-model="password.currentPassword" type="password" required autocomplete="current-password" /></label><label>Новый пароль<input v-model="password.newPassword" aria-label="Новый пароль" type="password" required minlength="10" autocomplete="new-password" /><small>Не менее 10 символов, буквы и цифры.</small></label><label>Повторите новый пароль<input v-model="password.confirmation" type="password" required minlength="10" autocomplete="new-password" /></label><button class="sa-button" :disabled="!!busy">{{ busy === 'password' ? 'Меняем пароль…' : 'Изменить пароль' }}<ArrowRight :size="20" /></button></form></section>
  <SiteAccountDrawer :open="confirmAvatar" title="Удалить фото?" @close="!busy && (confirmAvatar = false)"><p>Фото будет удалено из вашего профиля. Позже можно загрузить другое.</p><p v-if="error" role="alert">{{ error }}</p><div class="sa-actions"><button class="sa-button sa-secondary" :disabled="!!busy" @click="confirmAvatar = false">Отмена</button><button class="sa-button" :disabled="!!busy" @click="removeAvatar">Удалить фото <Trash2 :size="20" /></button></div></SiteAccountDrawer>
</div></template>
