
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AdminMediaBrowser: typeof import("../components/AdminMediaBrowser.vue")['default']
export const AdminMediaPicker: typeof import("../components/AdminMediaPicker.vue")['default']
export const AdminNewProduct: typeof import("../components/AdminNewProduct.vue")['default']
export const AdminOrderDrawer: typeof import("../components/AdminOrderDrawer.vue")['default']
export const AdminProductEditor: typeof import("../components/AdminProductEditor.vue")['default']
export const B2BPortalRail: typeof import("../components/B2BPortalRail.vue")['default']
export const BotCommandsSettings: typeof import("../components/BotCommandsSettings.vue")['default']
export const BusinessCatalog: typeof import("../components/BusinessCatalog.vue")['default']
export const BusinessOrders: typeof import("../components/BusinessOrders.vue")['default']
export const BusinessPurchasesDashboard: typeof import("../components/BusinessPurchasesDashboard.vue")['default']
export const BusinessSettings: typeof import("../components/BusinessSettings.vue")['default']
export const BusinessToolbar: typeof import("../components/BusinessToolbar.vue")['default']
export const ConsoleRail: typeof import("../components/ConsoleRail.vue")['default']
export const CrmPipelineSettings: typeof import("../components/CrmPipelineSettings.vue")['default']
export const CrmTaskAutomation: typeof import("../components/CrmTaskAutomation.vue")['default']
export const EcosystemAccounts: typeof import("../components/EcosystemAccounts.vue")['default']
export const EcosystemIntegrations: typeof import("../components/EcosystemIntegrations.vue")['default']
export const EcosystemTrash: typeof import("../components/EcosystemTrash.vue")['default']
export const IntegrationBrandLogo: typeof import("../components/IntegrationBrandLogo.vue")['default']
export const MarketplaceRail: typeof import("../components/MarketplaceRail.vue")['default']
export const PlatformChatDrawer: typeof import("../components/PlatformChatDrawer.vue")['default']
export const SalonBookingForm: typeof import("../components/SalonBookingForm.vue")['default']
export const SalonCalendar: typeof import("../components/SalonCalendar.vue")['default']
export const SalonClients: typeof import("../components/SalonClients.vue")['default']
export const SalonDashboard: typeof import("../components/SalonDashboard.vue")['default']
export const SalonOnlineBookingSettings: typeof import("../components/SalonOnlineBookingSettings.vue")['default']
export const SalonOrganizationCard: typeof import("../components/SalonOrganizationCard.vue")['default']
export const SalonPresentationSettings: typeof import("../components/SalonPresentationSettings.vue")['default']
export const SalonServices: typeof import("../components/SalonServices.vue")['default']
export const SalonTeam: typeof import("../components/SalonTeam.vue")['default']
export const SalonWeeklySchedule: typeof import("../components/SalonWeeklySchedule.vue")['default']
export const TaskReminderCenter: typeof import("../components/TaskReminderCenter.vue")['default']
export const UserProfileDrawer: typeof import("../components/UserProfileDrawer.vue")['default']
export const WorkspaceContextMenu: typeof import("../components/WorkspaceContextMenu.vue")['default']
export const WorkspaceLoading: typeof import("../components/WorkspaceLoading.vue")['default']
export const WorkspaceOrdersTable: typeof import("../components/WorkspaceOrdersTable.vue")['default']
export const WorkspaceOverview: typeof import("../components/WorkspaceOverview.vue")['default']
export const WorkspaceSectionIcon: typeof import("../components/WorkspaceSectionIcon.vue")['default']
export const WorkspaceToolbar: typeof import("../components/WorkspaceToolbar.vue")['default']
export const ProductCard: typeof import("../components/storefront/ProductCard.vue")['default']
export const SiteAccountAddresses: typeof import("../components/storefront/SiteAccountAddresses.vue")['default']
export const SiteAccountDashboard: typeof import("../components/storefront/SiteAccountDashboard.vue")['default']
export const SiteAccountDrawer: typeof import("../components/storefront/SiteAccountDrawer.vue")['default']
export const SiteAccountGiftCards: typeof import("../components/storefront/SiteAccountGiftCards.vue")['default']
export const SiteAccountNotifications: typeof import("../components/storefront/SiteAccountNotifications.vue")['default']
export const SiteAccountOrders: typeof import("../components/storefront/SiteAccountOrders.vue")['default']
export const SiteAccountProfile: typeof import("../components/storefront/SiteAccountProfile.vue")['default']
export const SiteAuthDrawer: typeof import("../components/storefront/SiteAuthDrawer.vue")['default']
export const SiteBusinessPage: typeof import("../components/storefront/SiteBusinessPage.vue")['default']
export const SiteBusinessPreview: typeof import("../components/storefront/SiteBusinessPreview.vue")['default']
export const SiteCartDrawer: typeof import("../components/storefront/SiteCartDrawer.vue")['default']
export const SiteCartRecommendations: typeof import("../components/storefront/SiteCartRecommendations.vue")['default']
export const SiteCatalogDrawer: typeof import("../components/storefront/SiteCatalogDrawer.vue")['default']
export const SiteCatalogFilters: typeof import("../components/storefront/SiteCatalogFilters.vue")['default']
export const SiteCatalogMenuEditor: typeof import("../components/storefront/SiteCatalogMenuEditor.vue")['default']
export const SiteCatalogPage: typeof import("../components/storefront/SiteCatalogPage.vue")['default']
export const SiteCategoriesEditor: typeof import("../components/storefront/SiteCategoriesEditor.vue")['default']
export const SiteCheckout: typeof import("../components/storefront/SiteCheckout.vue")['default']
export const SiteClubBlock: typeof import("../components/storefront/SiteClubBlock.vue")['default']
export const SiteClubReferral: typeof import("../components/storefront/SiteClubReferral.vue")['default']
export const SiteClubReferralStack: typeof import("../components/storefront/SiteClubReferralStack.vue")['default']
export const SiteContactForm: typeof import("../components/storefront/SiteContactForm.vue")['default']
export const SiteContentEditor: typeof import("../components/storefront/SiteContentEditor.vue")['default']
export const SiteContentPage: typeof import("../components/storefront/SiteContentPage.vue")['default']
export const SiteFavoritesDrawer: typeof import("../components/storefront/SiteFavoritesDrawer.vue")['default']
export const SiteFooter: typeof import("../components/storefront/SiteFooter.vue")['default']
export const SiteFounderBiography: typeof import("../components/storefront/SiteFounderBiography.vue")['default']
export const SiteGiftCardsEditor: typeof import("../components/storefront/SiteGiftCardsEditor.vue")['default']
export const SiteHeader: typeof import("../components/storefront/SiteHeader.vue")['default']
export const SiteLoyaltyPreview: typeof import("../components/storefront/SiteLoyaltyPreview.vue")['default']
export const SiteMenuDrawer: typeof import("../components/storefront/SiteMenuDrawer.vue")['default']
export const SiteMenuLink: typeof import("../components/storefront/SiteMenuLink.vue")['default']
export const SitePageArt: typeof import("../components/storefront/SitePageArt.vue")['default']
export const SitePagesEditor: typeof import("../components/storefront/SitePagesEditor.vue")['default']
export const SitePartnerAccount: typeof import("../components/storefront/SitePartnerAccount.vue")['default']
export const SitePartnerLink: typeof import("../components/storefront/SitePartnerLink.vue")['default']
export const SitePartnershipBlock: typeof import("../components/storefront/SitePartnershipBlock.vue")['default']
export const SitePartnershipPage: typeof import("../components/storefront/SitePartnershipPage.vue")['default']
export const SitePartnershipScene: typeof import("../components/storefront/SitePartnershipScene.vue")['default']
export const SiteProductBadgesEditor: typeof import("../components/storefront/SiteProductBadgesEditor.vue")['default']
export const SiteProductPage: typeof import("../components/storefront/SiteProductPage.vue")['default']
export const SitePromoCodesEditor: typeof import("../components/storefront/SitePromoCodesEditor.vue")['default']
export const SiteQuantityControl: typeof import("../components/storefront/SiteQuantityControl.vue")['default']
export const SiteShell: typeof import("../components/storefront/SiteShell.vue")['default']
export const SiteSocialLoginButtons: typeof import("../components/storefront/SiteSocialLoginButtons.vue")['default']
export const ChannelsWorkspacePage: typeof import("../components/workspace/ChannelsWorkspacePage.vue")['default']
export const ContactMessagesWorkspace: typeof import("../components/workspace/ContactMessagesWorkspace.vue")['default']
export const PartnerWorkspacePage: typeof import("../components/workspace/PartnerWorkspacePage.vue")['default']
export const ReportsWorkspacePage: typeof import("../components/workspace/ReportsWorkspacePage.vue")['default']
export const StoreDashboard: typeof import("../components/workspace/StoreDashboard.vue")['default']
export const StoreWorkspacePage: typeof import("../components/workspace/StoreWorkspacePage.vue")['default']
export const SupportWorkspacePage: typeof import("../components/workspace/SupportWorkspacePage.vue")['default']
export const SystemWorkspacePage: typeof import("../components/workspace/SystemWorkspacePage.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAdminMediaBrowser: LazyComponent<typeof import("../components/AdminMediaBrowser.vue")['default']>
export const LazyAdminMediaPicker: LazyComponent<typeof import("../components/AdminMediaPicker.vue")['default']>
export const LazyAdminNewProduct: LazyComponent<typeof import("../components/AdminNewProduct.vue")['default']>
export const LazyAdminOrderDrawer: LazyComponent<typeof import("../components/AdminOrderDrawer.vue")['default']>
export const LazyAdminProductEditor: LazyComponent<typeof import("../components/AdminProductEditor.vue")['default']>
export const LazyB2BPortalRail: LazyComponent<typeof import("../components/B2BPortalRail.vue")['default']>
export const LazyBotCommandsSettings: LazyComponent<typeof import("../components/BotCommandsSettings.vue")['default']>
export const LazyBusinessCatalog: LazyComponent<typeof import("../components/BusinessCatalog.vue")['default']>
export const LazyBusinessOrders: LazyComponent<typeof import("../components/BusinessOrders.vue")['default']>
export const LazyBusinessPurchasesDashboard: LazyComponent<typeof import("../components/BusinessPurchasesDashboard.vue")['default']>
export const LazyBusinessSettings: LazyComponent<typeof import("../components/BusinessSettings.vue")['default']>
export const LazyBusinessToolbar: LazyComponent<typeof import("../components/BusinessToolbar.vue")['default']>
export const LazyConsoleRail: LazyComponent<typeof import("../components/ConsoleRail.vue")['default']>
export const LazyCrmPipelineSettings: LazyComponent<typeof import("../components/CrmPipelineSettings.vue")['default']>
export const LazyCrmTaskAutomation: LazyComponent<typeof import("../components/CrmTaskAutomation.vue")['default']>
export const LazyEcosystemAccounts: LazyComponent<typeof import("../components/EcosystemAccounts.vue")['default']>
export const LazyEcosystemIntegrations: LazyComponent<typeof import("../components/EcosystemIntegrations.vue")['default']>
export const LazyEcosystemTrash: LazyComponent<typeof import("../components/EcosystemTrash.vue")['default']>
export const LazyIntegrationBrandLogo: LazyComponent<typeof import("../components/IntegrationBrandLogo.vue")['default']>
export const LazyMarketplaceRail: LazyComponent<typeof import("../components/MarketplaceRail.vue")['default']>
export const LazyPlatformChatDrawer: LazyComponent<typeof import("../components/PlatformChatDrawer.vue")['default']>
export const LazySalonBookingForm: LazyComponent<typeof import("../components/SalonBookingForm.vue")['default']>
export const LazySalonCalendar: LazyComponent<typeof import("../components/SalonCalendar.vue")['default']>
export const LazySalonClients: LazyComponent<typeof import("../components/SalonClients.vue")['default']>
export const LazySalonDashboard: LazyComponent<typeof import("../components/SalonDashboard.vue")['default']>
export const LazySalonOnlineBookingSettings: LazyComponent<typeof import("../components/SalonOnlineBookingSettings.vue")['default']>
export const LazySalonOrganizationCard: LazyComponent<typeof import("../components/SalonOrganizationCard.vue")['default']>
export const LazySalonPresentationSettings: LazyComponent<typeof import("../components/SalonPresentationSettings.vue")['default']>
export const LazySalonServices: LazyComponent<typeof import("../components/SalonServices.vue")['default']>
export const LazySalonTeam: LazyComponent<typeof import("../components/SalonTeam.vue")['default']>
export const LazySalonWeeklySchedule: LazyComponent<typeof import("../components/SalonWeeklySchedule.vue")['default']>
export const LazyTaskReminderCenter: LazyComponent<typeof import("../components/TaskReminderCenter.vue")['default']>
export const LazyUserProfileDrawer: LazyComponent<typeof import("../components/UserProfileDrawer.vue")['default']>
export const LazyWorkspaceContextMenu: LazyComponent<typeof import("../components/WorkspaceContextMenu.vue")['default']>
export const LazyWorkspaceLoading: LazyComponent<typeof import("../components/WorkspaceLoading.vue")['default']>
export const LazyWorkspaceOrdersTable: LazyComponent<typeof import("../components/WorkspaceOrdersTable.vue")['default']>
export const LazyWorkspaceOverview: LazyComponent<typeof import("../components/WorkspaceOverview.vue")['default']>
export const LazyWorkspaceSectionIcon: LazyComponent<typeof import("../components/WorkspaceSectionIcon.vue")['default']>
export const LazyWorkspaceToolbar: LazyComponent<typeof import("../components/WorkspaceToolbar.vue")['default']>
export const LazyProductCard: LazyComponent<typeof import("../components/storefront/ProductCard.vue")['default']>
export const LazySiteAccountAddresses: LazyComponent<typeof import("../components/storefront/SiteAccountAddresses.vue")['default']>
export const LazySiteAccountDashboard: LazyComponent<typeof import("../components/storefront/SiteAccountDashboard.vue")['default']>
export const LazySiteAccountDrawer: LazyComponent<typeof import("../components/storefront/SiteAccountDrawer.vue")['default']>
export const LazySiteAccountGiftCards: LazyComponent<typeof import("../components/storefront/SiteAccountGiftCards.vue")['default']>
export const LazySiteAccountNotifications: LazyComponent<typeof import("../components/storefront/SiteAccountNotifications.vue")['default']>
export const LazySiteAccountOrders: LazyComponent<typeof import("../components/storefront/SiteAccountOrders.vue")['default']>
export const LazySiteAccountProfile: LazyComponent<typeof import("../components/storefront/SiteAccountProfile.vue")['default']>
export const LazySiteAuthDrawer: LazyComponent<typeof import("../components/storefront/SiteAuthDrawer.vue")['default']>
export const LazySiteBusinessPage: LazyComponent<typeof import("../components/storefront/SiteBusinessPage.vue")['default']>
export const LazySiteBusinessPreview: LazyComponent<typeof import("../components/storefront/SiteBusinessPreview.vue")['default']>
export const LazySiteCartDrawer: LazyComponent<typeof import("../components/storefront/SiteCartDrawer.vue")['default']>
export const LazySiteCartRecommendations: LazyComponent<typeof import("../components/storefront/SiteCartRecommendations.vue")['default']>
export const LazySiteCatalogDrawer: LazyComponent<typeof import("../components/storefront/SiteCatalogDrawer.vue")['default']>
export const LazySiteCatalogFilters: LazyComponent<typeof import("../components/storefront/SiteCatalogFilters.vue")['default']>
export const LazySiteCatalogMenuEditor: LazyComponent<typeof import("../components/storefront/SiteCatalogMenuEditor.vue")['default']>
export const LazySiteCatalogPage: LazyComponent<typeof import("../components/storefront/SiteCatalogPage.vue")['default']>
export const LazySiteCategoriesEditor: LazyComponent<typeof import("../components/storefront/SiteCategoriesEditor.vue")['default']>
export const LazySiteCheckout: LazyComponent<typeof import("../components/storefront/SiteCheckout.vue")['default']>
export const LazySiteClubBlock: LazyComponent<typeof import("../components/storefront/SiteClubBlock.vue")['default']>
export const LazySiteClubReferral: LazyComponent<typeof import("../components/storefront/SiteClubReferral.vue")['default']>
export const LazySiteClubReferralStack: LazyComponent<typeof import("../components/storefront/SiteClubReferralStack.vue")['default']>
export const LazySiteContactForm: LazyComponent<typeof import("../components/storefront/SiteContactForm.vue")['default']>
export const LazySiteContentEditor: LazyComponent<typeof import("../components/storefront/SiteContentEditor.vue")['default']>
export const LazySiteContentPage: LazyComponent<typeof import("../components/storefront/SiteContentPage.vue")['default']>
export const LazySiteFavoritesDrawer: LazyComponent<typeof import("../components/storefront/SiteFavoritesDrawer.vue")['default']>
export const LazySiteFooter: LazyComponent<typeof import("../components/storefront/SiteFooter.vue")['default']>
export const LazySiteFounderBiography: LazyComponent<typeof import("../components/storefront/SiteFounderBiography.vue")['default']>
export const LazySiteGiftCardsEditor: LazyComponent<typeof import("../components/storefront/SiteGiftCardsEditor.vue")['default']>
export const LazySiteHeader: LazyComponent<typeof import("../components/storefront/SiteHeader.vue")['default']>
export const LazySiteLoyaltyPreview: LazyComponent<typeof import("../components/storefront/SiteLoyaltyPreview.vue")['default']>
export const LazySiteMenuDrawer: LazyComponent<typeof import("../components/storefront/SiteMenuDrawer.vue")['default']>
export const LazySiteMenuLink: LazyComponent<typeof import("../components/storefront/SiteMenuLink.vue")['default']>
export const LazySitePageArt: LazyComponent<typeof import("../components/storefront/SitePageArt.vue")['default']>
export const LazySitePagesEditor: LazyComponent<typeof import("../components/storefront/SitePagesEditor.vue")['default']>
export const LazySitePartnerAccount: LazyComponent<typeof import("../components/storefront/SitePartnerAccount.vue")['default']>
export const LazySitePartnerLink: LazyComponent<typeof import("../components/storefront/SitePartnerLink.vue")['default']>
export const LazySitePartnershipBlock: LazyComponent<typeof import("../components/storefront/SitePartnershipBlock.vue")['default']>
export const LazySitePartnershipPage: LazyComponent<typeof import("../components/storefront/SitePartnershipPage.vue")['default']>
export const LazySitePartnershipScene: LazyComponent<typeof import("../components/storefront/SitePartnershipScene.vue")['default']>
export const LazySiteProductBadgesEditor: LazyComponent<typeof import("../components/storefront/SiteProductBadgesEditor.vue")['default']>
export const LazySiteProductPage: LazyComponent<typeof import("../components/storefront/SiteProductPage.vue")['default']>
export const LazySitePromoCodesEditor: LazyComponent<typeof import("../components/storefront/SitePromoCodesEditor.vue")['default']>
export const LazySiteQuantityControl: LazyComponent<typeof import("../components/storefront/SiteQuantityControl.vue")['default']>
export const LazySiteShell: LazyComponent<typeof import("../components/storefront/SiteShell.vue")['default']>
export const LazySiteSocialLoginButtons: LazyComponent<typeof import("../components/storefront/SiteSocialLoginButtons.vue")['default']>
export const LazyChannelsWorkspacePage: LazyComponent<typeof import("../components/workspace/ChannelsWorkspacePage.vue")['default']>
export const LazyContactMessagesWorkspace: LazyComponent<typeof import("../components/workspace/ContactMessagesWorkspace.vue")['default']>
export const LazyPartnerWorkspacePage: LazyComponent<typeof import("../components/workspace/PartnerWorkspacePage.vue")['default']>
export const LazyReportsWorkspacePage: LazyComponent<typeof import("../components/workspace/ReportsWorkspacePage.vue")['default']>
export const LazyStoreDashboard: LazyComponent<typeof import("../components/workspace/StoreDashboard.vue")['default']>
export const LazyStoreWorkspacePage: LazyComponent<typeof import("../components/workspace/StoreWorkspacePage.vue")['default']>
export const LazySupportWorkspacePage: LazyComponent<typeof import("../components/workspace/SupportWorkspacePage.vue")['default']>
export const LazySystemWorkspacePage: LazyComponent<typeof import("../components/workspace/SystemWorkspacePage.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
